import { db } from "../../lib/db";

const BIO_PT_JPEN: Record<string, { pt: string; jpEn: string }> = {
  SSB4: {
    jpEn: "The unit that serves as the player's avatar in \"Fire Emblem: Awakening.\" Found having lost their memory, Robin is rescued by Chrom and the others. Robin's talent as a tactician is later recognized, and they travel together with Chrom's group. In \"Super Smash Bros.,\" Robin fights with magic and the Levin Sword. Robin has powerful moves, but each one has an individual usage limit. They recharge over time, so be careful not to overuse them.",
    pt: "A unidade que serve como avatar do jogador em Fire Emblem: Awakening. Encontrado tendo perdido a memória, Robin é resgatado por Chrom e os outros. Seu talento como estrategista é reconhecido depois, e passa a viajar junto com o grupo de Chrom. Em Smash Bros., Robin luta com magia e a Levin Sword. Robin tem golpes poderosos, mas cada um tem um limite individual de uso. Eles se recarregam com o tempo, então cuidado para não usá-los demais.",
  },
};

const TIPS = [
  { titleEn: "[★☆☆] Robin's Origins", titleJp: "ルフレの初登場作品", textJp: "ルフレのデビュー作は、２０１２年発売の『ファイアーエムブレム 覚醒』。プレイヤーの分身で、軍師としての才能をクロムに見込まれ、ともに戦う。", titleJpEn: "Robin's Debut Work", textJpEn: "Robin's debut work is 2012's \"Fire Emblem: Awakening.\" As the player's avatar, Robin's talent as a tactician is recognized by Chrom, and the two fight together.", titlePt: "As Origens do Robin", textPt: "O trabalho de estreia do Robin é \"Fire Emblem: Awakening\", lançado em 2012. Como avatar do jogador, o talento de Robin como estrategista é reconhecido por Chrom, e os dois lutam juntos." },
  { titleEn: "[★☆☆] In Their Series", titleJp: "原作では", textJp: "『ファイアーエムブレム 覚醒』に登場するマイユニット。性別や容姿などを設定できる。クロムに助けられたのち、軍師として自警団の仲間となり参戦する。", titleJpEn: "In the Original Game", textJpEn: "The customizable avatar unit that appears in \"Fire Emblem: Awakening.\" Gender and appearance can be set. After being rescued by Chrom, they join his militia as a tactician and fight alongside them.", titlePt: "Na Série Original", textPt: "A unidade avatar personalizável que aparece em \"Fire Emblem: Awakening\". Gênero e aparência podem ser definidos. Depois de ser resgatado por Chrom, ele se junta à milícia como estrategista e luta ao lado deles." },
  { titleEn: "[★☆☆] Nosferatu", titleJp: "リザイア", textJp: "原作においてはゲーム開始時に使うことはできなかった。ダークマージ系のクラスに転職すればリザイアの魔道書を装備できる。", titleJpEn: "Nosferatu", textJpEn: "In the original game, it couldn't be used at the start of the game. Reclassing into a Dark Mage-type class allows the Nosferatu tome to be equipped.", titlePt: "Nosferatu", textPt: "No jogo original, não era possível usá-lo no início do jogo. Trocar de classe para uma classe do tipo Mago das Trevas permite equipar o grimório Nosferatu." },
  { titleEn: "[★★☆] Thunder (Neutral Special)", titleJp: "サンダー 【通常必殺ワザ】", textJp: "ためずにすぐ発射すると、「サンダー」になる。威力は低いが速く飛ぶので、不意打ちなどに有効。", titleJpEn: "Thunder (Neutral Special)", textJpEn: "Firing it immediately without charging results in \"Thunder.\" Its power is low, but it flies quickly, making it effective for surprise attacks.", titlePt: "Thunder (Especial Neutro)", textPt: "Disparar imediatamente sem carregar resulta em \"Thunder\". Seu poder é baixo, mas voa rápido, tornando-o eficaz para ataques surpresa." },
  { titleEn: "[★☆☆] Thunder Types (Neutral Special)", titleJp: "サンダーの種類 【通常必殺ワザ】", textJp: "ためた時間によって、４種類の魔法を使い分けられる。魔道書の光の色で、ためた段階を確認できる。", titleJpEn: "Thunder's Types (Neutral Special)", textJpEn: "Depending on the charge time, four different types of magic can be used. The color the tome glows indicates the current charge stage.", titlePt: "Os Tipos de Thunder (Especial Neutro)", textPt: "Dependendo do tempo de carga, quatro tipos diferentes de magia podem ser usados. A cor que o grimório emite indica o estágio atual da carga." },
  { titleEn: "[★★☆] Thunder Charge Level 1 (Neutral Special)", titleJp: "サンダーの１段ためワザ 【通常必殺ワザ】", textJp: "光が黄色くなると、「エルサンダー」を発射できる。「サンダー」より威力が高く、遠くまで飛ぶが、少し遅い。", titleJpEn: "Thunder's First Charge Level (Neutral Special)", textJpEn: "When the glow turns yellow, \"Elthunder\" can be fired. It's more powerful than \"Thunder\" and travels farther, but is a bit slower.", titlePt: "O 1º Nível de Carga do Thunder (Especial Neutro)", textPt: "Quando o brilho fica amarelo, \"Elthunder\" pode ser disparado. É mais poderoso que \"Thunder\" e viaja mais longe, mas é um pouco mais lento." },
  { titleEn: "[★★☆] Thunder Charge Level 2 (Neutral Special)", titleJp: "サンダーの２段ためワザ 【通常必殺ワザ】", textJp: "光が赤紫になると、「ギガサンダー」を発射できる。何かに当たると広がる電流は、攻撃力が高い。", titleJpEn: "Thunder's Second Charge Level (Neutral Special)", textJpEn: "When the glow turns reddish-purple, \"Arcthunder\" can be fired. The current that spreads out on contact deals high damage.", titlePt: "O 2º Nível de Carga do Thunder (Especial Neutro)", textPt: "Quando o brilho fica roxo-avermelhado, \"Arcthunder\" pode ser disparado. A corrente que se espalha ao entrar em contato causa alto dano." },
  { titleEn: "[★★☆] Thunder at Max Charge (Neutral Special)", titleJp: "サンダーの最大ためワザ 【通常必殺ワザ】", textJp: "最大までためると、「トロン」を発射できる。高速で飛び貫通するレーザーは、複数の相手を巻き込める。", titleJpEn: "Thunder at Maximum Charge (Neutral Special)", textJpEn: "Charging it to maximum allows \"Thoron\" to be fired. The high-speed, piercing beam can catch multiple opponents at once.", titlePt: "Thunder na Carga Máxima (Especial Neutro)", textPt: "Carregá-lo ao máximo permite disparar \"Thoron\". O feixe de alta velocidade e perfurante pode pegar múltiplos adversários de uma vez." },
  { titleEn: "[★★★] Reaching Thunder's Limits (Neutral Special)", titleJp: "サンダーの使用回数 【通常必殺ワザ】", textJp: "サンダーの最大使用回数は２０回。上位の魔法ほど魔道書を大きく消耗する。エルサンダーは３回分、ギガサンダーは５回分、トロンは８回分の消耗。", titleJpEn: "Thunder's Usage Count (Neutral Special)", textJpEn: "Thunder can be used a maximum of 20 times. Stronger spells consume the tome faster — Elthunder uses up 3 charges, Arcthunder 5, and Thoron 8.", titlePt: "O Número de Usos do Thunder (Especial Neutro)", textPt: "O Thunder pode ser usado no máximo 20 vezes. Feitiços mais fortes consomem o grimório mais rápido — Elthunder gasta 3 cargas, Arcthunder 5, e Thoron 8." },
  { titleEn: "[★★★] Reaching Arcfire's Limits (Side Special)", titleJp: "ギガファイアーの使用回数 【横必殺ワザ】", textJp: "ギガファイアーの最大使用回数は６回。使い切ると魔道書を手放し、それから１２秒間はギガファイアーを使うことができない。", titleJpEn: "Arcfire's Usage Count (Side Special)", textJpEn: "Arcfire can be used a maximum of 6 times. Once used up, the tome is discarded, and Arcfire can't be used again for 12 seconds.", titlePt: "O Número de Usos do Arcfire (Especial Lateral)", textPt: "O Arcfire pode ser usado no máximo 6 vezes. Uma vez esgotado, o grimório é descartado, e o Arcfire não pode ser usado novamente por 12 segundos." },
  { titleEn: "[★☆☆] Elwind (Up Special)", titleJp: "エルウインド 【上必殺ワザ】", textJp: "１つ目のエルウインドの攻撃のみ、放った直後にメテオ効果がある。また、攻撃が地面にぶつかると風が起こり、触れた相手を押し出すことができる。", titleJpEn: "Elwind (Up Special)", textJpEn: "Only the first Elwind hit has a meteor effect right after it's released. Also, when the attack hits the ground, it creates a gust of wind that can push away any opponent it touches.", titlePt: "Elwind (Especial Cima)", textPt: "Apenas o primeiro golpe do Elwind tem efeito meteoro logo após ser liberado. Além disso, quando o ataque atinge o chão, cria uma rajada de vento que pode empurrar qualquer adversário que tocar." },
  { titleEn: "[★★★] Reaching Elwind's Limits (Up Special)", titleJp: "エルウインドの使用回数 【上必殺ワザ】", textJp: "１度の使用でエルウインドを２回出して上昇し、魔道書をその分消費する。２回分の耐久値がない場合、出せるエルウインドは１回になり、飛び上がる高さが低くなる。", titleJpEn: "Elwind's Usage Count (Up Special)", textJpEn: "A single use fires Elwind twice while rising, consuming that many charges from the tome. If there aren't enough charges left for two, only one Elwind will come out, resulting in a lower rise.", titlePt: "O Número de Usos do Elwind (Especial Cima)", textPt: "Um único uso dispara o Elwind duas vezes enquanto sobe, consumindo essa quantidade de cargas do grimório. Se não houver cargas suficientes para dois, apenas um Elwind sairá, resultando em uma subida menor." },
  { titleEn: "[★★★] Reaching Nosferatu's Limits (Down Special)", titleJp: "リザイアの使用回数 【下必殺ワザ】", textJp: "リザイアの最大使用回数は３回。回復にも使える強力なワザなので少なめ。使い切った後、再使用できるまでの時間も３０秒とかなり長い。", titleJpEn: "Nosferatu's Usage Count (Down Special)", textJpEn: "Nosferatu can be used a maximum of 3 times. Since it's a powerful move that can also heal, its uses are kept low. After it's used up, it also takes quite a long time — 30 seconds — before it can be used again.", titlePt: "O Número de Usos do Nosferatu (Especial Baixo)", textPt: "O Nosferatu pode ser usado no máximo 3 vezes. Como é um golpe poderoso que também pode curar, seus usos são mantidos baixos. Depois de esgotado, também leva bastante tempo — 30 segundos — até poder ser usado novamente." },
  { titleEn: "[★☆☆] Pair Up (Final Smash)", titleJp: "ダブル 【最後の切りふだ】", textJp: "クロムの突進が相手に当たり攻撃が成功すれば、ワザが終わった後に各魔道書やサンダーソードの使用回数が全回復する。", titleJpEn: "Dual Strike (Final Smash)", textJpEn: "If Chrom's charge hits the opponent and the attack succeeds, all of the tomes' and the Levin Sword's usage counts are fully restored once the move ends.", titlePt: "Pair Up (Final Smash)", textPt: "Se a investida do Chrom acertar o adversário e o ataque for bem-sucedido, todos os usos dos grimórios e da Levin Sword são totalmente restaurados quando o golpe termina." },
  { titleEn: "[★☆☆] Neutral Attack", titleJp: "弱攻撃", textJp: "３段目はファイアーで、相手を強くふっとばす。百裂攻撃はウインドで相手を切り刻み、大ダメージを与える。どちらも魔道書を消費。", titleJpEn: "Neutral Attack", textJpEn: "The third hit uses Fire, launching opponents with great force. The flurry attack uses Wind to repeatedly slash opponents, dealing heavy damage. Both consume a tome charge.", titlePt: "Ataque Neutro", textPt: "O terceiro golpe usa Fire, lançando os adversários com grande força. O ataque em rajada usa Wind para cortar repetidamente os adversários, causando muito dano. Ambos consomem uma carga do grimório." },
  { titleEn: "[★★★] Undercut (Down Air Attack)", titleJp: "アンダーカット 【下空中攻撃】", textJp: "青銅の剣ではメテオ効果は発生しないけれど、サンダーソードで空中の相手に当てた時だけメテオ効果が発生する。", titleJpEn: "Undercut (Down Air Attack)", textJpEn: "This move has no meteor effect with the Bronze Sword, but it does gain a meteor effect when it hits an airborne opponent with the Levin Sword.", titlePt: "Undercut (Ataque Aéreo Baixo)", textPt: "Este golpe não tem efeito meteoro com a Bronze Sword, mas ganha efeito meteoro ao acertar um adversário no ar com a Levin Sword." },
  { titleEn: "[★★☆] Neutral Air Attack with the Levin Sword", titleJp: "サンダーソードで通常空中攻撃", textJp: "青銅の剣を持っていても、空中で攻撃ボタンと必殺ワザボタンを同時に押せば、即座にサンダーソードに持ち替え、通常空中攻撃を出すことができる。", titleJpEn: "Neutral Air Attack with the Levin Sword", textJpEn: "Even while holding the Bronze Sword, pressing the attack and special move buttons at the same time in midair instantly switches to the Levin Sword to perform a neutral air attack.", titlePt: "Ataque Aéreo Neutro com a Levin Sword", textPt: "Mesmo segurando a Bronze Sword, apertar os botões de ataque e golpe especial ao mesmo tempo no ar troca instantaneamente para a Levin Sword para realizar um ataque aéreo neutro." },
  { titleEn: "[★★★] Reaching the Levin Sword's Limits", titleJp: "サンダーソードの使用回数", textJp: "サンダーソードの最大使用回数は８回。使い切ると手放し、１０秒間は再使用できない。また、地上で弱攻撃などを出すと、青銅の剣に持ち替え攻撃する。", titleJpEn: "The Levin Sword's Usage Count", textJpEn: "The Levin Sword can be used a maximum of 8 times. Once used up, it's discarded and can't be used again for 10 seconds. Also, using a neutral attack or similar move on the ground switches to attacking with the Bronze Sword.", titlePt: "O Número de Usos da Levin Sword", textPt: "A Levin Sword pode ser usada no máximo 8 vezes. Uma vez esgotada, é descartada e não pode ser usada novamente por 10 segundos. Além disso, usar um ataque neutro ou similar no chão troca para atacar com a Bronze Sword." },
  { titleEn: "[★★☆] Levin Sword's Recovery Time", titleJp: "サンダーソードの復活", textJp: "サンダーソードを使い切った時は、青銅の剣によるスマッシュ攻撃や、空中攻撃をはじき入力で出すことで、サンダーソードが復活するまでの時間を短縮できる。", titleJpEn: "The Levin Sword's Return", textJpEn: "When the Levin Sword has been used up, performing smash attacks with the Bronze Sword or aerial attacks with a flick input can shorten the time until the Levin Sword returns.", titlePt: "O Retorno da Levin Sword", textPt: "Quando a Levin Sword foi esgotada, realizar ataques smash com a Bronze Sword ou ataques aéreos com input de flick pode reduzir o tempo até a Levin Sword voltar." },
  { titleEn: "[★★☆] Using the Levin Sword", titleJp: "サンダーソードの使用タイミング", textJp: "乱闘開始時、サンダーソードは使えない状態だが、時間が経つと使えるようになる。逆に、魔道書は最初から使用回数が最大となっている。", titleJpEn: "Timing of the Levin Sword's Use", textJpEn: "At the start of a battle, the Levin Sword can't be used, but it becomes available as time passes. Conversely, the tomes start with their usage count already at maximum.", titlePt: "O Momento de Uso da Levin Sword", textPt: "No início de uma luta, a Levin Sword não pode ser usada, mas fica disponível conforme o tempo passa. Por outro lado, os grimórios já começam com o número de usos no máximo." },
  { titleEn: "[★☆☆] Throwing Tome and Levin Sword", titleJp: "魔道書とサンダーソードの投げ", textJp: "使い切って投げ捨てた魔道書やサンダーソードは、相手に当たればダメージを与える。落ちたものはアイテムとして拾って放り投げられる。", titleJpEn: "Throwing the Tome and Levin Sword", textJpEn: "A tome or Levin Sword that's been used up and discarded will deal damage if it hits an opponent. Once it falls, it can be picked up as an item and thrown.", titlePt: "Arremessando o Grimório e a Levin Sword", textPt: "Um grimório ou Levin Sword que tenha sido esgotado e descartado causa dano se atingir um adversário. Uma vez caído, pode ser pego como item e arremessado." },
  { titleEn: "[★☆☆] Tome and Levin Sword Recovery", titleJp: "魔道書とサンダーソードの回復", textJp: "基本的に魔道書やサンダーソードの使用回数は、一度撃墜されるか、使い切って捨てた後に再使用可能になるまで回復することは無い。", titleJpEn: "Tome and Levin Sword Recovery", textJpEn: "As a general rule, the usage count of tomes and the Levin Sword won't recover until either being KO'd once or being used up, discarded, and becoming usable again.", titlePt: "A Recuperação do Grimório e da Levin Sword", textPt: "Como regra geral, o número de usos dos grimórios e da Levin Sword não se recupera até ser nocauteado uma vez ou até serem esgotados, descartados e voltarem a ficar utilizáveis." },
  { titleEn: "[★★☆] Tome Care", titleJp: "魔道書の注意", textJp: "弱攻撃の３段目は、ギガファイアーと同じ魔道書を使っている。片方のワザで魔道書を使い切ると同時に２つのワザが使えなくなる。", titleJpEn: "Tome Caution", textJpEn: "The third hit of the neutral attack combo uses the same tome as Arcfire. Using up the tome with one move makes both moves unusable at the same time.", titlePt: "Cuidado com o Grimório", textPt: "O terceiro golpe do combo de ataque neutro usa o mesmo grimório que o Arcfire. Esgotar o grimório com um golpe torna ambos os golpes inutilizáveis ao mesmo tempo." },
  { titleEn: "[★★☆] Tome Changes", titleJp: "魔道書の変化", textJp: "乱闘中には気づきにくいが、ためた段階によって魔道書の表紙が変わっている。", titleJpEn: "Tome Changes", textJpEn: "It's hard to notice during a battle, but the tome's cover actually changes depending on the charge level.", titlePt: "Mudanças no Grimório", textPt: "É difícil perceber durante uma luta, mas a capa do grimório na verdade muda dependendo do nível de carga." },
  { titleEn: "[★★☆] Flurry Attack and Elwind", titleJp: "百裂攻撃とエルウインド", textJp: "百裂攻撃とエルウインドは、同じ魔道書を使用している。百裂攻撃を多用しすぎると、いざ復帰したいときにエルウインドが使えなくなることも。", titleJpEn: "Flurry Attack and Elwind", textJpEn: "The flurry attack and Elwind use the same tome. Overusing the flurry attack can leave Elwind unusable right when it's needed for recovery.", titlePt: "Ataque em Rajada e Elwind", textPt: "O ataque em rajada e o Elwind usam o mesmo grimório. Usar demais o ataque em rajada pode deixar o Elwind inutilizável justamente quando é necessário para recuperação." },
  { titleEn: "[★★☆] Regenerating Tomes and Swords", titleJp: "撃墜による復活時間の短縮", textJp: "魔道書やサンダーソードを使い切って手放した後、再使用できるまでに必要な時間は、相手を撃墜すると少しだけ短縮することができる。", titleJpEn: "Shortening Recovery Time by KOing Opponents", textJpEn: "After a tome or the Levin Sword has been used up and discarded, the time needed before it can be used again can be shortened slightly by KOing an opponent.", titlePt: "Reduzindo o Tempo de Recarga ao Nocautear Adversários", textPt: "Depois que um grimório ou a Levin Sword é esgotado e descartado, o tempo necessário até poder ser usado novamente pode ser reduzido um pouco ao nocautear um adversário." },
];

async function main() {
  const robin = await db.fighter.findFirst({
    where: { name: "Robin" },
    select: {
      id: true,
      bios: { select: { id: true, smashGameVersion: true } },
      moves: { select: { id: true, smashGameVersion: true, order: true } },
      tips: { select: { id: true, titleEn: true } },
    },
  });
  if (!robin) { console.log("Robin not found"); return; }

  await db.fighter.update({
    where: { id: robin.id },
    data: {
      curatorOverviewEn: "Robin, the tactician avatar from Fire Emblem: Awakening, plays like a resource-management puzzle wrapped around a fighter. Every tome and the Levin Sword has a hard usage limit — Thunder's four charge tiers trade speed for power and tome consumption, Arcfire threatens the ledge with a lingering pillar of flame, and Nosferatu offers rare life-steal at a steep cost. Elwind doubles as a meteor smash and a recovery tool, though depleting the tome shared with the flurry attack can strand Robin without a way back to the stage. The reward for careful charge management is access to some of the best zoning and burst damage in the game; the punishment for carelessness is being reduced to a weak Bronze Sword with none of Robin's signature tools.",
      curatorOverviewPt: "Robin, o avatar estrategista de Fire Emblem: Awakening, joga como um quebra-cabeça de gerenciamento de recursos disfarçado de lutador. Todo grimório e a Levin Sword têm um limite rígido de uso — os quatro níveis de carga do Thunder trocam velocidade por poder e consumo de grimório, Arcfire ameaça a borda com uma coluna de fogo persistente, e Nosferatu oferece um raro roubo de vida a um custo alto. Elwind funciona tanto como um meteoro quanto como ferramenta de recuperação, embora esgotar o grimório compartilhado com o ataque em rajada possa deixar Robin sem como voltar ao palco. A recompensa por um gerenciamento cuidadoso de carga é acesso a um dos melhores controles de área e dano em rajada do jogo; a punição por descuido é ser reduzido a uma Bronze Sword fraca, sem nenhuma das ferramentas características de Robin.",
      curatorOverviewJp: "『ファイアーエムブレム 覚醒』の軍師アバター、ルフレは、ファイターの姿をしたリソース管理パズルのようにプレイする。すべての魔道書とサンダーソードには厳格な使用回数の上限があり――「サンダー」の４段階のためは速度と威力・魔道書消費のトレードオフを持ち、「ギガファイアー」は残り続ける火柱でガケ際を脅かし、「リザイア」は高いコストと引き換えに貴重な回復手段を提供する。「エルウインド」はメテオ技と復帰技を兼ねるが、百裂攻撃と共有する魔道書を使い切ってしまうと、ステージへ戻る手段を失いかねない。慎重な使用回数管理の見返りは、ゲーム屈指の牽制力と瞬間火力へのアクセスであり、不注意の代償は、ルフレならではの武器を失った弱い青銅の剣に成り下がることだ。",
      curatorOverviewJpEn: "Robin, the tactician avatar from \"Fire Emblem: Awakening,\" plays like a resource-management puzzle disguised as a fighter. Every tome and the Levin Sword has a strict usage limit — Thunder's four charge levels trade speed for power and tome consumption, Arcfire threatens the ledge with a lingering pillar of flame, and Nosferatu offers a rare recovery tool at a steep cost. Elwind serves double duty as a meteor move and a recovery move, but using up the tome it shares with the flurry attack can leave Robin with no way back to the stage. The reward for careful usage management is access to some of the best zoning and burst damage in the game; the price of carelessness is being reduced to a weak Bronze Sword, stripped of all of Robin's signature tools.",
    },
  });
  console.log("✅ Curator Overview (4 langs)");

  for (const [version, data] of Object.entries(BIO_PT_JPEN)) {
    const bio = robin.bios.find(b => b.smashGameVersion === version);
    if (!bio) continue;
    await db.fighterBio.update({ where: { id: bio.id }, data: { contentPt: data.pt, contentJpEn: data.jpEn } });
    console.log(`✅ Bio [${version}]: PT+JpEn adicionados`);
  }

  const move = robin.moves.find(m => m.smashGameVersion === "SSB4" && m.order === 0);
  if (move) {
    const en = "Robin's magic is powerful but comes with usage limits. The Neutral Special \"Thunder\" transforms into \"Thoron\" when charged to maximum, boosting its power and projectile speed. Charging can be canceled and resumed partway through. \"Arcfire\" is a Side Special that raises a pillar of flame when the fire it releases touches terrain, an opponent, or an item. Using it near the ledge against an opponent off-stage can stop their recovery. (3DS) Fire Emblem: Awakening (2012/04)";
    await db.fighterMove.update({
      where: { id: move.id },
      data: {
        descEn: en, descJpEn: en,
        descPt: "A magia de Robin é poderosa, mas tem limites de uso. O especial neutro \"Thunder\" se transforma em \"Thoron\" quando carregado ao máximo, aumentando seu poder e a velocidade do projétil. A carga pode ser cancelada e retomada no meio do caminho. \"Arcfire\" é um especial lateral que ergue uma coluna de fogo quando as chamas liberadas tocam o terreno, um adversário ou um item. Usá-lo perto da borda contra um adversário fora do palco pode impedir sua recuperação. (3DS) Fire Emblem: Awakening (2012/04)",
      },
    });
    console.log("✅ Move [SSB4] EX: EN+PT+JpEn adicionados");
  }

  let updated = 0;
  for (const data of TIPS) {
    const tip = robin.tips.find(t => t.titleEn === data.titleEn);
    if (!tip) { console.log(`  ⚠️  Tip não encontrada: "${data.titleEn}"`); continue; }
    await db.fighterTip.update({
      where: { id: tip.id },
      data: {
        titleJp: data.titleJp, textJp: data.textJp,
        titleJpEn: data.titleJpEn, textJpEn: data.textJpEn,
        titlePt: data.titlePt, textPt: data.textPt,
      },
    });
    updated++;
  }
  console.log(`✅ ${updated}/${TIPS.length} tips atualizadas`);

  // Video fix (usuário via VLC): WiiU 1:26:52-1:27:02 = 5212-5222 no troféu principal
  const main = await db.collectible.findFirst({ where: { name: "Robin", type: "TROPHY", smashGameVersion: "SSB4" }, select: { id: true, videoStartSec: true, videoEndSec: true } });
  if (main) {
    await db.collectible.update({ where: { id: main.id }, data: { videoStartSec: 5212, videoEndSec: 5222 } });
    console.log(`✅ Trophy "Robin" [SSB4]: vídeo WiiU corrigido 5212-5222 (era ${main.videoStartSec}-${main.videoEndSec})`);
  }

  // NOTE: "Ashley Robbins" (Ashley Mizuki Robins, WarioWare) — falso positivo da busca
  // por substring "Robin", não linkado.

  await db.$disconnect();
}
main().catch(console.error);
