import { db } from "../../lib/db";

const BIO_PT_JPEN: Record<string, { pt: string; jpEn: string }> = {
  SSB4: {
    jpEn: "Joins the fight from the \"Street Fighter\" series. His fighting style is based on karate, but he incorporates techniques from other schools to fight with his own unique style. In \"Super Smash Bros.,\" his first jab and his strong attacks each have two patterns, letting him change the move by releasing the attack button quickly or holding it down longer. Each Special move can be varied across three power levels using the same method.",
    pt: "Entra na luta vindo da série \"Street Fighter\". Seu estilo de luta é baseado em karatê, mas ele incorpora técnicas de outras escolas para lutar com um estilo próprio e único. Em \"Super Smash Bros.\", seu primeiro golpe fraco e seus ataques fortes têm cada um dois padrões, permitindo mudar o golpe soltando o botão de ataque rapidamente ou segurando por mais tempo. Cada golpe especial também pode variar entre três níveis de poder usando o mesmo método.",
  },
};

const TIPS = [
  { titleEn: "[★☆☆] In His Series", titleJp: "原作では", textJp: "『ストリートファイター』シリーズ全てに登場する、メインのキャラクター。真の格闘家を目指し、世界中を旅している。１作目では、髪の色が赤かった。", titleJpEn: "In the Original Games", textJpEn: "The main character who appears in every game in the \"Street Fighter\" series. He travels the world in pursuit of becoming a true martial artist. In the first game, his hair was red.", titlePt: "Na Série Original", textPt: "O personagem principal que aparece em todos os jogos da série \"Street Fighter\". Ele viaja pelo mundo em busca de se tornar um verdadeiro lutador marcial. No primeiro jogo, seu cabelo era vermelho." },
  { titleEn: "[★☆☆] Hadoken (Neutral Special)", titleJp: "波動拳 【通常必殺ワザ】", textJp: "世界で一番有名な格闘ゲームの「飛び道具」。ボタンを押している長さで弾の速度が変化して一定距離を飛ぶと消滅する。", titleJpEn: "Hadoken (Neutral Special)", textJpEn: "The most famous \"projectile\" in fighting games worldwide. The length the button is held changes the speed of the blast, which disappears after traveling a set distance.", titlePt: "Hadoken (Especial Neutro)", textPt: "O \"projétil\" mais famoso dos jogos de luta no mundo todo. O tempo que o botão é segurado muda a velocidade do disparo, que desaparece depois de percorrer uma certa distância." },
  { titleEn: "[★☆☆] Hadoken (Neutral Special / Command-Input Move)", titleJp: "波動拳 【通常必殺・コマンド入力ワザ】", textJp: "原作のようにコマンド入力して出すと、通常の波動拳よりも攻撃力が高くなる。空中で出すとリュウが少しふわりと浮く。", titleJpEn: "Hadoken (Neutral Special / Command-Input Move)", textJpEn: "Using the command input from the original games gives it more power than the regular Hadoken. Using it in midair makes Ryu float slightly.", titlePt: "Hadoken (Especial Neutro / Golpe por Comando)", textPt: "Usar o input de comando dos jogos originais dá mais poder do que o Hadoken normal. Usá-lo no ar faz o Ryu flutuar levemente." },
  { titleEn: "[★☆☆] Hadoken's Power (Neutral Special / Command-Input Move)", titleJp: "波動拳の威力 【通常必殺・コマンド入力ワザ】", textJp: "右向き時、↓↘→と素早くコマンド入力することで攻撃力が１.２倍になる。慣れるまでは練習が必要。", titleJpEn: "Hadoken's Power (Neutral Special / Command-Input Move)", textJpEn: "When facing right, quickly inputting ↓↘→ increases attack power by 1.2x. It takes some practice to get used to.", titlePt: "O Poder do Hadoken (Especial Neutro / Golpe por Comando)", textPt: "Ao virar para a direita, inputar rapidamente ↓↘→ aumenta o poder de ataque em 1,2x. É preciso praticar um pouco para se acostumar." },
  { titleEn: "[★☆☆] Shakunetsu Hadoken (Neutral Special / Command-Input Move)", titleJp: "灼熱波動拳 【通常必殺・コマンド入力ワザ】", textJp: "右向き時、←↙↓↘→とコマンド入力を行うと、相手が燃えて多段ヒットする「灼熱波動拳」になる。", titleJpEn: "Shakunetsu Hadoken (Neutral Special / Command-Input Move)", textJpEn: "When facing right, inputting the command ←↙↓↘→ unleashes the \"Shakunetsu Hadoken,\" which sets the opponent on fire for multiple hits.", titlePt: "Shakunetsu Hadoken (Especial Neutro / Golpe por Comando)", textPt: "Ao virar para a direita, inputar o comando ←↙↓↘→ libera o \"Shakunetsu Hadoken\", que incendeia o adversário para múltiplos acertos." },
  { titleEn: "[★☆☆] Tatsumaki Senpukyaku (Side Special)", titleJp: "竜巻旋風脚 【横必殺ワザ】", textJp: "片足を横に伸ばして回転しながら移動する攻撃。ジャンプした直後に出すと少しだけ上昇するので復帰にも使える。", titleJpEn: "Tatsumaki Senpukyaku (Side Special)", textJpEn: "An attack where he extends one leg sideways and moves while spinning. Using it right after a jump causes a slight rise, so it can also be used for recovery.", titlePt: "Tatsumaki Senpukyaku (Especial Lateral)", textPt: "Um ataque em que ele estica uma perna lateralmente e se move enquanto gira. Usá-lo logo após um pulo causa uma leve subida, então também pode ser usado para recuperação." },
  { titleEn: "[★☆☆] Tatsumaki Senpukyaku (Side Special / Command-Input Move)", titleJp: "竜巻旋風脚 【横必殺・コマンド入力ワザ】", textJp: "原作のようにコマンド入力で出すと、通常の竜巻旋風脚よりも攻撃力が高くなる。空中では連続して出せない。", titleJpEn: "Tatsumaki Senpukyaku (Side Special / Command-Input Move)", textJpEn: "Using the command input from the original games gives it more power than the regular Tatsumaki Senpukyaku. It can't be used repeatedly in midair.", titlePt: "Tatsumaki Senpukyaku (Especial Lateral / Golpe por Comando)", textPt: "Usar o input de comando dos jogos originais dá mais poder do que o Tatsumaki Senpukyaku normal. Não pode ser usado repetidamente no ar." },
  { titleEn: "[★☆☆] Tatsumaki Senpukyaku's Power (Side Special / Command-Input Move)", titleJp: "竜巻旋風脚の威力 【横必殺・コマンド入力ワザ】", textJp: "右向き時、↓↙←とコマンド入力で出すと攻撃力が１.１６倍になる。強で出すと速度が上がり移動距離が伸びる。", titleJpEn: "Tatsumaki Senpukyaku's Power (Side Special / Command-Input Move)", textJpEn: "When facing right, inputting the command ↓↙← increases attack power by 1.16x. Using the strong version increases its speed and travel distance.", titlePt: "O Poder do Tatsumaki Senpukyaku (Especial Lateral / Golpe por Comando)", textPt: "Ao virar para a direita, inputar o comando ↓↙← aumenta o poder de ataque em 1,16x. Usar a versão forte aumenta sua velocidade e distância percorrida." },
  { titleEn: "[★☆☆] Shoryuken (Up Special / Command-Input Move)", titleJp: "昇龍拳 【上必殺・コマンド入力ワザ】", textJp: "コマンド入力時は、無敵時間が長くなり攻撃力もアップ。「昇龍拳！」のかけ声が長くなり、エフェクトも変化する。", titleJpEn: "Shoryuken (Up Special / Command-Input Move)", textJpEn: "Using the command input extends the invincibility window and boosts attack power. The shout \"Shoryuken!\" also becomes longer, and the effect changes.", titlePt: "Shoryuken (Especial Cima / Golpe por Comando)", textPt: "Usar o input de comando estende a janela de invencibilidade e aumenta o poder de ataque. O grito \"Shoryuken!\" também fica mais longo, e o efeito muda." },
  { titleEn: "[★☆☆] Shoryuken's Power (Up Special / Command-Input Move)", titleJp: "昇龍拳の威力 【上必殺・コマンド入力ワザ】", textJp: "右向き時、→↓↘と素早くコマンド入力すると攻撃力が１.２倍に上がる。チャンスには根本ヒットで撃墜を狙おう。", titleJpEn: "Shoryuken's Power (Up Special / Command-Input Move)", textJpEn: "When facing right, quickly inputting →↓↘ raises attack power by 1.2x. When the chance arises, aim for a KO with a hit at the base of the move.", titlePt: "O Poder do Shoryuken (Especial Cima / Golpe por Comando)", textPt: "Ao virar para a direita, inputar rapidamente →↓↘ aumenta o poder de ataque em 1,2x. Quando a chance surgir, mire um nocaute com um acerto na base do golpe." },
  { titleEn: "[★☆☆] Focus Attack (Down Special)", titleJp: "セービングアタック 【下必殺ワザ】", textJp: "このワザを出してから必殺ワザボタンを押している間は構えを継続し、ボタンを離すか一定時間経過で正拳突きを放つ。", titleJpEn: "Focus Attack (Down Special)", textJpEn: "After using this move, holding the special move button keeps the stance going, and releasing the button — or letting a set amount of time pass — unleashes the straight punch.", titlePt: "Focus Attack (Especial Baixo)", textPt: "Depois de usar este golpe, segurar o botão de golpe especial mantém a postura, e soltar o botão — ou deixar um certo tempo passar — libera o soco reto." },
  { titleEn: "[★★☆] Looking Back then Focus Attack (Down Special)", titleJp: "振り向いてセービングアタック 【下必殺ワザ】", textJp: "正拳突きを出す瞬間に向いている方向とは反対の方向に入力すると、背中側へ振り向いてワザを出すことができる。", titleJpEn: "Turning Around for Focus Attack (Down Special)", textJpEn: "Inputting the direction opposite to the one he's facing at the moment the punch comes out lets him turn around and strike behind himself instead.", titlePt: "Virando-se para o Focus Attack (Especial Baixo)", textPt: "Inputar a direção oposta àquela para a qual ele está virado no momento em que o soco sai permite que ele se vire e ataque para trás em vez disso." },
  { titleEn: "[★★☆] Focus Attack Follow-ups (Down Special)", titleJp: "セービングアタック後の追撃 【下必殺ワザ】", textJp: "最大までためた正拳突きは、地上の相手にヒットするとゆっくりと崩れ落ちるようにダウンする。倒れている間は追撃できる。", titleJpEn: "Focus Attack Follow-ups (Down Special)", textJpEn: "The straight punch, when fully charged, causes a grounded opponent to slowly crumple and go down on hit. A follow-up attack is possible while they're down.", titlePt: "Acompanhamentos do Focus Attack (Especial Baixo)", textPt: "O soco reto, quando totalmente carregado, faz um adversário no chão desabar lentamente ao ser atingido. Um golpe de acompanhamento é possível enquanto ele está caído." },
  { titleEn: "[★★☆] Canceling Focus Attack (Down Special)", titleJp: "セービングアタックのキャンセル 【下必殺ワザ】", textJp: "構えている間か正拳突きがヒットした直後、左右の同じ方向を素早く２回入力することで行動をキャンセルして移動できる。", titleJpEn: "Canceling Focus Attack (Down Special)", textJpEn: "While holding the stance, or right after the straight punch connects, quickly inputting the same left or right direction twice cancels the action and allows movement.", titlePt: "Cancelando o Focus Attack (Especial Baixo)", textPt: "Enquanto mantém a postura, ou logo depois que o soco reto acerta, inputar rapidamente a mesma direção (esquerda ou direita) duas vezes cancela a ação e permite se mover." },
  { titleEn: "[★★☆] Defend with Focus Attack (Down Special)", titleJp: "セービングアタックで防御 【下必殺ワザ】", textJp: "構えている間は１発だけ攻撃を受け止めることができる。最大までためると正拳突きが出る直前まで耐えられる。", titleJpEn: "Defending with Focus Attack (Down Special)", textJpEn: "While holding the stance, he can withstand one attack. Charging it to maximum lets him endure right up until the moment the straight punch comes out.", titlePt: "Defendendo com o Focus Attack (Especial Baixo)", textPt: "Enquanto mantém a postura, ele pode aguentar um ataque. Carregá-lo ao máximo permite resistir até o exato momento em que o soco reto sai." },
  { titleEn: "[★☆☆] Shin Shoryuken (Final Smash)", titleJp: "真・昇龍拳 【最後の切りふだ】", textJp: "相手が近くにいれば「真・昇龍拳」になる。真空波動拳より与えるダメージは大きく、撃墜が決まると背景がド派手な専用演出に。", titleJpEn: "Shin Shoryuken (Final Smash)", textJpEn: "If an opponent is nearby, it becomes \"Shin Shoryuken.\" It deals more damage than Shinku Hadoken, and landing a KO triggers a flashy dedicated background effect.", titlePt: "Shin Shoryuken (Final Smash)", textPt: "Se um adversário estiver por perto, ele se torna \"Shin Shoryuken\". Causa mais dano que o Shinku Hadoken, e conseguir um nocaute aciona um efeito de fundo exclusivo e chamativo." },
  { titleEn: "[★☆☆] Shinku Hadoken (Final Smash)", titleJp: "真空波動拳 【最後の切りふだ】", textJp: "相手が離れていれば「真空波動拳」になる。地形を貫通して直進するので、多くの相手を巻き込みやすい。", titleJpEn: "Shinku Hadoken (Final Smash)", textJpEn: "If an opponent is far away, it becomes \"Shinku Hadoken.\" Since it pierces through terrain and travels straight, it's easy to catch multiple opponents in it.", titlePt: "Shinku Hadoken (Final Smash)", textPt: "Se um adversário estiver longe, ele se torna \"Shinku Hadoken\". Como atravessa o terreno e viaja em linha reta, é fácil pegar múltiplos adversários com ele." },
  { titleEn: "[★★★] Final Smash between Attacks", titleJp: "キャンセル可能な最後の切りふだ", textJp: "リュウの最後の切りふだは、あらゆる攻撃をキャンセルして出せる。コンボのシメに使えば、効果絶大。", titleJpEn: "A Cancelable Final Smash", textJpEn: "Ryu's Final Smash can be unleashed by canceling almost any attack. Using it to finish off a combo is devastatingly effective.", titlePt: "Um Final Smash Cancelável", textPt: "O Final Smash do Ryu pode ser liberado cancelando quase qualquer ataque. Usá-lo para finalizar um combo é devastadoramente eficaz." },
  { titleEn: "[★☆☆] Collarbone Breaker (Side Tilt Attack - Heavy)", titleJp: "鎖骨割り 【横強攻撃(強)】", textJp: "２段ヒットする「鎖骨割り」。ガードした相手のシールドを大きく削ることができるのでプレッシャーをかけられる。", titleJpEn: "Collarbone Breaker (Side Tilt Attack - Heavy)", textJpEn: "The two-hit \"Collarbone Breaker.\" It can chip away a large chunk of a guarding opponent's shield, putting pressure on them.", titlePt: "Collarbone Breaker (Ataque Lateral Forte)", textPt: "O \"Collarbone Breaker\", que acerta duas vezes. Pode desgastar uma grande parte do escudo de um adversário se defendendo, colocando pressão nele." },
  { titleEn: "[★☆☆] Light Ankle Kick (Down Tilt Attack - Light)", titleJp: "くるぶしキック弱 【下強攻撃(弱)】", textJp: "しゃがみながら攻撃ボタンを短く入力すると出せる。ダウン中の相手にヒットさせると起き上がらせることが可能。", titleJpEn: "Light Ankle Kick (Down Tilt Attack - Light)", textJpEn: "Used by crouching and tapping the attack button briefly. Hitting a downed opponent with it can make them get back up.", titlePt: "Light Ankle Kick (Ataque Baixo Fraco)", textPt: "Usado ao agachar e tocar o botão de ataque brevemente. Acertar um adversário caído com ele pode fazê-lo se levantar." },
  { titleEn: "[★☆☆] Heavy Ankle Kick (Down Tilt Attack - Heavy)", titleJp: "くるぶしキック強 【下強攻撃(強)】", textJp: "原作におけるしゃがみ中キック。『スマブラ』でも必殺ワザによるキャンセルが可能なので攻守にわたり重要な攻撃。", titleJpEn: "Heavy Ankle Kick (Down Tilt Attack - Heavy)", textJpEn: "The crouching kick from the original games. In \"Super Smash Bros.\" too, it can be canceled into a special move, making it an important attack both offensively and defensively.", titlePt: "Heavy Ankle Kick (Ataque Baixo Forte)", textPt: "O chute agachado dos jogos originais. Também em \"Super Smash Bros.\", ele pode ser cancelado em um golpe especial, tornando-o um ataque importante tanto na ofensiva quanto na defensiva." },
  { titleEn: "[★☆☆] Canceling Heavy Ankle Kick (Down Tilt Attack - Heavy)", titleJp: "くるぶしキック強キャンセル 【下強攻撃(強)】", textJp: "しゃがみながら攻撃ボタンを長く入力すると出せる。ガードされても必殺ワザでキャンセルできるが空振りではできない。", titleJpEn: "Canceling Heavy Ankle Kick (Down Tilt Attack - Heavy)", textJpEn: "Used by crouching and holding the attack button longer. It can be canceled into a special move even if guarded, but not if it whiffs.", titlePt: "Cancelando o Heavy Ankle Kick (Ataque Baixo Forte)", textPt: "Usado ao agachar e segurar o botão de ataque por mais tempo. Pode ser cancelado em um golpe especial mesmo se bloqueado, mas não se errar o golpe." },
  { titleEn: "[★☆☆] Joudan Sokutogeri (Side Smash Attack)", titleJp: "上段足刀蹴り 【横スマッシュ攻撃】", textJp: "大きく前に進みながらの「上段足刀蹴り」。一番攻撃力が高い足の先端部分は、小さい相手がしゃがんでいると当たらない。", titleJpEn: "Joudan Sokutogeri (Side Smash Attack)", textJpEn: "The \"Joudan Sokutogeri,\" delivered while stepping far forward. The strongest part of the attack, the tip of the foot, won't connect if a small opponent is crouching.", titlePt: "Joudan Sokutogeri (Ataque Smash Lateral)", textPt: "O \"Joudan Sokutogeri\", desferido enquanto avança bastante para frente. A parte mais forte do ataque, a ponta do pé, não acerta se um adversário pequeno estiver agachado." },
  { titleEn: "[★☆☆] Tobigeri (Forward Air Attack)", titleJp: "飛び蹴り 【前空中攻撃】", textJp: "足の先端がヒットするとふっとばし力が高く、根元部分はシールドを多く削れて、ヒット時はコンボへ繋げやすい。", titleJpEn: "Tobigeri (Forward Air Attack)", textJpEn: "Hitting with the tip of the foot has high knockback power, while the base of the leg chips away more shield and, on hit, easily leads into combos.", titlePt: "Tobigeri (Ataque Aéreo Frente)", textPt: "Acertar com a ponta do pé tem alto poder de arremesso, enquanto a base da perna desgasta mais o escudo e, ao acertar, emenda facilmente em combos." },
  { titleEn: "[★☆☆] Sukui Tsuki (Up Air Attack)", titleJp: "すくい突き 【上空中攻撃】", textJp: "空中で２段ヒットするアッパー。見た目よりも大きなヒット判定があり、真上にいる相手を追撃しやすい。", titleJpEn: "Sukui Tsuki (Up Air Attack)", textJpEn: "An uppercut that hits twice in the air. It has a larger hitbox than it looks, making it easy to follow up on an opponent directly above.", titlePt: "Sukui Tsuki (Ataque Aéreo Cima)", textPt: "Um uppercut que acerta duas vezes no ar. Tem uma hitbox maior do que aparenta, tornando fácil emendar em um adversário diretamente acima." },
  { titleEn: "[★☆☆] Straight Punch (Down Air Attack)", titleJp: "ストレート 【下空中攻撃】", textJp: "リュウの攻撃で唯一メテオ効果がある。うまくヒットすれば相手を勢いよくななめ下にふっとばせるので積極的に狙おう。", titleJpEn: "Straight Punch (Down Air Attack)", textJpEn: "The only one of Ryu's attacks with a meteor effect. Landing it well launches the opponent forcefully at a diagonal downward angle, so go for it actively.", titlePt: "Straight Punch (Ataque Aéreo Baixo)", textPt: "O único ataque do Ryu com efeito meteoro. Acertá-lo bem lança o adversário com força na diagonal para baixo, então busque-o ativamente." },
  { titleEn: "[★★☆] Air Attack Cancel", titleJp: "キャンセルできる空中攻撃", textJp: "空中攻撃も一部のワザと同じく、当てた時は必殺ワザでキャンセルできる。つかみ→上投げ→上空中攻撃→昇龍拳など、組み合わせで強力なコンボも可能となる。", titleJpEn: "Cancelable Air Attacks", textJpEn: "Like some other moves, air attacks can be canceled into a special move when they connect. Combinations like Grab → Up Throw → Up Air Attack → Shoryuken make powerful combos possible.", titlePt: "Ataques Aéreos Canceláveis", textPt: "Assim como alguns outros golpes, os ataques aéreos podem ser cancelados em um golpe especial quando acertam. Combinações como Agarrão → Arremesso Cima → Ataque Aéreo Cima → Shoryuken tornam combos poderosos possíveis." },
  { titleEn: "[★☆☆] Heel Drop (Up Throw)", titleJp: "かかと落とし 【上投げ】", textJp: "つかんだ相手を真上に蹴り上げる投げワザ。投げた後に振り下ろす足は周囲のライバルにヒットする。", titleJpEn: "Heel Drop (Up Throw)", textJpEn: "A throw that kicks a grabbed opponent straight upward. The leg he swings down afterward can hit any nearby rivals.", titlePt: "Heel Drop (Arremesso Cima)", textPt: "Um arremesso que chuta um adversário agarrado diretamente para cima. A perna que ele balança para baixo em seguida pode acertar rivais próximos." },
];

async function main() {
  const ryu = await db.fighter.findFirst({
    where: { name: "Ryu" },
    select: {
      id: true,
      bios: { select: { id: true, smashGameVersion: true } },
      moves: { select: { id: true, smashGameVersion: true, order: true } },
      tips: { select: { id: true, titleEn: true } },
    },
  });
  if (!ryu) { console.log("Ryu not found"); return; }

  await db.fighter.update({
    where: { id: ryu.id },
    data: {
      curatorOverviewEn: "Ryu brings a full fighting-game moveset into Smash, and the two things that define him are command inputs and stance-switching. Every special move has a hidden, more powerful version triggered by inputting the classic Street Fighter motion instead of just the button, rewarding players willing to learn fighting-game inputs for real payoff — a fully-commanded Shoryuken hits harder and grants far more invincibility than the simplified version. Focus Attack lets him tank a single hit while charging a devastating counter-punch, and his Final Smash automatically becomes Shin Shoryuken or Shinku Hadoken depending on the opponent's distance, and can be canceled out of nearly any attack for a devastating combo finisher. Uniquely, Ryu and Ken always face their opponent regardless of which way they're walking, changing how spacing and positioning work compared to every other fighter in the game.",
      curatorOverviewPt: "Ryu traz um moveset completo de jogo de luta para o Smash, e as duas coisas que o definem são inputs de comando e a troca de posturas. Todo golpe especial tem uma versão oculta e mais poderosa, ativada ao inputar o movimento clássico de Street Fighter em vez de só o botão, recompensando jogadores dispostos a aprender inputs de jogos de luta com um retorno real — um Shoryuken totalmente comandado acerta mais forte e concede muito mais invencibilidade do que a versão simplificada. Focus Attack permite que ele aguente um golpe enquanto carrega um soco de contra-ataque devastador, e seu Final Smash se torna automaticamente Shin Shoryuken ou Shinku Hadoken dependendo da distância do adversário, podendo ser cancelado a partir de quase qualquer ataque para um finalizador de combo devastador. De forma única, Ryu e Ken sempre encaram o adversário independentemente da direção para a qual estão andando, mudando como o posicionamento funciona em comparação com todos os outros lutadores do jogo.",
      curatorOverviewJp: "リュウは格闘ゲームそのもののムーブセットをスマブラに持ち込んでおり、彼を特徴づける２つの要素は、コマンド入力と構えの切り替えだ。すべての必殺ワザには、ボタンだけでなく『ストリートファイター』譲りのクラシックなコマンド入力によって発動する、より強力な隠しバージョンが存在し、格闘ゲームの入力を学ぶ意欲があるプレイヤーに実際の見返りを与える――完全にコマンド入力された昇龍拳は、簡易版よりも強く当たり、はるかに長い無敵時間を得る。「セービングアタック」は、強烈なカウンターパンチをためている間、一発だけ攻撃に耐えることを可能にし、最後の切りふだは相手との距離に応じて自動的に「真・昇龍拳」または「真空波動拳」に変化し、ほぼあらゆる攻撃をキャンセルして繰り出せるため、コンボの決定的な締めとなる。ユニークな点として、リュウとケンは歩いている方向に関係なく常に相手の方を向いており、間合いと位置取りの扱いが、ゲーム内の他のどのファイターとも異なっている。",
      curatorOverviewJpEn: "Ryu brings a full fighting-game moveset into Smash, and the two elements that define him are command inputs and stance-switching. Every special move has a more powerful hidden version, triggered not just by the button but by a classic command input inherited from \"Street Fighter,\" rewarding players willing to learn fighting-game inputs with a real payoff — a fully command-input Shoryuken hits harder and gains far longer invincibility than the simplified version. Focus Attack lets him withstand a single hit while charging a devastating counter-punch, and his Final Smash automatically transforms into Shin Shoryuken or Shinku Hadoken depending on distance from the opponent, and can be unleashed by canceling almost any attack, making it a decisive combo finisher. Uniquely, Ryu and Ken always face their opponent regardless of the direction they're walking, changing how spacing and positioning work compared to every other fighter in the game.",
    },
  });
  console.log("✅ Curator Overview (4 langs)");

  for (const [version, data] of Object.entries(BIO_PT_JPEN)) {
    const bio = ryu.bios.find(b => b.smashGameVersion === version);
    if (!bio) continue;
    await db.fighterBio.update({ where: { id: bio.id }, data: { contentPt: data.pt, contentJpEn: data.jpEn } });
    console.log(`✅ Bio [${version}]: PT+JpEn adicionados`);
  }

  const move = ryu.moves.find(m => m.smashGameVersion === "SSB4" && m.order === 0);
  if (move) {
    const en = "The Down Special \"Focus Attack\" lets Ryu hold his stance while pressing the special move button — he still takes damage, but can endure one hit while doing so. The longer he holds the stance, the longer the follow-up window becomes when the straight punch connects. Hitting a grounded opponent makes them slowly crumple, completely defenseless. Cancel the stance to follow up quickly. (AC) Street Fighter (1987/08)";
    await db.fighterMove.update({
      where: { id: move.id },
      data: {
        descEn: en, descJpEn: en,
        descPt: "O especial baixo \"Focus Attack\" permite que o Ryu mantenha sua postura enquanto pressiona o botão de golpe especial — ele ainda recebe dano, mas pode suportar um golpe enquanto faz isso. Quanto mais tempo ele mantém a postura, maior a janela de acompanhamento quando o soco reto acerta. Atingir um adversário no chão o faz desabar lentamente, completamente indefeso. Cancele a postura para emendar rapidamente. (AC) Street Fighter (1987/08)",
      },
    });
    console.log("✅ Move [SSB4] EX: EN+PT+JpEn adicionados");
  }

  let updated = 0;
  for (const data of TIPS) {
    const tip = ryu.tips.find(t => t.titleEn === data.titleEn);
    if (!tip) { console.log(`  ⚠️  Tip não encontrada: "${data.titleEn}"`); continue; }
    await db.fighterTip.update({
      where: { id: tip.id },
      data: {
        titleJp: data.titleJp, textJp: data.textJp,
        titleJpEn: data.titleJpEn, textJpEn: data.textJpEn,
        titlePt: data.titlePt, textPt: data.textPt,
      },
    });
    updated++;
  }
  console.log(`✅ ${updated}/${TIPS.length} tips atualizadas`);

  // Video fix (usuário via VLC): WiiU 2:17:31-2:17:41 = 8251-8261 no troféu principal
  const main = await db.collectible.findFirst({ where: { name: "Ryu", type: "TROPHY", smashGameVersion: "SSB4" }, select: { id: true, videoStartSec: true, videoEndSec: true } });
  if (main) {
    await db.collectible.update({ where: { id: main.id }, data: { videoStartSec: 8251, videoEndSec: 8261 } });
    console.log(`✅ Trophy "Ryu" [SSB4]: vídeo WiiU corrigido 8251-8261 (era ${main.videoStartSec}-${main.videoEndSec})`);
  }

  await db.$disconnect();
}
main().catch(console.error);
