import { db } from "../../lib/db";

// Must match DB order exactly (orderBy id asc) — includes duplicate titleEn values
// ("Judge (Side Special)" x2, "Oil Panic (Down Special)" x2), so matched by index, not title.
const TIPS = [
  { titleJp: "Mr.ゲーム＆ウォッチの初登場作品", textJp: "Mr.ゲーム＆ウォッチの姿が初めて登場したのは１９８０年に発売された『ゲーム＆ウオッチ』。ファミコン以前に登場した任天堂ゲーム機のひとつ。", titleJpEn: "Mr. Game & Watch's Origins", textJpEn: "Mr. Game & Watch's appearance first debuted in \"Game & Watch,\" released in 1980. It was one of Nintendo's game consoles that appeared before the Famicom.", titlePt: "As Origens do Mr. Game & Watch", textPt: "A aparência do Mr. Game & Watch estreou em \"Game & Watch,\" lançado em 1980. Foi um dos consoles de jogos da Nintendo que surgiu antes do Famicom." },
  { titleJp: "原作では", textJp: "任天堂の携帯型液晶ゲームで、マリオよりも古いゲームキャラクターの１人。数あるゲーム＆ウオッチ作品で、さまざまな姿や役割を見せる。", titleJpEn: "In His Series", textJpEn: "A Nintendo handheld liquid-crystal game, he's one of the game characters older than Mario. Across the many \"Game & Watch\" titles, he shows a variety of appearances and roles.", titlePt: "Na Série Original", textPt: "Um jogo portátil de cristal líquido da Nintendo, ele é um dos personagens de videogame mais antigos que o Mario. Ao longo dos muitos títulos de \"Game & Watch,\" ele mostra uma variedade de aparências e papéis." },
  { titleJp: "すべてのワザ", textJp: "使用している各ワザの「シェフ」「ジャッジ」「ファイア」「オイルパニック」「オクトパス」は、すべて別々に発売されたゲーム＆ウオッチのシリーズ。", titleJpEn: "Move Names", textJpEn: "Each move he uses — \"Chef,\" \"Judge,\" \"Fire,\" \"Oil Panic,\" and \"Octopus\" — is named after a separately released title in the \"Game & Watch\" series.", titlePt: "Nomes dos Golpes", textPt: "Cada golpe que ele usa — \"Chef,\" \"Judge,\" \"Fire,\" \"Oil Panic\" e \"Octopus\" — tem o nome de um título lançado separadamente na série \"Game & Watch.\"" },
  { titleJp: "シェフ 【通常必殺ワザ】", textJp: "フライパンから料理を飛ばして攻撃するワザ。料理は色々な方向に飛ぶので、身を守るのにも使える。", titleJpEn: "Chef (Neutral Special)", textJpEn: "A move that attacks by launching food from a frying pan. Since the food flies in various directions, it can also be used to protect himself.", titlePt: "Chef (Especial Neutro)", textPt: "Um golpe que ataca lançando comida de uma frigideira. Como a comida voa em várias direções, também pode ser usado para se proteger." },
  { titleJp: "シェフのテクニック 【通常必殺ワザ】", textJp: "ボタンを押す間隔で、料理を飛ばすタイミングを調整できる。また、ボタンを連打すると、料理を飛ばす時間間隔が短くなる。", titleJpEn: "Chef Techniques (Neutral Special)", textJpEn: "The interval between button presses adjusts the timing of when the food is launched. Also, mashing the button shortens the interval between launches.", titlePt: "Técnicas do Chef (Especial Neutro)", textPt: "O intervalo entre os apertos do botão ajusta o momento em que a comida é lançada. Além disso, apertar o botão repetidamente encurta o intervalo entre os lançamentos." },
  { titleJp: "ジャッジ 【横必殺ワザ】", textJp: "表示される数字によって、ワザの効果が大きく違う。１はハズレだけど、９なら相手を強烈にふっとばす！", titleJpEn: "Judge (Side Special)", textJpEn: "The move's effect varies greatly depending on the number displayed. A 1 is a dud, but a 9 sends the opponent flying with tremendous force!", titlePt: "Judge (Especial Lateral)", textPt: "O efeito do golpe varia bastante dependendo do número exibido. Um 1 é um fracasso, mas um 9 arremessa o adversário com força tremenda!" },
  { titleJp: "ジャッジ 【横必殺ワザ】", textJp: "「７」が出たときには、リンゴが３つ出現する。もちろん、食べれば体力が回復するが、油断していると相手に取られる。", titleJpEn: "Judge (Side Special)", textJpEn: "When a \"7\" comes up, three apples appear. Of course, eating them restores health, but if you're not careful, an opponent can take them instead.", titlePt: "Judge (Especial Lateral)", textPt: "Quando sai um \"7,\" três maçãs aparecem. Claro, comê-las restaura a vida, mas se você não tomar cuidado, um adversário pode pegá-las primeiro." },
  { titleJp: "ファイア 【上必殺ワザ】", textJp: "救急員が現れ、Mr.ゲーム＆ウォッチを高く放りあげる。ジャンプする時に近くの相手を少し押し出す。", titleJpEn: "Fire (Up Special)", textJpEn: "A rescue worker appears and launches Mr. Game & Watch high into the air. When he jumps, nearby opponents are pushed back slightly.", titlePt: "Fire (Especial Cima)", textPt: "Um socorrista aparece e lança o Mr. Game & Watch bem alto no ar. Quando ele salta, adversários próximos são empurrados levemente para trás." },
  { titleJp: "ファイアでふっとばし 【上必殺ワザ】", textJp: "上昇中に当たった相手を横にふっとばすことができる。うまく当てれば、ガケ下に追撃にきた相手を返り討ちにすることも可能。", titleJpEn: "Launching with Fire (Up Special)", textJpEn: "Opponents hit while he's rising can be launched sideways. Landing it well can let him turn the tables on an opponent who came to edge-guard him below the ledge.", titlePt: "Arremessando com o Fire (Especial Cima)", textPt: "Adversários atingidos enquanto ele sobe podem ser arremessados lateralmente. Acertar bem pode permitir virar o jogo contra um adversário que veio persegui-lo abaixo da borda." },
  { titleJp: "オイルパニック 【下必殺ワザ】", textJp: "相手の飛び道具を吸収してバケツにためる。バケツが満タンになったら、中身を浴びせて攻撃できる。", titleJpEn: "Oil Panic (Down Special)", textJpEn: "Absorbs the opponent's projectiles and stores them in a bucket. When the bucket is full, its contents can be unleashed as an attack.", titlePt: "Oil Panic (Especial Baixo)", textPt: "Absorve os projéteis do adversário e os armazena em um balde. Quando o balde está cheio, seu conteúdo pode ser liberado como um ataque." },
  { titleJp: "オイルパニックと飛び道具 【下必殺ワザ】", textJp: "エネルギー系の飛び道具だけ吸収することができる。リンクの矢などの、物理系飛び道具は反射する。", titleJpEn: "Oil Panic and Projectiles (Down Special)", textJpEn: "Only energy-based projectiles can be absorbed. Physical projectiles, like Link's arrows, are reflected instead.", titlePt: "Oil Panic e Projéteis (Especial Baixo)", textPt: "Somente projéteis de energia podem ser absorvidos. Projéteis físicos, como as flechas do Link, são refletidos." },
  { titleJp: "オイルパニックのゲージ 【下必殺ワザ】", textJp: "吸い込んだ攻撃が強いほど、ゲージが一気にたまる。逆に、いくら弱い攻撃でも１回吸い込めば１つはゲージがたまる。", titleJpEn: "Oil Panic's Gauge (Down Special)", textJpEn: "The stronger the attack absorbed, the more the gauge fills at once. Conversely, no matter how weak the attack, absorbing it even once still fills at least one segment of the gauge.", titlePt: "O Medidor do Oil Panic (Especial Baixo)", textPt: "Quanto mais forte o ataque absorvido, mais o medidor se enche de uma vez. Por outro lado, não importa quão fraco seja o ataque, absorvê-lo pelo menos uma vez ainda enche ao menos um segmento do medidor." },
  { titleJp: "オイルパニックと爆弾 【下必殺ワザ】", textJp: "リンクの爆弾やボムへいなどの爆風も吸収することができる。ただし、サドンデス中に降ってくるボムへいは吸収できない。", titleJpEn: "Oil Panic and Bombs (Down Special)", textJpEn: "Explosions from things like Link's Bombs or Bob-ombs can also be absorbed. However, Bob-ombs that fall during Sudden Death cannot be absorbed.", titlePt: "Oil Panic e Bombas (Especial Baixo)", textPt: "Explosões de coisas como as Bombas do Link ou Bob-ombs também podem ser absorvidas. Porém, Bob-ombs que caem durante a Morte Súbita não podem ser absorvidas." },
  { titleJp: "オイルパニックとミス 【下必殺ワザ】", textJp: "たまったゲージは、Mr.ゲーム＆ウォッチがミスしても無くならない。復活直後にオイルをまいて相手の意表をつくこともできる。", titleJpEn: "Oil Panic and Getting KO'd (Down Special)", textJpEn: "The accumulated gauge doesn't disappear even if Mr. Game & Watch is KO'd. He can also catch the opponent off guard by unleashing the oil right after respawning.", titlePt: "Oil Panic e Ser Nocauteado (Especial Baixo)", textPt: "O medidor acumulado não desaparece mesmo se o Mr. Game & Watch for nocauteado. Ele também pode pegar o adversário de surpresa liberando o óleo logo após reaparecer." },
  { titleJp: "とりあえずオイルパニック 【下必殺ワザ】", textJp: "吸収できない物理系の飛び道具やアイテムも、反射することができる。何かが飛んできたら、とりあえずこのワザを使ってみるのもアリだ。", titleJpEn: "Oil Panic (Down Special)", textJpEn: "Physical projectiles and items that can't be absorbed can still be reflected. If something's flying at you, it's not a bad idea to just try using this move.", titlePt: "Oil Panic (Especial Baixo)", textPt: "Projéteis físicos e itens que não podem ser absorvidos ainda podem ser refletidos. Se algo estiver voando em sua direção, não é uma má ideia simplesmente tentar usar esse golpe." },
  { titleJp: "オクトパス 【最後の切りふだ】", textJp: "最後の切りふだの大ダコの足は、相手をつかまえる。ボタン連打で脱出できなければ、ステージの外まで連れて行かれてしまう。", titleJpEn: "Octopus (Final Smash)", textJpEn: "The giant octopus's tentacle from the Final Smash grabs the opponent. If they can't escape by mashing the button, they'll be carried all the way off the stage.", titlePt: "Octopus (Final Smash)", textPt: "O tentáculo do polvo gigante do Final Smash agarra o adversário. Se ele não conseguir escapar apertando o botão repetidamente, será carregado para fora do palco." },
  { titleJp: "オクトパスと障害物 【最後の切りふだ】", textJp: "大ダコの足でつかまれた相手を、画面の外へ連れていく。相手に脱出されそうな時は、わざと床やカベに当てて弾き飛ばすのも有効。", titleJpEn: "Octopus and Obstacles (Final Smash)", textJpEn: "The opponent grabbed by the giant octopus's tentacle is carried off-screen. If they seem about to escape, deliberately hitting them against the floor or a wall to knock them away is also effective.", titlePt: "Octopus e Obstáculos (Final Smash)", textPt: "O adversário agarrado pelo tentáculo do polvo gigante é levado para fora da tela. Se ele parecer prestes a escapar, acertá-lo propositalmente contra o chão ou uma parede para arremessá-lo também é eficaz." },
  { titleJp: "オクトパスの足 【最後の切りふだ】", textJp: "大ダコの足は、必殺ワザボタンを押せば伸ばすことができる。何もしなくても伸び縮みするが、ボタンを押したほうが早く動かせる。", titleJpEn: "Octopus Tentacles (Final Smash)", textJpEn: "The giant octopus's tentacle can be extended by pressing the special move button. It extends and retracts on its own even without input, but pressing the button moves it faster.", titlePt: "Tentáculos do Octopus (Final Smash)", textPt: "O tentáculo do polvo gigante pode ser esticado apertando o botão de golpe especial. Ele se estica e se retrai sozinho mesmo sem input, mas apertar o botão o move mais rápido." },
  { titleJp: "スピットボールスパーキー 【上空中攻撃】", textJp: "真上に気流を噴射して、相手を押し上げるワザ。高い位置で相手に当てることができれば、撃墜を狙える。", titleJpEn: "Spitball Sparky (Up Air Attack)", textJpEn: "A move that blasts an airstream straight up, pushing the opponent upward. Landing it on an opponent at a high position can set up for a KO.", titlePt: "Spitball Sparky (Ataque Aéreo Cima)", textPt: "Um golpe que dispara uma corrente de ar diretamente para cima, empurrando o adversário para cima. Acertá-lo em um adversário em uma posição alta pode preparar um KO." },
];

async function main() {
  const gnw = await db.fighter.findFirst({
    where: { name: "Mr. Game & Watch" },
    select: { tips: { select: { id: true, titleEn: true }, orderBy: { id: "asc" } } },
  });
  if (!gnw) { console.log("Mr. Game & Watch not found"); return; }
  if (gnw.tips.length !== TIPS.length) {
    console.log(`⚠️  Mismatch: DB has ${gnw.tips.length} tips, TIPS array has ${TIPS.length}`);
    return;
  }
  for (let i = 0; i < gnw.tips.length; i++) {
    const tip = gnw.tips[i];
    const data = TIPS[i];
    await db.fighterTip.update({
      where: { id: tip.id },
      data: {
        titleJp: data.titleJp, textJp: data.textJp,
        titleJpEn: data.titleJpEn, textJpEn: data.textJpEn,
        titlePt: data.titlePt, textPt: data.textPt,
      },
    });
    console.log(`✅ [${i}] "${tip.titleEn}" -> "${data.titleJpEn}"`);
  }
  console.log(`\n✅ ${gnw.tips.length}/${TIPS.length} tips atualizadas`);
  await db.$disconnect();
}
main().catch(console.error);
