import { db } from "../../lib/db";

const TIPS = [
  {
    titleEn: "[★☆☆] Kazuya's Origin",
    titleJp: "カズヤの初登場作品",
    textJp: "カズヤの初登場作品は、１９９４年稼働のアーケードゲーム『鉄拳』。当時はまだ少なかった、３Dポリゴンで表示された格闘ゲーム。ユニークなキャラクターも特徴だった。",
    titleJpEn: "Kazuya's Debut Work",
    textJpEn: "Kazuya's first appearance was in the 1994 arcade game Tekken. It was a fighting game displayed in 3D polygons, still rare at the time, and was also known for its unique characters.",
    titlePt: "As Origens de Kazuya",
    textPt: "A primeira aparição de Kazuya foi no jogo de arcade de 1994, Tekken. Era um jogo de luta exibido em polígonos 3D, algo ainda raro na época, e também era conhecido por seus personagens únicos.",
  },
  {
    titleEn: "[★☆☆] In His Series",
    titleJp: "原作では",
    textJp: "『鉄拳』のメインキャラクターの１人で、冷血な性格。シリーズを通して父の三島平八や息子の風間仁と熾烈な戦いを繰り広げてきた。体内のデビル因子によってデビル化する能力を持つ。",
    titleJpEn: "In the Original Game",
    textJpEn: "One of the main characters of Tekken, with a cold-blooded personality. Throughout the series, he has waged fierce battles against his father, Heihachi Mishima, and his son, Jin Kazama. He has the ability to transform into a devil through the Devil Gene within his body.",
    titlePt: "No Jogo Original",
    textPt: "Um dos personagens principais de Tekken, com uma personalidade fria e implacável. Ao longo da série, ele travou batalhas ferozes contra seu pai, Heihachi Mishima, e seu filho, Jin Kazama. Ele tem a habilidade de se transformar em um demônio através do Devil Gene dentro de seu corpo.",
  },
  {
    titleEn: "[★☆☆] Devil Blaster (Neutral Special)",
    titleJp: "デビルブラスター 【通常必殺ワザ】",
    textJp: "地上ではまっすぐ、空中では斜め下に、高威力のビームを放つ。長射程なうえ、ファイターを貫通して３人まで当てられる。当てる度に威力は落ちる。",
    titleJpEn: "Devil Blaster (Neutral Special)",
    textJpEn: "Fires a high-powered beam straight ahead on the ground, or diagonally downward in midair. It has long range and can pierce through fighters, hitting up to 3 opponents. Its power drops each time it hits someone.",
    titlePt: "Devil Blaster (Especial Neutro)",
    textPt: "Dispara um feixe de alto poder reto à frente no chão, ou na diagonal para baixo no ar. Tem longo alcance e pode perfurar lutadores, atingindo até 3 oponentes. Seu poder cai a cada vez que atinge alguém.",
  },
  {
    titleEn: "[★☆☆] Aiming the Devil Blaster (Neutral Special)",
    titleJp: "デビルブラスターの出し分け 【通常必殺ワザ】",
    textJp: "ビームを放つ直前にスティック上下入力で、上下に出し分けられる。斜め下に出すと背の低い相手にも当てられるが、やや威力が落ちる。",
    titleJpEn: "Aiming the Devil Blaster (Neutral Special)",
    textJpEn: "Inputting up or down on the stick right before firing the beam lets Kazuya angle it up or down. Firing it diagonally downward can hit shorter opponents, but slightly reduces its power.",
    titlePt: "Mirando o Devil Blaster (Especial Neutro)",
    textPt: "Inserir para cima ou para baixo no direcional pouco antes de disparar o feixe permite que Kazuya o direcione para cima ou para baixo. Disparar na diagonal para baixo pode acertar oponentes mais baixos, mas reduz um pouco o poder.",
  },
  {
    titleEn: "[★☆☆] Devil Fist (Side Special)",
    titleJp: "デビルフィスト 【横必殺ワザ】",
    textJp: "突進しながらくり出した拳が相手に当たると、そのまま相手の背後まで突き抜ける。ワザの出始めを当てると相手がダウンし、さらなる追撃を狙える。",
    titleJpEn: "Devil Fist (Side Special)",
    textJpEn: "If the fist thrown while charging forward hits an opponent, it punches straight through to behind them. Landing it right at the start knocks the opponent down, allowing for a further follow-up.",
    titlePt: "Devil Fist (Especial Lateral)",
    textPt: "Se o punho lançado durante o avanço atingir um oponente, ele atravessa direto até atrás dele. Acertá-lo bem no início derruba o oponente, permitindo um golpe de acompanhamento adicional.",
  },
  {
    titleEn: "[★☆☆] Devil Fist in the Air (Side Special)",
    titleJp: "空中でのデビルフィスト 【横必殺ワザ】",
    textJp: "空中で出した時は、地上より突進の距離が短くなる。また、地上で出すとガケ際で止まるが、空中では止まらない。自滅に要注意。",
    titleJpEn: "Devil Fist in the Air (Side Special)",
    textJpEn: "When used in midair, the charging distance is shorter than on the ground. Also, while it stops at the edge of a ledge when used on the ground, it doesn't stop in midair. Be very careful of self-destructing.",
    titlePt: "Devil Fist no Ar (Especial Lateral)",
    textPt: "Quando usado no ar, a distância do avanço é menor do que no chão. Além disso, enquanto ele para na borda quando usado no chão, ele não para no ar. Muito cuidado para não se autodestruir.",
  },
  {
    titleEn: "[★☆☆] Devil Fist Invincibility and Vulnerability (Side Special)",
    titleJp: "デビルフィストの無敵とスキ 【横必殺ワザ】",
    textJp: "地上では、ワザの出始めに一瞬だけ無敵になる。一方ワザ後のスキは大きいので、確実に当てられる時を狙おう。",
    titleJpEn: "Devil Fist Invincibility and Vulnerability (Side Special)",
    textJpEn: "On the ground, Kazuya is briefly invincible at the very start of the move. However, the opening after the move is large, so aim for moments when it's certain to connect.",
    titlePt: "Invencibilidade e Vulnerabilidade do Devil Fist (Especial Lateral)",
    textPt: "No chão, Kazuya fica brevemente invencível bem no início do golpe. Porém, a brecha depois do golpe é grande, então mire em momentos em que ele certamente vai acertar.",
  },
  {
    titleEn: "[★☆☆] Devil Wings (Up Special)",
    titleJp: "デビルウィング 【上必殺ワザ】",
    textJp: "上昇中にスティック左右入力で、少し左右に移動できる。また、上昇中は翼の爪で相手を攻撃できる。",
    titleJpEn: "Devil Wings (Up Special)",
    textJpEn: "Inputting left or right on the stick while ascending allows for a small amount of horizontal movement. Also, while ascending, Kazuya can attack opponents with his wing claws.",
    titlePt: "Devil Wings (Especial Superior)",
    textPt: "Inserir para a esquerda ou direita no direcional durante a subida permite um pequeno deslocamento horizontal. Além disso, durante a subida, Kazuya pode atacar oponentes com as garras das asas.",
  },
  {
    titleEn: "[★☆☆] After Using Devil Wings (Up Special)",
    titleJp: "デビルウィング後の制限 【上必殺ワザ】",
    textJp: "ワザを出した後でも、少し経てば他のワザを出すことができる。ただし、横必殺ワザは着地まで出すことができない。",
    titleJpEn: "After Using Devil Wings (Up Special)",
    textJpEn: "Even after using this move, Kazuya can use other moves after a short while. However, the side special can't be used until he lands.",
    titlePt: "Depois de Usar o Devil Wings (Especial Superior)",
    textPt: "Mesmo depois de usar esse golpe, Kazuya pode usar outros golpes depois de um curto tempo. Porém, o especial lateral não pode ser usado até ele aterrissar.",
  },
  {
    titleEn: "[★☆☆] Heaven's Door (Down Special)",
    titleJp: "ヘブンズドア 【下必殺ワザ】",
    textJp: "目の前の相手をつかんで地面に叩きつけ、大ダメージを与える。相手のシールドを無視できるが、空振りすると大きなスキが生じる。",
    titleJpEn: "Heaven's Door (Down Special)",
    textJpEn: "Grabs the opponent right in front and slams them into the ground, dealing massive damage. It ignores the opponent's shield, but whiffing it creates a large opening.",
    titlePt: "Heaven's Door (Especial Inferior)",
    textPt: "Agarra o oponente bem à frente e o joga contra o chão, causando dano massivo. Ele ignora o escudo do oponente, mas errar o golpe cria uma grande brecha.",
  },
  {
    titleEn: "[★☆☆] Heaven's Door's Super Armor (Down Special)",
    titleJp: "ヘブンズドアのスーパーアーマー 【下必殺ワザ】",
    textJp: "ワザの出始めにスーパーアーマー効果がある。相手の攻撃に重ねて強引にくり出すことも可能だが、ワザの出が遅い点は要注意。",
    titleJpEn: "Heaven's Door's Super Armor (Down Special)",
    textJpEn: "This move has a Super Armor effect at the very start. It's possible to force it out through an opponent's attack, but be careful — the move is slow to come out.",
    titlePt: "Super Armadura do Heaven's Door (Especial Inferior)",
    textPt: "Esse golpe tem efeito de Super Armadura bem no início. É possível forçá-lo através do ataque de um oponente, mas cuidado — o golpe demora para sair.",
  },
  {
    titleEn: "[★☆☆] Accumulated Damage and Heaven's Door (Down Special)",
    titleJp: "ヘブンズドアと蓄積ダメージ 【下必殺ワザ】",
    textJp: "空中で相手をつかんでいる間の左右入力は、相手と押し合う状態になる。蓄積ダメージが少ないほうの入力が、より大きく影響する。",
    titleJpEn: "Accumulated Damage and Heaven's Door (Down Special)",
    textJpEn: "While holding an opponent in midair, inputting left or right becomes a tug-of-war between the two. The input of whoever has less accumulated damage has a greater effect.",
    titlePt: "Dano Acumulado e o Heaven's Door (Especial Inferior)",
    textPt: "Enquanto segura um oponente no ar, inserir para a esquerda ou direita se torna um cabo de guerra entre os dois. O input de quem tem menos dano acumulado tem um efeito maior.",
  },
  {
    titleEn: "[★☆☆] Enemies Near Heaven's Door (Down Special)",
    titleJp: "ヘブンズドアで巻き込み 【下必殺ワザ】",
    textJp: "相手を地面に叩きつけた時、周囲に他のファイターがいると、巻き込んで一緒にふっとばせる。",
    titleJpEn: "Enemies Near Heaven's Door (Down Special)",
    textJpEn: "When slamming an opponent into the ground, if other fighters are nearby, they can be caught up and launched along with them.",
    titlePt: "Inimigos Perto do Heaven's Door (Especial Inferior)",
    textPt: "Ao jogar um oponente contra o chão, se houver outros lutadores por perto, eles podem ser pegos e lançados junto.",
  },
  {
    titleEn: "[★☆☆] Final Blaster (Final Smash)",
    titleJp: "ファイナルブラスター 【最後の切りふだ】",
    textJp: "額から長射程のビームを放ち、相手に当たると、翼と胸からビームを斉射する。前方の広範囲に斉射するため、多くの相手を巻き込みやすい。",
    titleJpEn: "Final Blaster (Final Smash)",
    textJpEn: "Fires a long-range beam from his forehead, and if it hits an opponent, follows up with a barrage of beams from his wings and chest. Since the barrage covers a wide area in front, it's easy to catch many opponents.",
    titlePt: "Final Blaster (Ataque Final)",
    textPt: "Dispara um feixe de longo alcance da testa, e se atingir um oponente, segue com uma rajada de feixes das asas e do peito. Como a rajada cobre uma ampla área à frente, é fácil pegar muitos oponentes.",
  },
  {
    titleEn: "[★☆☆] Rage",
    titleJp: "レイジ",
    textJp: "蓄積ダメージが１００％を超えるか、体力制で残り体力が約１／４を切ると、レイジ状態になって攻撃力が上昇する。",
    titleJpEn: "Rage",
    textJpEn: "When accumulated damage exceeds 100%, or in Stamina mode when remaining stamina drops below about a quarter, Kazuya enters a Rage state, increasing his attack power.",
    titlePt: "Rage",
    textPt: "Quando o dano acumulado ultrapassa 100%, ou no Modo Resistência quando a resistência restante cai abaixo de cerca de um quarto, Kazuya entra em estado de Rage, aumentando seu poder de ataque.",
  },
  {
    titleEn: "[★☆☆] The Signs of Rage",
    titleJp: "レイジ状態の印",
    textJp: "レイジ状態の時は、赤いオーラをまとう。また、蓄積ダメージ近くのファイターの名前が、赤く点滅する。",
    titleJpEn: "The Signs of Rage",
    textJpEn: "While in the Rage state, Kazuya is wrapped in a red aura. Additionally, his fighter name near his damage percentage blinks red.",
    titlePt: "Os Sinais do Rage",
    textPt: "Enquanto está em estado de Rage, Kazuya fica envolto numa aura vermelha. Além disso, o nome dele perto da porcentagem de dano pisca em vermelho.",
  },
  {
    titleEn: "[★☆☆] Rage Drive",
    titleJp: "レイジドライブ",
    textJp: "レイジ状態で地上にいる時、→↓↘＋ボタン長押し、下必殺ワザ、つかみのどれかで発動する。→↓↘＋ボタン長押しで出すと、最も高威力。",
    titleJpEn: "Rage Drive",
    textJpEn: "While on the ground in the Rage state, this can be activated with →↓↘ + held button, the down special, or a grab. Using →↓↘ + held button deals the highest damage.",
    titlePt: "Rage Drive",
    textPt: "Enquanto está no chão em estado de Rage, isso pode ser ativado com →↓↘ + botão segurado, o especial inferior, ou um agarrão. Usar →↓↘ + botão segurado causa o maior dano.",
  },
  {
    titleEn: "[★☆☆] Features of Rage Drive",
    titleJp: "レイジドライブの特徴",
    textJp: "高威力でスキが少なく、さらに相手のシールドを無視して攻撃できる。ただし、空振りするとレイジ状態の解除が早まる。使いどころを見極めよう。",
    titleJpEn: "Features of Rage Drive",
    textJpEn: "It deals high damage with little opening, and can also attack ignoring the opponent's shield. However, whiffing it speeds up the end of the Rage state, so choose carefully when to use it.",
    titlePt: "Características do Rage Drive",
    textPt: "Causa alto dano com pouca brecha, e também pode atacar ignorando o escudo do oponente. Porém, errar o golpe acelera o fim do estado de Rage, então escolha bem quando usá-lo.",
  },
  {
    titleEn: "[★☆☆] Ending Rage",
    titleJp: "レイジ状態の解除",
    textJp: "レイジ状態は、レイジ状態を相手に当てると解除される。レイジドライブの空振りや、ダメージを受ける事でも解除に近づく。解除後はミスして復活するまでレイジ状態にならない。",
    titleJpEn: "Ending Rage",
    textJpEn: "The Rage state ends once a Rage attack connects with an opponent. Whiffing Rage Drive or taking damage also brings it closer to ending. After it ends, Kazuya won't enter the Rage state again until he's KO'd and respawns.",
    titlePt: "Fim do Rage",
    textPt: "O estado de Rage termina assim que um ataque de Rage acerta um oponente. Errar o Rage Drive ou sofrer dano também aproxima o fim do estado. Depois de terminar, Kazuya não entra em estado de Rage de novo até ser nocauteado e renascer.",
  },
  {
    titleEn: "[★☆☆] Glorious Demon God Fist (Side Smash Attack)",
    titleJp: "魔神閃焦拳 【横スマッシュ攻撃】",
    textJp: "クリーンヒットした時の威力は、カズヤのワザの中で最高レベル。スキが大きいが、相手を横方向に大きくふっとばせて、多人数での乱闘でも撃墜を狙いやすい。",
    titleJpEn: "Glorious Demon God Fist (Side Smash Attack)",
    textJpEn: "When it lands as a clean hit, its power is the highest level among all of Kazuya's moves. It leaves a large opening, but it launches opponents far sideways, making it easy to go for KOs even in free-for-alls.",
    titlePt: "Glorious Demon God Fist (Ataque Forte Lateral)",
    textPt: "Quando acerta em cheio, seu poder é o mais alto entre todos os golpes de Kazuya. Deixa uma grande brecha, mas lança oponentes para longe na lateral, facilitando buscar nocautes mesmo em confrontos com vários lutadores.",
  },
  {
    titleEn: "[★☆☆] Lion Slayer (Down Smash Attack)",
    titleJp: "獅子斬り包丁 【下スマッシュ攻撃】",
    textJp: "振り下ろした手刀には、メテオ効果がある。地上の相手に当てると、相手が地面にバウンドし、その後のコンボに繋げやすい。",
    titleJpEn: "Lion Slayer (Down Smash Attack)",
    textJpEn: "The downward hand-chop has a meteor effect. If it hits a grounded opponent, they bounce off the ground, making it easy to follow up with a combo.",
    titlePt: "Lion Slayer (Ataque Forte para Baixo)",
    textPt: "O golpe de mão para baixo tem efeito meteoro. Se atingir um oponente no chão, ele quica no chão, facilitando emendar um combo em seguida.",
  },
  {
    titleEn: "[★☆☆] Features of His Smash Attacks",
    titleJp: "スマッシュ攻撃の特徴",
    textJp: "すべてのスマッシュ攻撃には、出始めにスーパーアーマー効果がある。また、横スマッシュ攻撃と下スマッシュ攻撃は、相手のシールドを削りやすい。",
    titleJpEn: "Features of His Smash Attacks",
    textJpEn: "All of Kazuya's smash attacks have a Super Armor effect at the very start. Also, the side smash attack and down smash attack are effective at wearing down an opponent's shield.",
    titlePt: "Características dos Ataques Fortes",
    textPt: "Todos os ataques fortes de Kazuya têm efeito de Super Armadura bem no início. Além disso, o ataque forte lateral e o ataque forte para baixo são eficazes para desgastar o escudo do oponente.",
  },
  {
    titleEn: "[★☆☆] Command-Input Moves",
    titleJp: "コマンド入力ワザ",
    textJp: "↓＋攻撃ボタンや→→＋攻撃ボタンなど、地上で方向入力とボタンを組み合わせると、コマンド入力専用のワザを出せる。普通のワザより出すのが難しいが、どれも強力。",
    titleJpEn: "Command-Input Moves",
    textJpEn: "Combining a directional input with the attack button on the ground, such as ↓ + attack button or →→ + attack button, brings out moves exclusive to command input. They're harder to perform than regular moves, but all of them are powerful.",
    titlePt: "Golpes de Comando",
    textPt: "Combinar um input direcional com o botão de ataque no chão, como ↓ + botão de ataque ou →→ + botão de ataque, desfere golpes exclusivos de comando. Eles são mais difíceis de executar do que golpes normais, mas todos são poderosos.",
  },
  {
    titleEn: "[★☆☆] 10 Hit Combo (Command-Input Move)",
    titleJp: "１０連コンボ 【コマンド入力ワザ】",
    textJp: "攻撃ボタンを素早く連打するか長押しすると、１０回までコンボを繋げられる。最後の攻撃は、相手のシールドを無視してヒットする。",
    titleJpEn: "10-Hit Combo (Command-Input Move)",
    textJpEn: "Rapidly mashing or holding down the attack button can chain up to 10 hits in a combo. The final hit connects while ignoring the opponent's shield.",
    titlePt: "Combo de 10 Golpes (Golpe de Comando)",
    textPt: "Apertar rapidamente ou segurar o botão de ataque pode encadear até 10 acertos num combo. O golpe final acerta ignorando o escudo do oponente.",
  },
  {
    titleEn: "[★☆☆] Flash Punch Combo (Command-Input Move)",
    titleJp: "閃光烈拳 【コマンド入力ワザ】",
    textJp: "弱攻撃の３段目を、少し間を空けて入力すると出せる。攻撃力が高く、相手にダメージを与えていきたい時に特に有効。",
    titleJpEn: "Flash Punch Combo (Command-Input Move)",
    textJpEn: "Can be performed by inputting the third hit of the neutral attack with a slight pause. It deals high damage and is especially effective when trying to rack up damage on an opponent.",
    titlePt: "Flash Punch Combo (Golpe de Comando)",
    textPt: "Pode ser executado inserindo o terceiro golpe do ataque fraco com uma pequena pausa. Causa alto dano e é especialmente eficaz quando se quer acumular dano no oponente.",
  },
  {
    titleEn: "[★☆☆] Left Splits Kick (Command-Input Move)",
    titleJp: "左踵落とし 【コマンド入力ワザ】",
    textJp: "右向き時、素早く→→＋攻撃ボタンで出せる。威力が高めで、スキが小さい。また、相手の飛び道具を反射することができる。",
    titleJpEn: "Left Heel Drop (Command-Input Move)",
    textJpEn: "While facing right, can be performed quickly with →→ + attack button. It has fairly high power and leaves little opening. It can also reflect an opponent's projectile.",
    titlePt: "Left Splits Kick (Golpe de Comando)",
    textPt: "Virado para a direita, pode ser executado rapidamente com →→ + botão de ataque. Tem poder razoavelmente alto e deixa pouca brecha. Também pode refletir o projétil de um oponente.",
  },
  {
    titleEn: "[★☆☆] Twin Pistons (Command-Input Move)",
    titleJp: "ダブルアッパー 【コマンド入力ワザ】",
    textJp: "↑＋攻撃ボタンでアッパーを出し、再度攻撃ボタンでダブルアッパーを出せる。ワザの間は上半身が無敵になるため、対空攻撃として強力。",
    titleJpEn: "Double Uppercut (Command-Input Move)",
    textJpEn: "Pressing ↑ + attack button brings out an uppercut, and pressing the attack button again brings out a double uppercut. The upper body is invincible during the move, making it a powerful anti-air attack.",
    titlePt: "Twin Pistons (Golpe de Comando)",
    textPt: "Pressionar ↑ + botão de ataque desfere um upper, e pressionar o botão de ataque novamente desfere um duplo upper. A parte superior do corpo fica invencível durante o golpe, tornando-o um poderoso ataque antiaéreo.",
  },
  {
    titleEn: "[★★☆] Using Twin Pistons (Command-Input Move)",
    titleJp: "ダブルアッパーの使い分け 【コマンド入力ワザ】",
    textJp: "初段で止めると、相手を打ち上げてから他のワザで追撃を狙いやすい。２段目まで出すと、相手を大きくふっとばせる。",
    titleJpEn: "Using Double Uppercut (Command-Input Move)",
    textJpEn: "Stopping at the first hit launches the opponent upward, making it easy to follow up with another move. Going all the way to the second hit launches the opponent much farther.",
    titlePt: "Usando o Twin Pistons (Golpe de Comando)",
    textPt: "Parar no primeiro golpe lança o oponente para cima, facilitando emendar outro golpe em seguida. Ir até o segundo golpe lança o oponente muito mais longe.",
  },
  {
    titleEn: "[★☆☆] Roundhouse to Triple Spin Kicks (Command-Input Move)",
    titleJp: "螺旋幻魔脚 【コマンド入力ワザ】",
    textJp: "右向き時、↗＋攻撃ボタン４回入力で出せる。初段がヒットすれば、４連撃で大ダメージを与えられる。初段は軽くジャンプするため、足元への攻撃を避けつつ反撃を狙える。",
    titleJpEn: "Spiral Phantom Demon Leg (Command-Input Move)",
    textJpEn: "While facing right, can be performed by inputting ↗ + attack button 4 times. If the first hit connects, all 4 hits deal massive damage. Since the first hit involves a small hop, it can dodge low attacks while going for a counter.",
    titlePt: "Roundhouse to Triple Spin Kicks (Golpe de Comando)",
    textPt: "Virado para a direita, pode ser executado inserindo ↗ + botão de ataque 4 vezes. Se o primeiro golpe acertar, todos os 4 golpes causam dano massivo. Como o primeiro golpe envolve um pequeno salto, é possível esquivar de ataques baixos enquanto busca um contra-ataque.",
  },
  {
    titleEn: "[★☆☆] Oni Front Kick (Command-Input Move)",
    titleJp: "鬼蹴り 【コマンド入力ワザ】",
    textJp: "→＋攻撃ボタンで出せる。ほぼ真横に相手をふっとばす。相手をガケに追い詰めたり、そこからの撃墜を狙ったりしやすい。復帰力が弱い相手には、特に有効。",
    titleJpEn: "Oni Front Kick (Command-Input Move)",
    textJpEn: "Can be performed with → + attack button. It launches the opponent almost straight sideways. It's easy to use to corner an opponent toward the ledge and go for a KO from there. Especially effective against opponents with weak recovery.",
    titlePt: "Oni Front Kick (Golpe de Comando)",
    textPt: "Pode ser executado com → + botão de ataque. Lança o oponente quase diretamente para o lado. É fácil usá-lo para encurralar o oponente perto da borda e buscar um nocaute a partir daí. Especialmente eficaz contra oponentes com recuperação fraca.",
  },
  {
    titleEn: "[★☆☆] Tsunami Kick (Command-Input Move)",
    titleJp: "踵切り 【コマンド入力ワザ】",
    textJp: "右向き時、↘＋攻撃ボタンで相手を浮かせ、再度攻撃ボタンで相手を高めにふっとばす。１段目はコンボに繋げやすく、２段目は相手のシールドを削りやすい。",
    titleJpEn: "Heel Slice (Command-Input Move)",
    textJpEn: "While facing right, ↘ + attack button pops the opponent up, and pressing the attack button again launches them higher. The first hit is easy to combo from, and the second hit is effective at wearing down the opponent's shield.",
    titlePt: "Tsunami Kick (Golpe de Comando)",
    textPt: "Virado para a direita, ↘ + botão de ataque levanta o oponente, e pressionar o botão de ataque novamente o lança mais alto. O primeiro golpe é fácil de encadear num combo, e o segundo golpe é eficaz para desgastar o escudo do oponente.",
  },
  {
    titleEn: "[★☆☆] Nejiri Uraken (Command-Input Move)",
    titleJp: "捻り裏拳 【コマンド入力ワザ】",
    textJp: "↓＋攻撃ボタンで出せる。ワザの後半、裏拳をくり出す瞬間は無敵になる。裏拳をくり出す前にシールドボタンを押すと、ワザをキャンセルできる。",
    titleJpEn: "Twisting Backfist (Command-Input Move)",
    textJpEn: "Can be performed with ↓ + attack button. In the second half of the move, the instant the backfist is thrown, Kazuya becomes invincible. Pressing the shield button before throwing the backfist cancels the move.",
    titlePt: "Nejiri Uraken (Golpe de Comando)",
    textPt: "Pode ser executado com ↓ + botão de ataque. Na segunda metade do golpe, no instante em que o soco de costa da mão é desferido, Kazuya fica invencível. Pressionar o botão de escudo antes de desferir o soco cancela o golpe.",
  },
  {
    titleEn: "[★☆☆] Stature Smash (Command-Input Move)",
    titleJp: "腿砕き 【コマンド入力ワザ】",
    textJp: "右向き時、↙＋攻撃ボタンで出せる。リーチが短めだが、スキが小さく、当てれば相手を転ばせてさらなる追撃を狙える。",
    titleJpEn: "Thigh Crusher (Command-Input Move)",
    textJpEn: "While facing right, can be performed with ↙ + attack button. Its reach is fairly short, but it leaves little opening, and landing it trips the opponent, opening the door for a further follow-up.",
    titlePt: "Stature Smash (Golpe de Comando)",
    textPt: "Virado para a direita, pode ser executado com ↙ + botão de ataque. O alcance é relativamente curto, mas deixa pouca brecha, e acertá-lo derruba o oponente, abrindo espaço para um golpe de acompanhamento adicional.",
  },
  {
    titleEn: "[★☆☆] Flash Tornado (Command-Input Move)",
    titleJp: "刃閃風 【コマンド入力ワザ】",
    textJp: "右向き時、←＋攻撃ボタンで出せる。上半身無敵で斜め上を攻撃でき、上方から攻めてくる相手に対して有利に反撃しやすい。",
    titleJpEn: "Blade Flash Wind (Command-Input Move)",
    textJpEn: "While facing right, can be performed with ← + attack button. It attacks diagonally upward with an invincible upper body, making it easy to counterattack favorably against opponents coming from above.",
    titlePt: "Flash Tornado (Golpe de Comando)",
    textPt: "Virado para a direita, pode ser executado com ← + botão de ataque. Ataca na diagonal para cima com a parte superior do corpo invencível, facilitando contra-atacar de forma vantajosa contra oponentes atacando de cima.",
  },
  {
    titleEn: "[★★☆] Jump Side Kick (Command-Input Move)",
    titleJp: "ジャンプサイドキック 【コマンド入力ワザ】",
    textJp: "右向き時、↖＋攻撃ボタンで出せ、相手と距離を置きつつ攻撃できる。ジャンプ中は相手につかまれにくいため、近付いてくる相手の迎撃に有効。",
    titleJpEn: "Jump Side Kick (Command-Input Move)",
    textJpEn: "While facing right, can be performed with ↖ + attack button, attacking while keeping distance from the opponent. Since Kazuya is hard to grab while jumping, it's effective for intercepting an approaching opponent.",
    titlePt: "Jump Side Kick (Golpe de Comando)",
    textPt: "Virado para a direita, pode ser executado com ↖ + botão de ataque, atacando enquanto mantém distância do oponente. Como Kazuya é difícil de agarrar enquanto pula, é eficaz para interceptar um oponente se aproximando.",
  },
  {
    titleEn: "[★☆☆] Jump Side Kick Invincibility (Command-Input Move)",
    titleJp: "ジャンプサイドキックの無敵 【コマンド入力ワザ】",
    textJp: "ワザの出始め、下半身が無敵になる。蹴り出した脚が無敵のまま攻撃できるため、上空の相手に打ち勝ちやすい。",
    titleJpEn: "Jump Side Kick Invincibility (Command-Input Move)",
    textJpEn: "At the very start of the move, the lower body becomes invincible. Since the kicking leg can attack while still invincible, it's easy to beat out opponents above.",
    titlePt: "Invencibilidade do Jump Side Kick (Golpe de Comando)",
    textPt: "Bem no início do golpe, a parte inferior do corpo fica invencível. Como a perna do chute pode atacar enquanto ainda está invencível, é fácil vencer oponentes acima.",
  },
  {
    titleEn: "[★☆☆] Tombstone Crusher (Command-Input Move)",
    titleJp: "螺旋岩砕蹴 【コマンド入力ワザ】",
    textJp: "右向き時、しゃがみ中 ↘＋攻撃ボタンで出せる。無敵が長く、上から来る相手を迎撃しやすい。対空攻撃としては低めの方向にふっとばすため、撃墜も狙えるワザ。",
    titleJpEn: "Spiral Rock-Crushing Kick (Command-Input Move)",
    textJpEn: "While facing right and crouching, can be performed with ↘ + attack button. It has long invincibility, making it easy to intercept opponents coming from above. As an anti-air, it launches at a fairly low angle, so it can also be used to go for a KO.",
    titlePt: "Tombstone Crusher (Golpe de Comando)",
    textPt: "Virado para a direita e agachado, pode ser executado com ↘ + botão de ataque. Tem invencibilidade longa, facilitando interceptar oponentes vindos de cima. Como antiaéreo, lança num ângulo relativamente baixo, então também pode ser usado para buscar um nocaute.",
  },
  {
    titleEn: "[★☆☆] Crouch Jab (Command-Input Move)",
    titleJp: "シットジャブ 【コマンド入力ワザ】",
    textJp: "しゃがみ中に↓＋攻撃ボタンで出せる。出が早くスキが少ない。鬼蹴りや風神拳、奈落旋風へのコンボに繋げやすい。また、連打で相手のけん制にも使える。",
    titleJpEn: "Crouch Jab (Command-Input Move)",
    textJpEn: "Can be performed while crouching with ↓ + attack button. It comes out quickly and leaves little opening. It's easy to combo into Oni Front Kick, Wind God Fist, or Spinning Demon to Left Hook. It can also be mashed to keep an opponent in check.",
    titlePt: "Crouch Jab (Golpe de Comando)",
    textPt: "Pode ser executado enquanto agachado com ↓ + botão de ataque. Sai rápido e deixa pouca brecha. É fácil de encadear em Oni Front Kick, Wind God Fist, ou Spinning Demon to Left Hook. Também pode ser usado repetidamente para pressionar o oponente à distância.",
  },
  {
    titleEn: "[★☆☆] Crouch Spin Kick (Command-Input Move)",
    titleJp: "シットスピンキック 【コマンド入力ワザ】",
    textJp: "右向き時、しゃがみ中に ↙＋攻撃ボタンで出せる。低い姿勢で攻撃するため、相手の攻撃をかわして割り込みやすい。",
    titleJpEn: "Crouch Spin Kick (Command-Input Move)",
    textJpEn: "While facing right and crouching, can be performed with ↙ + attack button. Since it attacks from a low stance, it's easy to dodge an opponent's attack and interrupt them.",
    titlePt: "Crouch Spin Kick (Golpe de Comando)",
    textPt: "Virado para a direita e agachado, pode ser executado com ↙ + botão de ataque. Como ataca a partir de uma postura baixa, é fácil esquivar do ataque do oponente e interrompê-lo.",
  },
  {
    titleEn: "[★☆☆] Demon God Fist (Command-Input Move)",
    titleJp: "魔神拳 【コマンド入力ワザ】",
    textJp: "しゃがんでいる状態から立ち上がるまでに攻撃ボタンで出せる。当たった相手をしびれさせ、追撃を狙える強力なワザ。その分、ワザ後のスキが大きめ。",
    titleJpEn: "Demon God Fist (Command-Input Move)",
    textJpEn: "Can be performed with the attack button while rising from a crouch. It's a powerful move that stuns an opponent it hits, opening the door for a follow-up. In exchange, it leaves a fairly large opening afterward.",
    titlePt: "Demon God Fist (Golpe de Comando)",
    textPt: "Pode ser executado com o botão de ataque enquanto se levanta de um agachamento. É um golpe poderoso que atordoa um oponente atingido, abrindo espaço para um golpe de acompanhamento. Em troca, deixa uma brecha razoavelmente grande depois.",
  },
  {
    titleEn: "[★☆☆] Gates of Hell (Command-Input Move)",
    titleJp: "地獄門 【コマンド入力ワザ】",
    textJp: "右向き時、↘↓↘＋つかみで出せる。かなりの高威力で、大きく踏み込むためリーチも長い。入力は難しいが、横方向に相手を大きくふっとばすため、撃墜にも使える。",
    titleJpEn: "Gates of Hell (Command-Input Move)",
    textJpEn: "While facing right, can be performed with ↘↓↘ + grab. It has considerably high power, and since it involves a large step forward, it also has long reach. The input is difficult, but since it launches opponents far sideways, it can also be used to go for a KO.",
    titlePt: "Gates of Hell (Golpe de Comando)",
    textPt: "Virado para a direita, pode ser executado com ↘↓↘ + agarrão. Tem poder consideravelmente alto, e como envolve um grande passo à frente, também tem alcance longo. O input é difícil, mas como lança oponentes para longe na lateral, também pode ser usado para buscar um nocaute.",
  },
  {
    titleEn: "[★☆☆] Crouch Dash (Command-Input Move)",
    titleJp: "風神ステップ 【コマンド入力ワザ】",
    textJp: "右向き時、→↓↘で出せる特別なダッシュ。移動の初めは全身が無敵になり、立ち上がるまでは上半身が無敵になる。相手の攻撃を避けつつ、間合いを素早く詰められる。",
    titleJpEn: "Wind God Step (Command-Input Move)",
    textJpEn: "While facing right, this is a special dash performed with →↓↘. The whole body is invincible at the start of the movement, and the upper body remains invincible until Kazuya stands back up. It lets him quickly close the distance while dodging an opponent's attack.",
    titlePt: "Crouch Dash (Golpe de Comando)",
    textPt: "Virado para a direita, essa é uma corrida especial executada com →↓↘. O corpo inteiro fica invencível no início do movimento, e a parte superior do corpo permanece invencível até Kazuya se levantar. Isso permite fechar a distância rapidamente enquanto esquiva do ataque do oponente.",
  },
  {
    titleEn: "[★★☆] Movement after Crouch Dash (Command-Input Move)",
    titleJp: "風神ステップからの行動",
    textJp: "風神ステップから奈落旋風や風神拳を出すと、相手をけん制できる。一方シールドを固める相手には、風神ステップ後にヘブンズドアや地獄門でつかむ戦法が有効。",
    titleJpEn: "Movement after Wind God Step (Command-Input Move)",
    textJpEn: "Following up Wind God Step with Spinning Demon to Left Hook or Wind God Fist can keep an opponent in check. On the other hand, against an opponent turtling behind a shield, a strategy of grabbing with Heaven's Door or Gates of Hell after Wind God Step is effective.",
    titlePt: "Movimento Depois do Crouch Dash (Golpe de Comando)",
    textPt: "Encadear o Crouch Dash com Spinning Demon to Left Hook ou Wind God Fist pode pressionar o oponente à distância. Por outro lado, contra um oponente na defensiva atrás do escudo, uma estratégia de agarrar com Heaven's Door ou Gates of Hell depois do Crouch Dash é eficaz.",
  },
  {
    titleEn: "[★☆☆] Wind God Fist (Command-Input Move)",
    titleJp: "風神拳 【コマンド入力ワザ】",
    textJp: "右向き時、→↓↘＋攻撃ボタンで出せる。風神ステップで一気に間合いを詰めて攻撃できる。高威力なうえ、ヒット後に追撃してコンボにつなげやすいワザ。",
    titleJpEn: "Wind God Fist (Command-Input Move)",
    textJpEn: "While facing right, can be performed with →↓↘ + attack button. It uses Wind God Step to close the distance in one go and attack. It deals high damage and is easy to follow up into a combo after it hits.",
    titlePt: "Wind God Fist (Golpe de Comando)",
    textPt: "Virado para a direita, pode ser executado com →↓↘ + botão de ataque. Usa o Crouch Dash para fechar a distância de uma vez e atacar. Causa alto dano e é fácil de encadear num combo depois de acertar.",
  },
  {
    titleEn: "[★★☆] Electric Wind God Fist (Command-Input Move)",
    titleJp: "最速風神拳 【コマンド入力ワザ】",
    textJp: "右向き時、→↓↘＋攻撃ボタンで風神拳を出す際、↘と攻撃ボタンを同時押しで出せる。風神拳より出始めの無敵が長く、威力も高め。当たると相手をしびれさせ、追撃を狙いやすい。",
    titleJpEn: "Electric Wind God Fist (Command-Input Move)",
    textJpEn: "While facing right, when performing Wind God Fist with →↓↘ + attack button, pressing ↘ and the attack button at the same time brings this out instead. It has longer invincibility at the start than Wind God Fist and deals higher damage. If it hits, it stuns the opponent, making it easy to follow up.",
    titlePt: "Electric Wind God Fist (Golpe de Comando)",
    textPt: "Virado para a direita, ao executar o Wind God Fist com →↓↘ + botão de ataque, pressionar ↘ e o botão de ataque ao mesmo tempo desfere esse golpe no lugar. Tem invencibilidade mais longa no início do que o Wind God Fist e causa mais dano. Se acertar, atordoa o oponente, facilitando um golpe de acompanhamento.",
  },
  {
    titleEn: "[★★☆] Electric Wind God Fist and Shields (Command-Input Move)",
    titleJp: "最速風神拳とシールド 【コマンド入力ワザ】",
    textJp: "風神拳とは異なり、最速風神拳はシールドされた時に相手を引き離して、間合いを取ることができる。",
    titleJpEn: "Electric Wind God Fist and Shields (Command-Input Move)",
    textJpEn: "Unlike Wind God Fist, when Electric Wind God Fist is blocked by a shield, it pushes the opponent away, creating distance.",
    titlePt: "Electric Wind God Fist e Escudos (Golpe de Comando)",
    textPt: "Diferente do Wind God Fist, quando o Electric Wind God Fist é bloqueado por um escudo, ele empurra o oponente para longe, criando distância.",
  },
  {
    titleEn: "[★☆☆] Dragon Uppercut (Command-Input Move)",
    titleJp: "雷神拳 【コマンド入力ワザ】",
    textJp: "右向き時、→↓↘＋攻撃ボタン長押しで出せる。ワザの出始めは全身が無敵になり、アッパー中も上半身の無敵が続く。攻撃の出が遅いものの、高威力な一撃。",
    titleJpEn: "Thunder God Fist (Command-Input Move)",
    textJpEn: "While facing right, can be performed with →↓↘ + held attack button. The whole body is invincible at the very start of the move, and the upper body remains invincible throughout the uppercut. It's slow to come out, but it's a high-power blow.",
    titlePt: "Dragon Uppercut (Golpe de Comando)",
    textPt: "Virado para a direita, pode ser executado com →↓↘ + botão de ataque segurado. O corpo inteiro fica invencível bem no início do golpe, e a parte superior do corpo permanece invencível durante todo o upper. Demora para sair, mas é um golpe de alto poder.",
  },
  {
    titleEn: "[★☆☆] Spinning Demon to Left Hook (Command-Input Move)",
    titleJp: "奈落旋風 【コマンド入力ワザ】",
    textJp: "右向き時、→↓↘＋必殺ワザボタンで出せる。出始めは全身無敵になり、間合いを詰めつつ相手を大きくふっとばせる。レイジドライブを温存したい時にも、代わりに撃墜を狙いやすい。",
    titleJpEn: "Abyss Whirlwind (Command-Input Move)",
    textJpEn: "While facing right, can be performed with →↓↘ + special-move button. The whole body is invincible at the start, and it closes the distance while launching the opponent far. It's also useful for going for a KO instead when you want to save Rage Drive.",
    titlePt: "Spinning Demon to Left Hook (Golpe de Comando)",
    textPt: "Virado para a direita, pode ser executado com →↓↘ + botão de especial. O corpo inteiro fica invencível no início, e fecha a distância enquanto lança o oponente para longe. Também é útil para buscar um nocaute no lugar quando se quer economizar o Rage Drive.",
  },
  {
    titleEn: "[★☆☆] Leaping Sidekick",
    titleJp: "空斬脚",
    textJp: "ダッシュ中に攻撃ボタンで出せる。足元への攻撃を避けながら前進し、相手を攻撃できる。ただし、背面は無防備。",
    titleJpEn: "Air-Cutting Leg",
    textJpEn: "Can be performed with the attack button while dashing. It advances forward while dodging low attacks and can strike the opponent. However, Kazuya's back is left defenseless.",
    titlePt: "Leaping Sidekick",
    textPt: "Pode ser executado com o botão de ataque durante a corrida. Avança para frente enquanto esquiva de ataques baixos e pode atingir o oponente. Porém, as costas de Kazuya ficam desprotegidas.",
  },
  {
    titleEn: "[★☆☆] Face Off 1-on-1",
    titleJp: "1on1での振り向き",
    textJp: "１対１の対戦では、自動で相手側に向く。コマンド入力の向きに気を付けよう。",
    titleJpEn: "Turning to Face in 1-on-1",
    textJpEn: "In 1-on-1 battles, Kazuya automatically faces toward his opponent. Pay attention to the direction when entering commands.",
    titlePt: "Virada de Frente no 1 contra 1",
    textPt: "Em batalhas 1 contra 1, Kazuya automaticamente vira de frente para o oponente. Preste atenção à direção ao inserir comandos.",
  },
  {
    titleEn: "[★☆☆] Tough Body",
    titleJp: "強靭な肉体",
    textJp: "蓄積ダメージが少ない間は、相手からの弱い攻撃ではひるまない。反撃からのコンボを狙いやすい。",
    titleJpEn: "Tough Body",
    textJpEn: "While his accumulated damage is low, Kazuya won't flinch from an opponent's weak attacks. This makes it easy to go for a combo off a counterattack.",
    titlePt: "Tough Body",
    textPt: "Enquanto o dano acumulado dele está baixo, Kazuya não se abala com ataques fracos do oponente. Isso facilita buscar um combo a partir de um contra-ataque.",
  },
  {
    titleEn: "[★★☆] Moves Good for Follow-Up Attacks",
    titleJp: "追撃に使いやすいワザ",
    textJp: "横必殺ワザの出始めヒットなどで相手にスキが生じたら、追撃には腿砕き(↙＋攻撃ボタン)や獅子斬り包丁(下スマッシュ攻撃)、螺旋幻魔脚(↗＋攻撃ボタン４回)などがオススメ。",
    titleJpEn: "Moves Good for Follow-Up Attacks",
    textJpEn: "When an opponent is left open, such as from the initial hit of the side special, good follow-up options include Thigh Crusher (↙ + attack button), Lion Slayer (down smash attack), and Spiral Phantom Demon Leg (↗ + attack button x4).",
    titlePt: "Golpes Bons para Ataques de Acompanhamento",
    textPt: "Quando o oponente fica exposto, como pelo acerto inicial do especial lateral, boas opções de acompanhamento incluem Stature Smash (↙ + botão de ataque), Lion Slayer (ataque forte para baixo), e Roundhouse to Triple Spin Kicks (↗ + botão de ataque x4).",
  },
];

async function main() {
  const kazuya = await db.fighter.findFirst({
    where: { name: { contains: "Kazuya", mode: "insensitive" } },
    select: { id: true, tips: { select: { id: true, titleEn: true } } },
  });
  if (!kazuya) { console.log("Kazuya not found"); return; }

  await db.fighter.update({
    where: { id: kazuya.id },
    data: {
      curatorOverviewEn: "Kazuya imports Tekken's command-input execution wholesale: nearly every one of his most powerful tools — Wind God Fist, its frame-perfect Electric Wind God Fist variant, the Crouch Dash chain that sets them both up, Thunder God Fist, Gates of Hell, and a dozen more directional strikes — requires a real fighting-game motion rather than a single button, and all of it sits on top of a standard Smash moveset. His four specials are built around commitment: Devil Blaster is a piercing beam that can hit up to three fighters in a line but loses power with each one, Devil Fist is a full-screen dash punch that's briefly invincible on the way out but doesn't stop at the ledge in midair — a real self-destruct risk — Devil Wings doubles as recovery and an aerial claw attack, and Heaven's Door is a command grab that ignores shields entirely, with the escape from its aerial slam decided by a literal stick-mashing tug-of-war weighted toward whoever has less damage. Every one of his smash attacks opens with super armor, letting him force them through weaker hits. The centerpiece is Rage: crossing 100% damage (or dropping below a quarter of his stamina) buffs his power and unlocks Rage Drive, a shield-ignoring, low-commitment finisher — but whiffing it, or simply taking more damage, burns through the Rage state faster, and once it's gone it doesn't come back until his next stock. Between his resistance to being flinched out of weak hits and a long list of command normals built specifically to convert a single opening into a full combo, Kazuya rewards players willing to learn genuine execution over a character who can win on simple inputs alone.",
      curatorOverviewPt: "Kazuya importa a execução por comando de Tekken quase por completo: quase todas as suas ferramentas mais poderosas — Wind God Fist, sua variante de frame perfeito Electric Wind God Fist, o encadeamento Crouch Dash que prepara as duas, Thunder God Fist, Gates of Hell, e mais uma dúzia de golpes direcionais — exige um movimento de verdade de jogo de luta em vez de um único botão, tudo isso em cima de um moveset padrão do Smash. Os quatro especiais dele são construídos em torno de comprometimento: o Devil Blaster é um feixe perfurante que pode atingir até três lutadores em linha, mas perde poder a cada um, o Devil Fist é uma investida de punho que cobre a tela inteira e é brevemente invencível na saída, mas não para na borda no ar — um risco real de autodestruição — o Devil Wings funciona tanto como recuperação quanto como ataque aéreo de garra, e o Heaven's Door é um agarrão de comando que ignora escudos por completo, com a fuga do arremesso aéreo decidida por um verdadeiro cabo de guerra de apertar o direcional, favorecendo quem tem menos dano. Todos os ataques fortes dele abrem com super armadura, permitindo forçá-los através de golpes mais fracos. O ponto central é o Rage: ultrapassar 100% de dano (ou cair abaixo de um quarto da resistência) melhora seu poder e libera o Rage Drive, um finalizador de baixo comprometimento que ignora escudos — mas errá-lo, ou simplesmente sofrer mais dano, consome o estado de Rage mais rápido, e uma vez que acaba, só volta na próxima vida. Entre a resistência dele a se abalar com golpes fracos e uma longa lista de golpes de comando construídos especificamente para converter uma única brecha num combo completo, Kazuya recompensa jogadores dispostos a aprender execução de verdade, em vez de ser um personagem que vence só com inputs simples.",
      curatorOverviewJp: "カズヤは『鉄拳』のコマンド入力による操作をほぼそのまま持ち込んでいる——風神拳、フレーム精度が求められる派生技の最速風神拳、その両方への布石となる風神ステップの連携、雷神拳、地獄門、その他十数種類の方向入力ワザまで、彼の最も強力な道具のほとんどが、単一ボタンではなく本物の格闘ゲームの入力を要求する。それらすべてが、通常のスマブラのワザ構成の上に積み重なっている。４つの必殺ワザは踏み込みを軸に組まれている——「デビルブラスター」は最大３人のファイターを一直線に貫通できるビームだが、当てるたびに威力が落ちる。「デビルフィスト」は画面いっぱいに突進する拳で、出だしに一瞬無敵になるが、空中ではガケ際で止まらない——実質的な自滅リスクだ。「デビルウィング」は復帰と空中の爪攻撃を兼ねる。「ヘブンズドア」はシールドを完全に無視するコマンドつかみで、空中での叩きつけからの脱出は、ダメージの少ないほうが有利になる文字通りのスティック押し合いで決まる。彼のスマッシュ攻撃はすべて出始めにスーパーアーマーがあり、弱い攻撃を受けながらでも強引にくり出せる。中心となるのは「レイジ」だ——蓄積ダメージが１００％を超える（あるいは体力制で残り体力が１／４を切る）と攻撃力が上がり、シールドを無視する低リスクの必殺技「レイジドライブ」が解禁される——しかし空振りしたり、単にダメージを受けたりするだけでもレイジ状態の消費は早まり、一度なくなると次のストックまで戻ってこない。弱い攻撃でひるまない耐性と、たった１つの隙をフルコンボへと変えるために特化した膨大な数のコマンド技のリストを併せ持つカズヤは、単純な入力だけで勝てるファイターというより、本物の実行力を学ぶ意志のあるプレイヤーに報いるキャラクターだ。",
      curatorOverviewJpEn: "Kazuya imports Tekken's command-input execution almost entirely as-is — Wind God Fist; its frame-precise variant, Electric Wind God Fist; the Crouch Dash chain that sets up both of them; Thunder God Fist; Gates of Hell; and more than a dozen other directional strikes. Most of his most powerful tools require a genuine fighting-game input rather than a single button, and all of it is stacked on top of a standard Smash moveset. His four special moves are built around commitment — \"Devil Blaster\" is a beam that can pierce through up to 3 fighters in a straight line, but loses power with each one it hits. \"Devil Fist\" is a full-screen charging punch, briefly invincible at the start, but it doesn't stop at the ledge in midair — a genuine self-destruct risk. \"Devil Wings\" doubles as both recovery and an aerial claw attack. \"Heaven's Door\" is a command grab that completely ignores shields, and escaping its aerial slam is decided by a literal tug-of-war on the stick that favors whoever has less damage. All of his smash attacks have Super Armor at the very start, letting him force them out through weaker attacks. The centerpiece is \"Rage\" — once accumulated damage exceeds 100% (or, in Stamina mode, remaining stamina drops below a quarter), his attack power increases and \"Rage Drive,\" a low-commitment finisher that ignores shields, becomes available. However, whiffing it, or simply taking more damage, speeds up the end of the Rage state, and once it ends, it won't return until his next stock. Combining his resistance to flinching from weak attacks with a massive list of command moves built specifically to convert a single opening into a full combo, Kazuya rewards players willing to learn genuine execution, rather than being a fighter who can win on simple inputs alone.",
    },
  });
  console.log("✅ Curator Overview (4 langs)");

  let updated = 0;
  for (const data of TIPS) {
    const tip = kazuya.tips.find(t => t.titleEn === data.titleEn);
    if (!tip) { console.log(`  ⚠️  Tip não encontrada: "${data.titleEn}"`); continue; }
    await db.fighterTip.update({
      where: { id: tip.id },
      data: {
        titleJp: data.titleJp, textJp: data.textJp,
        titleJpEn: data.titleJpEn, textJpEn: data.textJpEn,
        titlePt: data.titlePt, textPt: data.textPt,
      },
    });
    updated++;
  }
  console.log(`✅ ${updated}/${TIPS.length} tips atualizadas`);

  await db.fighter.update({ where: { id: kazuya.id }, data: { curationStatus: "approved" } });
  console.log("✅ Kazuya aprovado");

  // Sem FighterMove (0 registros) — newcomer DLC exclusivo do Ultimate, não é lacuna.
  // Nenhum troféu existe (newcomer DLC) — fallback via FighterChronicleLink já lista Tekken corretamente.
  // Sem timing de vídeo novo fornecido. SSBU bio JP ausente — aprovado direto, padrão já estabelecido.
  // Vários nomes de golpes de comando divergem entre JP literal e a localização EN oficial (ex: 雷神拳
  // "Thunder God Fist" -> "Dragon Uppercut", 奈落旋風 "Abyss Whirlwind" -> "Spinning Demon to Left Hook",
  // 風神ステップ "Wind God Step" -> "Crouch Dash") — mantidos fiéis em cada idioma, sem reconciliar,
  // mesmo padrão já visto em Min Min, Sephiroth e Steve.

  await db.$disconnect();
}
main().catch(console.error);
