import { db } from "../../lib/db";

const BIO_PT_JPEN: Record<string, { pt: string; jpEn: string }> = {
  SSB4: {
    jpEn: "Joins the fight from \"Bayonetta.\" A survivor of the Umbra Witches clan, which was wiped out centuries ago. \"Bullet Arts,\" a fighting style weaving together strikes and gunfire, and \"Wicked Weave,\" which uses her own hair as a catalyst to summon a demon's limbs, remain intact in \"Super Smash Bros.\" as well. Additionally, all of her standard moves can fire bullets in rapid succession if the button is held down. This isn't only useful for chasing extra damage — it's also effective for keeping opponents in check.",
    pt: "Entra na luta vindo de \"Bayonetta\". Uma sobrevivente do clã das Umbra Witches, exterminado séculos atrás. \"Bullet Arts\", um estilo de luta que entrelaça golpes e tiros, e \"Wicked Weave\", que usa seu próprio cabelo como catalisador para convocar os membros de um demônio, permanecem intactos também em \"Super Smash Bros.\". Além disso, todos os seus golpes padrão podem disparar balas em sucessão rápida se o botão for segurado. Isso não é útil apenas para buscar dano extra — também é eficaz para conter adversários.",
  },
};

const TIPS = [
  { titleEn: "[★☆☆] In Her Series", titleJp: "原作では", textJp: "記憶を失った魔女で、本名は「セレッサ」。メガネは絶対に外さない。両手両足に装備した四丁一組の銃を駆使した格闘術「バレットアーツ」を使いこなす。", titleJpEn: "In the Original Game", textJpEn: "A witch who lost her memory, whose real name is \"Cereza.\" She never takes off her glasses. She's mastered \"Bullet Arts,\" a fighting style that makes full use of a set of four guns equipped on both her hands and feet.", titlePt: "Na Série Original", textPt: "Uma bruxa que perdeu a memória, cujo nome verdadeiro é \"Cereza\". Ela nunca tira os óculos. Ela domina o \"Bullet Arts\", um estilo de luta que usa plenamente um conjunto de quatro armas equipadas em ambas as mãos e pés." },
  { titleEn: "[★☆☆] Rapid Fire with Bullet Climax (Neutral Special)", titleJp: "バレットクライマックスの連射 【通常必殺ワザ】", textJp: "ワザを出すたび、手射撃と足射撃が交互に切り替わる。発射中にボタンを連打すると、射撃する回数が増える。", titleJpEn: "Rapid Fire with Bullet Climax (Neutral Special)", textJpEn: "Each time the move is used, it alternates between firing from her hands and from her feet. Mashing the button while firing increases the number of shots.", titlePt: "Rajada com o Bullet Climax (Especial Neutro)", textPt: "Toda vez que o golpe é usado, ele alterna entre disparar das mãos e dos pés. Apertar o botão repetidamente enquanto atira aumenta o número de tiros." },
  { titleEn: "[★☆☆] Bullet Climax's Charge (Neutral Special)", titleJp: "バレットクライマックスのチャージ 【通常必殺ワザ】", textJp: "ボタン長押しでためるとチャージバレットとなり、威力がアップ。最初の４発のみが強化され、追加射撃には影響しない。", titleJpEn: "Bullet Climax's Charge (Neutral Special)", textJpEn: "Holding the button down to charge creates Charge Bullets, boosting power. Only the first four shots are strengthened; it has no effect on the additional shots.", titlePt: "A Carga do Bullet Climax (Especial Neutro)", textPt: "Segurar o botão para carregar cria Charge Bullets, aumentando o poder. Apenas os primeiros quatro tiros são reforçados; não tem efeito nos tiros adicionais." },
  { titleEn: "[★☆☆] Heel Slide (Side Special)", titleJp: "ヒールスライド 【横必殺ワザ】", textJp: "低い姿勢で突進するスライディングキック。ボタン長押しで、足先から追加射撃と蹴り上げ攻撃が出せる。", titleJpEn: "Heel Slide (Side Special)", textJpEn: "A low-profile charging slide kick. Holding down the button adds shots fired from her feet followed by an upward kick attack.", titlePt: "Heel Slide (Especial Lateral)", textPt: "Um chute deslizante de investida com perfil baixo. Segurar o botão adiciona tiros disparados dos pés seguidos de um ataque de chute para cima." },
  { titleEn: "[★☆☆] Two-Part After Burner Kick (Side Special)", titleJp: "２段アフターバーナーキック 【横必殺ワザ】", textJp: "攻撃を当てて、約１秒以内であれば、もう１度アフターバーナーキックを繰り出せる。コンボをより強力にすることもでき、長距離を移動するのにも役立つ。", titleJpEn: "Two-Part After Burner Kick (Side Special)", textJpEn: "If she lands the attack, After Burner Kick can be used once more within about one second. It can make combos stronger and is also useful for traveling long distances.", titlePt: "After Burner Kick em Duas Partes (Especial Lateral)", textPt: "Se ela acertar o ataque, o After Burner Kick pode ser usado mais uma vez dentro de cerca de um segundo. Pode tornar os combos mais fortes e também é útil para percorrer longas distâncias." },
  { titleEn: "[★☆☆] After Burner Kick Angle (Side Special)", titleJp: "アフターバーナーキックの角度 【横必殺ワザ】", textJp: "下入力をしてからアフターバーナーキックを出すか、必殺ワザ入力直後に下入力をすれば、斜め下にワザを繰り出すことができる。", titleJpEn: "After Burner Kick's Angle (Side Special)", textJpEn: "Inputting down before using After Burner Kick, or inputting down right after the special move input, lets it be unleashed diagonally downward instead.", titlePt: "O Ângulo do After Burner Kick (Especial Lateral)", textPt: "Inputar baixo antes de usar o After Burner Kick, ou inputar baixo logo depois do input do golpe especial, permite lançá-lo na diagonal para baixo." },
  { titleEn: "[★☆☆] Witch Twist's Traits (Up Special)", titleJp: "ウィッチツイストの特性 【上必殺ワザ】", textJp: "このワザは１回使用した後に空中ジャンプをすると、２回目を出せるようになる。コンボや復帰に使える重要なワザ。", titleJpEn: "Witch Twist's Traits (Up Special)", textJpEn: "Performing a midair jump after using this move once allows it to be used a second time. An important move usable for combos or recovery.", titlePt: "As Características do Witch Twist (Especial Cima)", textPt: "Realizar um pulo aéreo depois de usar este golpe uma vez permite usá-lo uma segunda vez. Um golpe importante utilizável para combos ou recuperação." },
  { titleEn: "[★☆☆] Witch Twist's Angle (Up Special)", titleJp: "ウィッチツイストの角度 【上必殺ワザ】", textJp: "１回目と２回目では、ヒットした相手のふっとぶ角度が違う。状況によって追撃するワザを変えて、うまくコンボに組み込もう。", titleJpEn: "Witch Twist's Angle (Up Special)", textJpEn: "The launch angle of a hit opponent differs between the first and second use. Change the follow-up move depending on the situation to weave it well into combos.", titlePt: "O Ângulo do Witch Twist (Especial Cima)", textPt: "O ângulo de lançamento de um adversário atingido difere entre o primeiro e o segundo uso. Mude o golpe de acompanhamento de acordo com a situação para incorporá-lo bem em combos." },
  { titleEn: "[★☆☆] Witch Time's Effect (Down Special)", titleJp: "ウィッチタイムの効果 【下必殺ワザ】", textJp: "カウンターに成功すると、相手の動きをスローにする。相手の蓄積ダメージが多いほど、スローになる時間が延びていく。", titleJpEn: "Witch Time's Effect (Down Special)", textJpEn: "A successful counter slows down the opponent's movement. The more accumulated damage the opponent has, the longer the slowdown lasts.", titlePt: "O Efeito do Witch Time (Especial Baixo)", textPt: "Um contra-ataque bem-sucedido diminui o movimento do adversário. Quanto mais dano acumulado o adversário tiver, mais tempo a lentidão dura." },
  { titleEn: "[★☆☆] Witch Time Confirmation (Down Special)", titleJp: "ウィッチタイムの確認 【下必殺ワザ】", textJp: "ウィッチタイムの効果時間は、相手に表示された時計の針で確認できる。針が一周するまでの間に追撃しよう。", titleJpEn: "Confirming Witch Time (Down Special)", textJpEn: "Witch Time's remaining duration can be checked via the clock hand displayed over the opponent. Land a follow-up before the hand completes a full circle.", titlePt: "Confirmando o Witch Time (Especial Baixo)", textPt: "A duração restante do Witch Time pode ser verificada pelo ponteiro do relógio exibido sobre o adversário. Emende um acompanhamento antes que o ponteiro complete uma volta." },
  { titleEn: "[★☆☆] Witch Time's Traits (Down Special)", titleJp: "ウィッチタイムの特性 【下必殺ワザ】", textJp: "連続して出すほど成功時に相手にかかるスローの時間が短くなってしまう。乱発は控えてここぞという時に繰り出そう。", titleJpEn: "Witch Time's Traits (Down Special)", textJpEn: "The more it's used consecutively, the shorter the slowdown duration becomes on a successful hit. Avoid overusing it and save it for when it really counts.", titlePt: "As Características do Witch Time (Especial Baixo)", textPt: "Quanto mais é usado consecutivamente, mais curta a duração da lentidão se torna quando bem-sucedido. Evite usá-lo demais e reserve-o para quando realmente importar." },
  { titleEn: "[★★★] Witch Time and Projectiles (Down Special)", titleJp: "飛び道具にウィッチタイム 【下必殺ワザ】", textJp: "相手の飛び道具に対してカウンターを成功させると、相手との距離が遠く離れていなければ、スローにすることができる。", titleJpEn: "Witch Time and Projectiles (Down Special)", textJpEn: "Successfully countering an opponent's projectile can slow them down too, as long as they aren't too far away.", titlePt: "Witch Time e Projéteis (Especial Baixo)", textPt: "Contra-atacar com sucesso o projétil de um adversário também pode desacelerá-lo, desde que ele não esteja muito longe." },
  { titleEn: "[★☆☆] Infernal Climax (Final Smash)", titleJp: "大魔獣召喚 【最後の切りふだ】", textJp: "周囲をウィッチタイム状態にし、相手に攻撃を与え、クライマックスゲージを灯す。８つ灯るとゴモラを呼び出だせる。クライマックスゲージには、制限時間があるので注意。", titleJpEn: "Infernal Climax (Final Smash)", textJpEn: "Puts the surrounding area into a Witch Time state, and landing attacks on opponents lights up the Climax Gauge. Lighting all eight lets her summon Gomorrah. Be careful, as the Climax Gauge has a time limit.", titlePt: "Infernal Climax (Final Smash)", textPt: "Coloca a área ao redor em um estado de Witch Time, e acertar ataques nos adversários acende o Climax Gauge. Acender todos os oito permite convocar Gomorrah. Cuidado, pois o Climax Gauge tem um limite de tempo." },
  { titleEn: "[★☆☆] Infernal Climax Additional Damage (Final Smash)", titleJp: "大魔獣召喚時の追加ダメージ 【最後の切りふだ】", textJp: "ゴモラ召喚後もクライマックスゲージが表示され、攻撃ボタンの入力で追撃できる。８つゲージが灯れば、ダメージが追加。蓄積ダメージが１００％を超えれば、撃墜できる。", titleJpEn: "Additional Damage When Summoning Gomorrah (Final Smash)", textJpEn: "The Climax Gauge is still displayed even after summoning Gomorrah, and pressing the attack button lets you land follow-up hits. If all eight segments light up, extra damage is dealt. If the opponent's accumulated damage exceeds 100%, they can be KO'd.", titlePt: "Dano Adicional ao Convocar Gomorrah (Final Smash)", textPt: "O Climax Gauge continua exibido mesmo após convocar Gomorrah, e apertar o botão de ataque permite emendar acertos. Se todos os oito segmentos acenderem, dano extra é causado. Se o dano acumulado do adversário exceder 100%, ele pode ser nocauteado." },
  { titleEn: "[★☆☆] Launching with Consecutive Kicks (Side Tilt Attack)", titleJp: "連続キックで打ち上げ 【横強攻撃】", textJp: "攻撃ボタンを追加入力すると３連続のキック攻撃を出せる。３発目で打ち上げるので、すかさず空中での追撃を狙おう。", titleJpEn: "Launching with Consecutive Kicks (Side Tilt Attack)", textJpEn: "Inputting the attack button additional times unleashes a three-hit kick combo. The third kick launches the opponent, so aim for an immediate aerial follow-up.", titlePt: "Lançando com Chutes Consecutivos (Ataque Lateral)", textPt: "Inputar o botão de ataque vezes adicionais libera um combo de três chutes. O terceiro chute lança o adversário, então mire em um acompanhamento aéreo imediato." },
  { titleEn: "[★☆☆] Against Aerial Attacks (Up Tilt Attack)", titleJp: "対空ワザ 【上強攻撃】", textJp: "上方向を大きくカバーできる対空ワザ。地上のファイターに当てても浮かせられる。ほかの強攻撃と同様に、当てた後は追撃を狙える。", titleJpEn: "Anti-Air Move (Up Tilt Attack)", textJpEn: "An anti-air move that covers a wide area above her. It can also launch grounded fighters into the air. Like other tilt attacks, a follow-up can be aimed for after it connects.", titlePt: "Golpe Antiaéreo (Ataque Cima)", textPt: "Um golpe antiaéreo que cobre uma ampla área acima dela. Também pode lançar lutadores no chão para o ar. Como outros ataques direcionais, um acompanhamento pode ser mirado depois que acerta." },
  { titleEn: "[★☆☆] Kick Attack and Gun Fire (Down Tilt Attack)", titleJp: "キック攻撃と射撃 【下強攻撃】", textJp: "早く出せるワザで、相手を打ち上げるキック攻撃。ボタンの長押しで前後へ同時に射撃し、両手で銃を撃つ前方の威力が高い。", titleJpEn: "Kick Attack and Gun Fire (Down Tilt Attack)", textJpEn: "A quick-coming kick attack that launches the opponent. Holding down the button fires forward and backward simultaneously; the forward shots, fired with both hands, deal more damage.", titlePt: "Kick Attack e Gun Fire (Ataque Baixo)", textPt: "Um ataque de chute rápido que lança o adversário. Segurar o botão dispara para frente e para trás simultaneamente; os tiros para frente, disparados com as duas mãos, causam mais dano." },
  { titleEn: "[★☆☆] Stomp to Meteor (Down Smash Attack)", titleJp: "踏みつけでメテオ 【下スマッシュ攻撃】", textJp: "魔界から召喚した足での踏みつけ攻撃はメテオ効果があり、復帰阻止で狙うと強い。ガケで待てばプレッシャーを与えられる。", titleJpEn: "Stomp to Meteor (Down Smash Attack)", textJpEn: "A stomping attack with a foot summoned from the demon realm has a meteor effect, making it powerful when aimed to stop a recovery. Waiting at the ledge with it applies pressure.", titlePt: "Pisão até Meteoro (Ataque Smash Baixo)", textPt: "Um ataque de pisão com um pé convocado do reino demoníaco tem efeito meteoro, tornando-o poderoso quando usado para impedir uma recuperação. Esperar na borda com ele aplica pressão." },
  { titleEn: "[★☆☆] Consecutive Midair Attacks (Forward Air Attack)", titleJp: "空中で連続攻撃 【前空中攻撃】", textJp: "追加入力すると３発出せる空中の連続攻撃。復帰中の相手を追撃したり、長押し射撃を駆使したけん制攻撃でダメージを与えよう。", titleJpEn: "Consecutive Midair Attacks (Forward Air Attack)", textJpEn: "An aerial combo that can fire three shots with additional inputs. Follow up on opponents recovering, or deal damage with a hold-to-fire zoning attack.", titlePt: "Ataques Aéreos Consecutivos (Ataque Aéreo Frente)", textPt: "Um combo aéreo que pode disparar três tiros com inputs adicionais. Emende em adversários se recuperando, ou cause dano com um ataque de controle de área ao segurar o disparo." },
  { titleEn: "[★☆☆] Rapidly Descending Meteor (Down Air Attack)", titleJp: "急降下でメテオ 【下空中攻撃】", textJp: "垂直に急降下するキック。落下中は常に攻撃判定があり、足の先端は少しだけ攻撃力が高い。メテオ効果もある。", titleJpEn: "Rapidly Descending Meteor (Down Air Attack)", textJpEn: "A kick that drops straight down rapidly. There's always a hitbox while falling, and the tip of the foot deals slightly more damage. It also has a meteor effect.", titlePt: "Meteoro em Descida Rápida (Ataque Aéreo Baixo)", textPt: "Um chute que desce reto e rapidamente. Sempre há uma hitbox durante a queda, e a ponta do pé causa um pouco mais de dano. Também tem efeito meteoro." },
  { titleEn: "[★☆☆] Tetsuzankou (Forward Throw)", titleJp: "鉄山靠 【前投げ】", textJp: "鉄山靠と言えば、『バーチャファイター』シリーズのアキラの得意技。前投げ、鉄山靠でたまに出る「十年早いんだよ！」は、アキラの決めゼリフ。", titleJpEn: "Tetsuzankou (Forward Throw)", textJpEn: "Speaking of Tetsuzankou, it's Akira's signature move from the \"Virtua Fighter\" series. \"You're ten years too early!\", occasionally heard during the forward throw's Tetsuzankou, is Akira's signature catchphrase.", titlePt: "Tetsuzankou (Arremesso Frente)", textPt: "Falando em Tetsuzankou, é o golpe característico do Akira da série \"Virtua Fighter\". \"Você é dez anos jovem demais!\", ocasionalmente ouvido durante o Tetsuzankou do arremesso frente, é a frase de efeito característica do Akira." },
  { titleEn: "[★★☆] Hold Attack to Keep Firing", titleJp: "攻撃の長押し射撃", textJp: "全ての通常ワザと一部必殺ワザは、ワザを出した後にそのままボタンを押していると、追加射撃ができる。", titleJpEn: "Holding the Attack Button to Keep Firing", textJpEn: "All standard moves and some special moves allow additional shots to be fired if the button is kept held down after the move comes out.", titlePt: "Segurando o Ataque para Continuar Atirando", textPt: "Todos os golpes padrão e alguns golpes especiais permitem disparar tiros adicionais se o botão for mantido pressionado depois que o golpe sai." },
  { titleEn: "[★★☆] Hold Attack to Steal KO", titleJp: "長押し射撃で横取り", textJp: "空振りした攻撃でも出せるので、追加射撃だけを狙っても良い。ふっとばされて撃墜しそうな相手に当てれば横取りも狙える。", titleJpEn: "Stealing a KO with Held-Down Fire", textJpEn: "Since it can be performed even if the attack whiffs, it's fine to aim purely for the additional shots. Hitting an opponent who's about to be KO'd while launched can even steal the finish.", titlePt: "Roubando um Nocaute com o Tiro Segurado", textPt: "Como pode ser realizado mesmo se o ataque errar, tudo bem mirar apenas nos tiros adicionais. Acertar um adversário que está prestes a ser nocauteado enquanto é lançado pode até roubar o acabamento." },
  { titleEn: "[★☆☆] Bat Within", titleJp: "バットウィズイン", textJp: "各種緊急回避や下必殺ワザの途中で攻撃を受けると、コウモリに変身してワザのダメージを半減する。", titleJpEn: "Bat Within", textJpEn: "If she's hit during any dodge or partway through her Down Special, she transforms into a swarm of bats, halving the move's damage.", titlePt: "Bat Within", textPt: "Se ela for atingida durante qualquer esquiva ou no meio do especial baixo, ela se transforma em um enxame de morcegos, reduzindo o dano do golpe pela metade." },
  { titleEn: "[★★☆] Filling the Witch Time Gauge", titleJp: "効率よくウィッチタイムゲージをためる", textJp: "最後の切りふだ中のウィッチタイムは、攻撃を当てた分だけゲージがたまる。１人を集中して狙うと、ふっとんで攻撃を当てにくくなるので、大勢を狙うとよい。", titleJpEn: "Efficiently Filling the Witch Time Gauge", textJpEn: "During Witch Time in the Final Smash, the gauge fills based on how many attacks connect. Focusing on a single opponent makes it harder to keep hitting them once they're launched away, so it's better to target multiple opponents.", titlePt: "Enchendo o Witch Time Gauge com Eficiência", textPt: "Durante o Witch Time no Final Smash, o medidor enche com base em quantos ataques acertam. Focar em um único adversário torna mais difícil continuar acertando-o depois que é lançado para longe, então é melhor mirar em múltiplos adversários." },
];

async function main() {
  const bayonetta = await db.fighter.findFirst({
    where: { name: "Bayonetta" },
    select: {
      id: true,
      bios: { select: { id: true, smashGameVersion: true } },
      moves: { select: { id: true, smashGameVersion: true, order: true } },
      tips: { select: { id: true, titleEn: true } },
    },
  });
  if (!bayonetta) { console.log("Bayonetta not found"); return; }

  await db.fighter.update({
    where: { id: bayonetta.id },
    data: {
      curatorOverviewEn: "Bayonetta is one of the most technical fighters in the game, built around holding the attack button after nearly any move to fire additional bullets — chip damage, zoning, and even stealing a KO from a launched opponent who thinks they're safe. Witch Time turns a well-timed counter into a devastating window where the opponent moves in slow motion, though its duration shrinks with overuse, demanding patience over spam. After Burner Kick and Witch Twist can each be used twice for extended aerial combos and long-distance recovery, letting her stay airborne and combo-heavy far longer than most of the cast. Her Final Smash, Infernal Climax, rewards spreading damage across multiple opponents rather than tunnel-visioning one target. Bayonetta demands real technical investment — mastering her rewards players with some of the flashiest, most combo-dense play in all of Smash.",
      curatorOverviewPt: "Bayonetta é uma das lutadoras mais técnicas do jogo, construída em torno de segurar o botão de ataque depois de quase qualquer golpe para disparar balas adicionais — dano residual, controle de área, e até roubar um nocaute de um adversário lançado que acha que está seguro. Witch Time transforma um contra-ataque bem cronometrado em uma janela devastadora onde o adversário se move em câmera lenta, embora sua duração diminua com o uso excessivo, exigindo paciência em vez de spam. After Burner Kick e Witch Twist podem cada um ser usados duas vezes para combos aéreos estendidos e recuperação de longa distância, permitindo que ela permaneça no ar e faça combos por muito mais tempo do que a maioria do elenco. Seu Final Smash, Infernal Climax, recompensa distribuir dano entre múltiplos adversários em vez de focar obsessivamente em um único alvo. Bayonetta exige um investimento técnico real — dominá-la recompensa jogadores com um dos estilos de jogo mais estilosos e densos em combos de todo o Smash.",
      curatorOverviewJp: "ベヨネッタはゲーム屈指のテクニカルなファイターで、ほぼどのワザの後でも攻撃ボタンを長押しして追加の銃弾を発射することを軸に組み立てられている――削りダメージ、けん制、そして安全だと思っている撃墜寸前の相手からの横取りまで可能だ。「ウィッチタイム」は、タイミングの良いカウンターを、相手がスローモーションで動く強烈な隙に変えるが、乱発すると効果時間が縮んでいくため、連発よりも忍耐が求められる。「アフターバーナーキック」と「ウィッチツイスト」はそれぞれ２回使うことができ、空中コンボの延長や長距離復帰に使え、他の多くのファイターよりもはるかに長く空中に留まり、コンボ主体で戦うことができる。最後の切りふだ「大魔獣召喚」は、１体の相手に固執するのではなく、複数の相手にダメージを分散させることに応える。ベヨネッタは本物の技術的投資を要求するファイターであり、使いこなせば、スマブラ全体でも屈指の華やかでコンボ密度の高いプレイを楽しめる。",
      curatorOverviewJpEn: "Bayonetta is one of the most technical fighters in the game, built around holding the attack button after almost any move to fire additional bullets — chip damage, zoning, and even stealing a KO from an opponent about to be launched who thinks they're safe. \"Witch Time\" turns a well-timed counter into a devastating window where the opponent moves in slow motion, but overusing it shrinks the effect's duration, demanding patience over spam. \"After Burner Kick\" and \"Witch Twist\" can each be used twice, enabling extended aerial combos and long-distance recovery, letting her stay airborne and combo-focused far longer than most other fighters. Her Final Smash, \"Infernal Climax,\" rewards spreading damage across multiple opponents rather than fixating on a single target. Bayonetta demands genuine technical investment — mastering her lets you enjoy some of the flashiest, most combo-dense play in all of Smash.",
    },
  });
  console.log("✅ Curator Overview (4 langs)");

  for (const [version, data] of Object.entries(BIO_PT_JPEN)) {
    const bio = bayonetta.bios.find(b => b.smashGameVersion === version);
    if (!bio) continue;
    await db.fighterBio.update({ where: { id: bio.id }, data: { contentPt: data.pt, contentJpEn: data.jpEn } });
    console.log(`✅ Bio [${version}]: PT+JpEn adicionados`);
  }

  const move = bayonetta.moves.find(m => m.smashGameVersion === "SSB4" && m.order === 0);
  if (move) {
    const en = "Using the Side Special in midair unleashes \"After Burner Kick,\" a diagonal upward lunge. Inputting down right before the kick comes out turns it into a rapid descent attack, so use whichever suits the situation. This move can be used one more time after hitting an opponent in the air. Since it can be worked into combos with other moves, it's well-suited for stylish, continuous aerial attacks while flying gracefully through the air. Bayonetta 2009/10 (Wii U) Bayonetta 2 (2014/09)";
    await db.fighterMove.update({
      where: { id: move.id },
      data: {
        descEn: en, descJpEn: en,
        descPt: "Usar o especial lateral no ar libera o \"After Burner Kick\", uma investida diagonal para cima. Inputar para baixo logo antes do chute sair o transforma em um ataque de descida rápida, então use o que combinar com a situação. Este golpe pode ser usado mais uma vez depois de acertar um adversário no ar. Como pode ser incorporado a combos com outros golpes, é adequado para ataques aéreos contínuos e estilosos enquanto voa graciosamente pelo ar. Bayonetta 2009/10 (Wii U) Bayonetta 2 (2014/09)",
      },
    });
    console.log("✅ Move [SSB4] EX: EN+PT+JpEn adicionados");
  }

  let updated = 0;
  for (const data of TIPS) {
    const tip = bayonetta.tips.find(t => t.titleEn === data.titleEn);
    if (!tip) { console.log(`  ⚠️  Tip não encontrada: "${data.titleEn}"`); continue; }
    await db.fighterTip.update({
      where: { id: tip.id },
      data: {
        titleJp: data.titleJp, textJp: data.textJp,
        titleJpEn: data.titleJpEn, textJpEn: data.textJpEn,
        titlePt: data.titlePt, textPt: data.textPt,
      },
    });
    updated++;
  }
  console.log(`✅ ${updated}/${TIPS.length} tips atualizadas`);

  // Nenhum timing de vídeo novo fornecido pelo usuário desta vez — dados existentes mantidos.

  await db.$disconnect();
}
main().catch(console.error);
