import { db } from "../../lib/db";

const TIPS = [
  {
    titleEn: "[★☆☆] In Their Series",
    titleJp: "原作では",
    textJp: "広大な『Minecraft』の世界を冒険するプレイヤーの化身。洞窟を探検したり、建物を建てたり、村人と取引したり、何をするかはプレイヤー次第。",
    titleJpEn: "In the Original Game",
    textJpEn: "An avatar for the player to explore the vast world of Minecraft. Exploring caves, building structures, trading with villagers — what to do is entirely up to the player.",
    titlePt: "No Jogo Original",
    textPt: "Um avatar para o jogador explorar o vasto mundo de Minecraft. Explorar cavernas, construir estruturas, negociar com aldeões — o que fazer fica totalmente a critério do jogador.",
  },
  {
    titleEn: "[★☆☆] Zombies from the Series",
    titleJp: "原作でのゾンビ",
    textJp: "7Pカラーのゾンビは、暗がりから現れ、人間を見つけると襲いかかる。しかし、日光を浴びると燃え上がって消滅してしまう。",
    titleJpEn: "Zombies in the Original Game",
    textJpEn: "The 7P color represents the Zombie, which emerges from the darkness and attacks when it spots a human. However, it bursts into flame and disappears when exposed to sunlight.",
    titlePt: "Zumbis no Jogo Original",
    textPt: "A cor 7P representa o Zumbi, que surge da escuridão e ataca ao avistar um humano. Porém, ele pega fogo e desaparece quando exposto à luz do sol.",
  },
  {
    titleEn: "[★☆☆] Enderman from the Series",
    titleJp: "原作でのエンダーマン",
    textJp: "8Pカラーは、ジ・エンドの住人エンダーマン。普段はテレポートしつつ静かにブロックを運んでいることが多いが、目が合った瞬間、プレイヤーを攻撃してくる強敵と化す。",
    titleJpEn: "Enderman in the Original Game",
    textJpEn: "The 8P color represents the Enderman, a resident of The End. It's normally seen quietly teleporting around while carrying blocks, but the moment eye contact is made, it turns into a formidable foe that attacks the player.",
    titlePt: "Enderman no Jogo Original",
    textPt: "A cor 8P representa o Enderman, um habitante do The End. Normalmente é visto teleportando-se silenciosamente enquanto carrega blocos, mas no instante em que o contato visual é feito, ele se torna um inimigo formidável que ataca o jogador.",
  },
  {
    titleEn: "[★☆☆] Tools and Moves",
    titleJp: "道具とワザ",
    textJp: "ワザによって、剣、斧、シャベル、ツルハシを使い分ける。どの道具もしばらく使うと壊れ、その道具を使ったワザの威力が下がる。",
    titleJpEn: "Tools and Moves",
    textJpEn: "Depending on the move, Steve uses a sword, axe, shovel, or pickaxe. Every tool breaks after being used for a while, lowering the power of moves that use it.",
    titlePt: "Ferramentas e Golpes",
    textPt: "Dependendo do golpe, Steve usa uma espada, machado, pá ou picareta. Toda ferramenta quebra depois de um tempo de uso, reduzindo o poder dos golpes que a utilizam.",
  },
  {
    titleEn: "[★☆☆] Materials and Moves",
    titleJp: "素材とワザ",
    textJp: "ワザによっては、素材を使う。必要な素材を持っていないと、失敗したり、威力が落ちたりする。常に手持ちの素材に気を配ろう。",
    titleJpEn: "Materials and Moves",
    textJpEn: "Some moves use materials. Without the necessary materials on hand, a move may fail or have reduced power. Always keep an eye on the materials Steve is holding.",
    titlePt: "Materiais e Golpes",
    textPt: "Alguns golpes usam materiais. Sem os materiais necessários em mãos, um golpe pode falhar ou ter o poder reduzido. Sempre fique de olho nos materiais que Steve está carregando.",
  },
  {
    titleEn: "[★☆☆] Mine (Neutral Special)",
    titleJp: "採掘 【通常必殺ワザ】",
    textJp: "地上でボタンを長押しすると、足元の床やカベを掘って、素材を入手できる。掘る場所の材質によって、掘る早さや、入手しやすい素材が変わる。",
    titleJpEn: "Mine (Neutral Special)",
    textJpEn: "Holding the button down on the ground digs into the floor or wall beneath Steve, obtaining materials. The speed of digging and the materials likely to be obtained change depending on what's being dug into.",
    titlePt: "Mine (Especial Neutro)",
    textPt: "Segurar o botão no chão escava o piso ou a parede sob Steve, obtendo materiais. A velocidade de escavação e os materiais prováveis de serem obtidos mudam dependendo do que está sendo escavado.",
  },
  {
    titleEn: "[★☆☆] Mineable Materials (Neutral Special)",
    titleJp: "採掘できる素材 【通常必殺ワザ】",
    textJp: "素材は、土＞木材＞石＞鉄＞レッドストーン＞金＞ダイヤモンドの順で出やすい。ステージの材質によっては、土の代わりに氷、砂、ウールが手に入る。",
    titleJpEn: "Mineable Materials (Neutral Special)",
    textJpEn: "Materials are more likely to appear in this order: dirt, wood, stone, iron, redstone, gold, diamond. Depending on the stage's material, ice, sand, or wool may be obtained instead of dirt.",
    titlePt: "Materiais Mineráveis (Especial Neutro)",
    textPt: "Os materiais têm mais chance de aparecer nesta ordem: terra, madeira, pedra, ferro, redstone, ouro, diamante. Dependendo do material do cenário, gelo, areia ou lã podem ser obtidos no lugar da terra.",
  },
  {
    titleEn: "[★☆☆] High-Quality Mineable Materials (Neutral Special)",
    titleJp: "高品質素材の採掘 【通常必殺ワザ】",
    textJp: "鉄、金、レッドストーン、ダイヤモンドは、どんな材質からでも、たまに入手できる。",
    titleJpEn: "High-Quality Mineable Materials (Neutral Special)",
    textJpEn: "Iron, gold, redstone, and diamond can occasionally be obtained from any material, regardless of what's being dug into.",
    titlePt: "Materiais de Alta Qualidade Mineráveis (Especial Neutro)",
    textPt: "Ferro, ouro, redstone e diamante podem ocasionalmente ser obtidos de qualquer material, independentemente do que está sendo escavado.",
  },
  {
    titleEn: "[★☆☆] Mining and the Material Gauge (Neutral Special)",
    titleJp: "採掘と素材ゲージ 【通常必殺ワザ】",
    textJp: "手持ちの素材は、蓄積ダメージの近くにゲージとして表示される。ただし、金とダイヤモンドはその横に別に表示される。また、レッドストーンは表示されない。",
    titleJpEn: "Mining and the Material Gauge (Neutral Special)",
    textJpEn: "The materials Steve is holding are displayed as a gauge near his damage percentage. However, gold and diamond are displayed separately next to it, and redstone isn't displayed at all.",
    titlePt: "Mineração e o Medidor de Materiais (Especial Neutro)",
    textPt: "Os materiais que Steve está carregando são exibidos como um medidor perto da porcentagem de dano dele. Porém, ouro e diamante são exibidos separadamente ao lado, e redstone não é exibido.",
  },
  {
    titleEn: "[★☆☆] Quality of Mined Material (Neutral Special)",
    titleJp: "採掘と材質 【通常必殺ワザ】",
    textJp: "より硬い材質の床やカベほど、より良い素材を入手しやすい。ただし、素材を入手するまでに、より時間がかかる。",
    titleJpEn: "Mining and Material Type (Neutral Special)",
    textJpEn: "The harder the floor or wall material, the easier it is to obtain better materials. However, it also takes longer to obtain them.",
    titlePt: "Mineração e Tipo de Material (Especial Neutro)",
    textPt: "Quanto mais duro o material do piso ou da parede, mais fácil é obter materiais melhores. Porém, também leva mais tempo para obtê-los.",
  },
  {
    titleEn: "[★☆☆] Mining Limits (Neutral Special)",
    titleJp: "採掘の限界 【通常必殺ワザ】",
    textJp: "素材を持てる数には限界がある。また、珍しい素材ほど、持てる数が少ない。上限を超えて採掘した場合は、持てなくなった素材を捨てる。",
    titleJpEn: "Mining Limits (Neutral Special)",
    textJpEn: "There's a limit to how many materials Steve can hold, and the rarer the material, the fewer he can carry. If he mines beyond that limit, the materials he can no longer hold are discarded.",
    titlePt: "Limites de Mineração (Especial Neutro)",
    textPt: "Há um limite de quantos materiais Steve pode carregar, e quanto mais raro o material, menos ele pode carregar. Se ele minerar além desse limite, os materiais que ele não puder mais carregar são descartados.",
  },
  {
    titleEn: "[★☆☆] Mining Tools (Neutral Special)",
    titleJp: "採掘と道具 【通常必殺ワザ】",
    textJp: "採掘の道具は、掘る床やカベの材質によって切り替わる。使う道具が壊れていると、掘る速度が落ちるため注意。",
    titleJpEn: "Mining Tools (Neutral Special)",
    textJpEn: "The mining tool switches depending on the material of the floor or wall being dug. Be careful — if the tool being used is broken, the digging speed drops.",
    titlePt: "Ferramentas de Mineração (Especial Neutro)",
    textPt: "A ferramenta de mineração muda dependendo do material do piso ou da parede sendo escavado. Cuidado — se a ferramenta usada estiver quebrada, a velocidade de escavação cai.",
  },
  {
    titleEn: "[★☆☆] Mining, Tools, and Quality (Neutral Special)",
    titleJp: "採掘と道具の品質 【通常必殺ワザ】",
    textJp: "道具の品質は、ダイヤモンド＞金＞鉄＞石＞木材の順で良い。金以外は、おおむね品質が良いほど壊れにくく、採掘が早い。",
    titleJpEn: "Mining, Tools, and Quality (Neutral Special)",
    textJpEn: "Tool quality, from best to worst, goes diamond, gold, iron, stone, wood. Except for gold, the better the quality generally, the less likely a tool is to break and the faster it mines.",
    titlePt: "Mineração, Ferramentas e Qualidade (Especial Neutro)",
    textPt: "A qualidade das ferramentas, da melhor para a pior, segue diamante, ouro, ferro, pedra, madeira. Com exceção do ouro, quanto melhor a qualidade geralmente, menos provável a ferramenta é de quebrar e mais rápida ela minera.",
  },
  {
    titleEn: "[★☆☆] While Mining (Neutral Special)",
    titleJp: "採掘中の行動 【通常必殺ワザ】",
    textJp: "採掘中は攻撃できないが、前後への移動やジャンプは可能。前後に移動しながらでも採掘を続けられるが、ジャンプすると中断される。",
    titleJpEn: "While Mining (Neutral Special)",
    textJpEn: "Steve can't attack while mining, but he can still move forward and backward or jump. He can keep mining while moving forward and backward, but jumping interrupts it.",
    titlePt: "Durante a Mineração (Especial Neutro)",
    textPt: "Steve não pode atacar enquanto minera, mas ainda pode se mover para frente e para trás ou pular. Ele pode continuar minerando enquanto se move para frente e para trás, mas pular interrompe a mineração.",
  },
  {
    titleEn: "[★☆☆] Mining on Battlefield-Form Stages (Neutral Special)",
    titleJp: "戦場化ステージでの採掘 【通常必殺ワザ】",
    textJp: "戦場化や終点化されたステージでは、採掘で入手できる素材の種類と順番が、全ステージ共通であらかじめ決まっている。",
    titleJpEn: "Mining on Battlefield-Form Stages (Neutral Special)",
    textJpEn: "On stages transformed into Battlefield or Final Destination form, the type and order of materials obtainable through mining are predetermined and common to all such stages.",
    titlePt: "Mineração em Cenários no Formato Battlefield (Especial Neutro)",
    textPt: "Em cenários transformados no formato Battlefield ou Final Destination, o tipo e a ordem dos materiais obtidos pela mineração são predeterminados e comuns a todos esses cenários.",
  },
  {
    titleEn: "[★☆☆] Craft (Neutral Special)",
    titleJp: "クラフト 【通常必殺ワザ】",
    textJp: "作業台の前でボタンを押すと、手持ちの素材を使って、道具の製作や強化、修理を行う。",
    titleJpEn: "Craft (Neutral Special)",
    textJpEn: "Pressing the button in front of a crafting table uses the materials Steve is holding to make, upgrade, or repair tools.",
    titlePt: "Craft (Especial Neutro)",
    textPt: "Pressionar o botão em frente a uma mesa de trabalho usa os materiais que Steve está carregando para fazer, melhorar ou consertar ferramentas.",
  },
  {
    titleEn: "[★☆☆] Crafting Tools (Neutral Special)",
    titleJp: "クラフトで製作 【通常必殺ワザ】",
    textJp: "壊れた道具がある時にクラフトすると、できるだけ品質が良い道具を新たに製作する。より良い素材が使われた場合、他の道具も同じ素材で強化される。",
    titleJpEn: "Crafting Tools (Neutral Special)",
    textJpEn: "If a tool is broken, crafting will make a new one of the best quality possible. If a better material is used, the other tools are also upgraded with the same material.",
    titlePt: "Fabricando Ferramentas (Especial Neutro)",
    textPt: "Se uma ferramenta estiver quebrada, o craft fará uma nova da melhor qualidade possível. Se um material melhor for usado, as outras ferramentas também são melhoradas com o mesmo material.",
  },
  {
    titleEn: "[★☆☆] Using Craft to Upgrade (Neutral Special)",
    titleJp: "クラフトで強化 【通常必殺ワザ】",
    textJp: "より品質が良い道具を作れる素材を持っている時は、クラフトで道具を強化できる。すべての道具が一度に強化される。",
    titleJpEn: "Using Craft to Upgrade (Neutral Special)",
    textJpEn: "When Steve has materials that can make a higher-quality tool, crafting can upgrade his tools. All of his tools are upgraded at once.",
    titlePt: "Usando o Craft para Melhorar (Especial Neutro)",
    textPt: "Quando Steve tem materiais que podem fazer uma ferramenta de qualidade superior, o craft pode melhorar suas ferramentas. Todas as ferramentas dele são melhoradas de uma vez.",
  },
  {
    titleEn: "[★☆☆] Using Craft to Repair (Neutral Special)",
    titleJp: "クラフトで修理 【通常必殺ワザ】",
    textJp: "壊れそうな道具がある時は、道具の材質と同じ素材を持っていればクラフトで修理できる。壊れた後で製作するより、素早く行える。",
    titleJpEn: "Using Craft to Repair (Neutral Special)",
    textJpEn: "If a tool is about to break, crafting can repair it as long as Steve has a material matching that tool's material. This can be done faster than making a new tool after it breaks.",
    titlePt: "Usando o Craft para Consertar (Especial Neutro)",
    textPt: "Se uma ferramenta estiver prestes a quebrar, o craft pode consertá-la desde que Steve tenha um material igual ao material daquela ferramenta. Isso pode ser feito mais rápido do que fazer uma ferramenta nova depois que ela quebra.",
  },
  {
    titleEn: "[★☆☆] Canceling Craft (Neutral Special)",
    titleJp: "クラフトの中断 【通常必殺ワザ】",
    textJp: "クラフト中、ジャンプやシールド、回避を行うか、攻撃ボタンで、ワザをキャンセルできる。キャンセルした場合、素材は減らない。",
    titleJpEn: "Canceling Craft (Neutral Special)",
    textJpEn: "During crafting, jumping, shielding, dodging, or pressing the attack button will cancel the move. If canceled, no materials are consumed.",
    titlePt: "Cancelando o Craft (Especial Neutro)",
    textPt: "Durante o craft, pular, usar o escudo, esquivar, ou pressionar o botão de ataque cancela o golpe. Se cancelado, nenhum material é consumido.",
  },
  {
    titleEn: "[★☆☆] Crafting with Gold (Neutral Special)",
    titleJp: "金でクラフト 【通常必殺ワザ】",
    textJp: "金の道具は、すべての道具の中で最も壊れやすいが、採掘やワザを出すまでの時間が最も早い。",
    titleJpEn: "Crafting with Gold (Neutral Special)",
    textJpEn: "Gold tools are the most prone to breaking of all tools, but they're the fastest at mining and at bringing out moves.",
    titlePt: "Craftando com Ouro (Especial Neutro)",
    textPt: "As ferramentas de ouro são as mais propensas a quebrar entre todas as ferramentas, mas são as mais rápidas para minerar e desferir golpes.",
  },
  {
    titleEn: "[★☆☆] Crafting with Diamond (Neutral Special)",
    titleJp: "ダイヤモンドでクラフト 【通常必殺ワザ】",
    textJp: "ダイヤモンドの道具は強力だが、他の道具に比べて、クラフトに時間がかかる。",
    titleJpEn: "Crafting with Diamond (Neutral Special)",
    textJpEn: "Diamond tools are powerful, but they take longer to craft compared to other tools.",
    titlePt: "Craftando com Diamante (Especial Neutro)",
    textPt: "As ferramentas de diamante são poderosas, mas levam mais tempo para craftar em comparação com outras ferramentas.",
  },
  {
    titleEn: "[★☆☆] Moving the Crafting Table (Neutral Special)",
    titleJp: "作業台の呼び出し 【通常必殺ワザ】",
    textJp: "シールド中に必殺ワザボタンを押すと、素材を使って、近くに作業台を置き直せる。素材は、木材、石、鉄の順で使われる。",
    titleJpEn: "Calling the Crafting Table (Neutral Special)",
    textJpEn: "Pressing the special-move button while shielding uses materials to reposition the crafting table nearby. Materials are used in the order wood, stone, iron.",
    titlePt: "Chamando a Mesa de Trabalho (Especial Neutro)",
    textPt: "Pressionar o botão de especial enquanto usa o escudo utiliza materiais para reposicionar a mesa de trabalho por perto. Os materiais são usados na ordem madeira, pedra, ferro.",
  },
  {
    titleEn: "[★☆☆] Using Create Block (Neutral Special)",
    titleJp: "ブロック生成 【通常必殺ワザ】",
    textJp: "空中でボタンを押すと、手持ちの素材を使い、足元にブロックを作って置く。ボタンを押したまま移動やジャンプをすると、続けて置ける。",
    titleJpEn: "Using Create Block (Neutral Special)",
    textJpEn: "Pressing the button in midair uses the materials Steve is holding to create and place a block beneath his feet. Holding the button while moving or jumping lets him keep placing more.",
    titlePt: "Usando o Create Block (Especial Neutro)",
    textPt: "Pressionar o botão no ar usa os materiais que Steve está carregando para criar e colocar um bloco sob seus pés. Segurar o botão enquanto se move ou pula permite colocar mais blocos continuamente.",
  },
  {
    titleEn: "[★☆☆] Materials and Create Block (Neutral Special)",
    titleJp: "ブロック生成の素材 【通常必殺ワザ】",
    textJp: "ブロックの素材は、土などのより入手しやすいものから、木材、石、鉄の順で使われる。素材によって、ブロックの壊れにくさが異なる。",
    titleJpEn: "Materials and Create Block (Neutral Special)",
    textJpEn: "Block materials are used starting with the easiest to obtain, like dirt, followed by wood, stone, and iron in that order. The block's durability varies depending on the material used.",
    titlePt: "Materiais e o Create Block (Especial Neutro)",
    textPt: "Os materiais do bloco são usados começando pelos mais fáceis de obter, como terra, seguidos por madeira, pedra e ferro, nessa ordem. A durabilidade do bloco varia dependendo do material usado.",
  },
  {
    titleEn: "[★☆☆] Block Limits (Neutral Special)",
    titleJp: "ブロック生成の上限 【通常必殺ワザ】",
    textJp: "一度に作って置けるブロックの数には、限りがある。上限より多く置こうとすると、古いブロックから壊れていく。",
    titleJpEn: "Block Limits (Neutral Special)",
    textJpEn: "There's a limit to how many blocks can be created and placed at once. If Steve tries to place more than that limit, the oldest blocks will start breaking.",
    titlePt: "Limites de Blocos (Especial Neutro)",
    textPt: "Há um limite de quantos blocos podem ser criados e colocados de uma vez. Se Steve tentar colocar mais do que esse limite, os blocos mais antigos começam a quebrar.",
  },
  {
    titleEn: "[★☆☆] Block Rules (Neutral Special)",
    titleJp: "ブロック生成の位置 【通常必殺ワザ】",
    textJp: "画面外に近い場所では、ブロックを置くことができない。置いたブロックが点滅していたら、限界が近い証。",
    titleJpEn: "Where Blocks Can Be Placed (Neutral Special)",
    textJpEn: "Blocks can't be placed near the edge of the screen. If a placed block is blinking, that's a sign the limit is about to be reached.",
    titlePt: "Onde os Blocos Podem Ser Colocados (Especial Neutro)",
    textPt: "Blocos não podem ser colocados perto da borda da tela. Se um bloco colocado estiver piscando, isso é um sinal de que o limite está prestes a ser atingido.",
  },
  {
    titleEn: "[★☆☆] Overlapping Blocks (Neutral Special)",
    titleJp: "重ねてブロック生成 【通常必殺ワザ】",
    textJp: "既にブロックを置いた場所でさらにワザを使うと、古いブロックを壊して新たに置くことができる。",
    titleJpEn: "Overlapping Blocks (Neutral Special)",
    textJpEn: "Using the move again on a spot where a block was already placed will destroy the old block and place a new one.",
    titlePt: "Sobrepondo Blocos (Especial Neutro)",
    textPt: "Usar o golpe novamente num local onde um bloco já foi colocado destrói o bloco antigo e coloca um novo.",
  },
  {
    titleEn: "[★☆☆] Destroying Blocks (Neutral Special)",
    titleJp: "生成したブロックの破壊 【通常必殺ワザ】",
    textJp: "ワザで置いたブロックは、時間と共に壊れていく。また、攻撃を受けたり、ファイターが上に乗ったり、下からぶつかったりすると、より早く壊れる。",
    titleJpEn: "Destroying Created Blocks (Neutral Special)",
    textJpEn: "Blocks placed with this move break down over time. They also break faster if attacked, if a fighter stands on top of them, or if something hits them from below.",
    titlePt: "Destruindo Blocos Criados (Especial Neutro)",
    textPt: "Blocos colocados com esse golpe se deterioram com o tempo. Eles também quebram mais rápido se atacados, se um lutador ficar em cima deles, ou se algo os atingir por baixo.",
  },
  {
    titleEn: "[★☆☆] Mining Blocks (Neutral Special)",
    titleJp: "生成したブロックの採掘 【通常必殺ワザ】",
    textJp: "ワザで置いたブロックも掘ることができるが、壊れるだけで、素材は入手できない。",
    titleJpEn: "Mining Created Blocks (Neutral Special)",
    textJpEn: "Blocks placed with this move can also be mined, but doing so only destroys them without yielding any materials.",
    titlePt: "Minerando Blocos Criados (Especial Neutro)",
    textPt: "Blocos colocados com esse golpe também podem ser minerados, mas isso apenas os destrói, sem gerar materiais.",
  },
  {
    titleEn: "[★☆☆] Creating Blocks while Mining (Neutral Special)",
    titleJp: "採掘とブロック生成 【通常必殺ワザ】",
    textJp: "採掘中、ボタンを押したままジャンプすると、足元にブロックを置ける。",
    titleJpEn: "Creating Blocks While Mining (Neutral Special)",
    textJpEn: "While mining, jumping while still holding down the button lets Steve place a block beneath his feet.",
    titlePt: "Criando Blocos Durante a Mineração (Especial Neutro)",
    textPt: "Enquanto minera, pular enquanto ainda segura o botão permite que Steve coloque um bloco sob seus pés.",
  },
  {
    titleEn: "[★☆☆] Minecart (Side Special)",
    titleJp: "トロッコ 【横必殺ワザ】",
    textJp: "鉄を使ってトロッコを作り、レールを敷いて突進する。ジャンプすると、トロッコから飛び出せる。空のトロッコは突進を続け、相手に当たると強制的に乗せて連れ去る。",
    titleJpEn: "Minecart (Side Special)",
    textJpEn: "Uses iron to create a minecart, laying rail and charging forward. Jumping lets Steve leap out of the minecart. An empty minecart keeps charging forward, and if it hits an opponent, it forces them aboard and carries them off.",
    titlePt: "Minecart (Especial Lateral)",
    textPt: "Usa ferro para criar um carrinho de mina, colocando trilhos e avançando. Pular permite que Steve salte para fora do carrinho. Um carrinho vazio continua avançando, e se atingir um oponente, o força a embarcar e o carrega.",
  },
  {
    titleEn: "[★☆☆] Stuck in the Minecart (Side Special)",
    titleJp: "トロッコでの拘束時間 【横必殺ワザ】",
    textJp: "トロッコに乗せられた相手は、蓄積ダメージが大きいほど長く拘束される。レバガチャすると、少し早く抜け出せる。",
    titleJpEn: "Restraint Time in the Minecart (Side Special)",
    textJpEn: "An opponent forced into the minecart is restrained longer the higher their accumulated damage. Mashing the stick and buttons lets them escape a little sooner.",
    titlePt: "Tempo de Retenção no Minecart (Especial Lateral)",
    textPt: "Um oponente forçado a embarcar no carrinho fica retido por mais tempo quanto maior for o dano acumulado dele. Apertar o direcional e os botões repetidamente permite que ele escape um pouco mais cedo.",
  },
  {
    titleEn: "[★★☆] Using Minecart Repeatedly (Side Special)",
    titleJp: "トロッコの連続使用 【横必殺ワザ】",
    textJp: "連続でトロッコを使い続けると、乗せた相手を拘束できる時間が少しずつ短くなる。",
    titleJpEn: "Using Minecart Repeatedly (Side Special)",
    textJpEn: "Using the minecart repeatedly in succession gradually shortens how long an opponent forced aboard can be restrained.",
    titlePt: "Usando o Minecart Repetidamente (Especial Lateral)",
    textPt: "Usar o carrinho repetidamente em sucessão diminui gradualmente por quanto tempo um oponente forçado a embarcar pode ser retido.",
  },
  {
    titleEn: "[★☆☆] Minecart on a Hill (Side Special)",
    titleJp: "坂道でのトロッコ 【横必殺ワザ】",
    textJp: "急な上り坂に差し掛かると、トロッコは減速し、やがて後退し始める。逆に、下り坂では加速する。",
    titleJpEn: "Minecart on a Slope (Side Special)",
    textJpEn: "When it reaches a steep uphill slope, the minecart slows down and eventually starts moving backward. Conversely, it accelerates on a downhill slope.",
    titlePt: "Minecart numa Rampa (Especial Lateral)",
    textPt: "Ao chegar numa subida íngreme, o carrinho desacelera e eventualmente começa a se mover para trás. Por outro lado, ele acelera numa descida.",
  },
  {
    titleEn: "[★☆☆] Minecart and Powered Rails (Side Special)",
    titleJp: "トロッコと加速レール 【横必殺ワザ】",
    textJp: "レッドストーンと金を持っていると、加速レールを敷く。突進の速度が大きく上がり、坂も登れるようになる。",
    titleJpEn: "Minecart and Powered Rails (Side Special)",
    textJpEn: "If Steve has redstone and gold, he lays a powered rail. This greatly increases the charging speed and allows the minecart to climb slopes.",
    titlePt: "Minecart e Trilhos Energizados (Especial Lateral)",
    textPt: "Se Steve tiver redstone e ouro, ele coloca um trilho energizado. Isso aumenta muito a velocidade de avanço e permite que o carrinho suba rampas.",
  },
  {
    titleEn: "[★☆☆] Charge with Minecart and Powered Rail (Side Special)",
    titleJp: "トロッコで突進中の加速レール 【横必殺ワザ】",
    textJp: "突進中に必殺ワザボタンで、加速レールを敷いて加速することができる。ただし、レッドストーンと金を持っている必要がある。",
    titleJpEn: "Powered Rail While Charging in Minecart (Side Special)",
    textJpEn: "Pressing the special-move button while charging lets Steve lay a powered rail to accelerate. However, he needs to have redstone and gold to do so.",
    titlePt: "Trilho Energizado Durante o Avanço no Minecart (Especial Lateral)",
    textPt: "Pressionar o botão de especial durante o avanço permite que Steve coloque um trilho energizado para acelerar. Porém, ele precisa ter redstone e ouro para fazer isso.",
  },
  {
    titleEn: "[★☆☆] Reboarding the Minecart (Side Special)",
    titleJp: "トロッコへの再搭乗 【横必殺ワザ】",
    textJp: "トロッコから降りた後ジャンプして、走っているトロッコに上から乗ると、もう一度乗り直して走ることができる。ただし、乗り直せるのは２回まで。",
    titleJpEn: "Reboarding the Minecart (Side Special)",
    textJpEn: "After getting off the minecart, jumping and landing on top of the still-moving minecart lets Steve reboard and keep going. However, he can only reboard up to 2 times.",
    titlePt: "Reembarcando no Minecart (Especial Lateral)",
    textPt: "Depois de descer do carrinho, pular e aterrissar em cima do carrinho ainda em movimento permite que Steve reembarque e continue. Porém, ele só pode reembarcar até 2 vezes.",
  },
  {
    titleEn: "[★☆☆] Minecart Controls (Side Special)",
    titleJp: "トロッコ搭乗中の入力 【横必殺ワザ】",
    textJp: "トロッコ搭乗中、スティックを左右に倒すと、素材を使いレールを敷きながら移動できる。素材がなくなり、レールから落ちると、トロッコは止まってしまう。",
    titleJpEn: "Minecart Controls (Side Special)",
    textJpEn: "While aboard the minecart, tilting the stick left or right lets Steve move while using materials to lay rail. If materials run out and the cart falls off the rail, the minecart stops.",
    titlePt: "Controles do Minecart (Especial Lateral)",
    textPt: "Enquanto está a bordo do carrinho, inclinar o direcional para a esquerda ou direita permite que Steve se mova enquanto usa materiais para colocar trilhos. Se os materiais acabarem e o carrinho cair do trilho, ele para.",
  },
  {
    titleEn: "[★☆☆] Materials for Rails (Side Special)",
    titleJp: "レールの素材 【横必殺ワザ】",
    textJp: "レールを敷くたびに、素材が必要になる。素材は、土などのより入手しやすいものから、木材、石、鉄の順で使われる。",
    titleJpEn: "Materials for Rails (Side Special)",
    textJpEn: "Materials are needed each time rail is laid. Materials are used starting with the easiest to obtain, like dirt, followed by wood, stone, and iron in that order.",
    titlePt: "Materiais para Trilhos (Especial Lateral)",
    textPt: "Materiais são necessários toda vez que um trilho é colocado. Os materiais são usados começando pelos mais fáceis de obter, como terra, seguidos por madeira, pedra e ferro, nessa ordem.",
  },
  {
    titleEn: "[★☆☆] Destroying the Minecart (Side Special)",
    titleJp: "トロッコの破壊 【横必殺ワザ】",
    textJp: "トロッコは、一定以上のダメージを受けると壊れてしまう。壊したファイターがスティーブの場合は、トロッコから鉄素材を回収できる。",
    titleJpEn: "Destroying the Minecart (Side Special)",
    textJpEn: "The minecart breaks after taking a certain amount of damage. If Steve is the one who breaks it, he can recover iron materials from the minecart.",
    titlePt: "Destruindo o Minecart (Especial Lateral)",
    textPt: "O carrinho quebra depois de sofrer uma certa quantidade de dano. Se Steve for quem o quebrou, ele pode recuperar materiais de ferro do carrinho.",
  },
  {
    titleEn: "[★☆☆] Elytra (Up Special)",
    titleJp: "エリトラ 【上必殺ワザ】",
    textJp: "背中に装備したエリトラを広げ、横に向かって滑空する。滑空中にスティックを上下に倒すと、滑空の角度を調節し、軌道を変えられる。",
    titleJpEn: "Elytra (Up Special)",
    textJpEn: "Spreads the Elytra equipped on Steve's back, gliding sideways. Tilting the stick up or down while gliding adjusts the gliding angle, changing the trajectory.",
    titlePt: "Elytra (Especial Superior)",
    textPt: "Estende a Elytra equipada nas costas de Steve, planando de lado. Inclinar o direcional para cima ou para baixo durante o planeio ajusta o ângulo do planeio, mudando a trajetória.",
  },
  {
    titleEn: "[★☆☆] Elytra and Firework Rocket (Up Special)",
    titleJp: "エリトラとロケット花火 【上必殺ワザ】",
    textJp: "ワザの出始めは、ロケット花火に点火して、大きく加速する。ロケット花火での加速中は、ぶつかった相手に少しダメージを与えられる。",
    titleJpEn: "Elytra and Firework Rocket (Up Special)",
    textJpEn: "At the very start of the move, a Firework Rocket ignites, causing a large boost in speed. While accelerating from the Firework Rocket, Steve deals a small amount of damage to any opponent he collides with.",
    titlePt: "Elytra e Firework Rocket (Especial Superior)",
    textPt: "Bem no início do golpe, um Firework Rocket é acionado, causando um grande impulso de velocidade. Enquanto acelera com o Firework Rocket, Steve causa um pouco de dano a qualquer oponente com quem colidir.",
  },
  {
    titleEn: "[★☆☆] Cancel Elytra (Up Special)",
    titleJp: "エリトラの中断 【上必殺ワザ】",
    textJp: "滑空中、少し経った後でシールドボタンや攻撃ボタンを押すと、エリトラを外して落下し始める。落下中は、少しだけ前後に動ける。",
    titleJpEn: "Canceling Elytra (Up Special)",
    textJpEn: "After a short while of gliding, pressing the shield button or attack button removes the Elytra, and Steve starts falling. While falling, he can still move slightly forward and backward.",
    titlePt: "Cancelando a Elytra (Especial Superior)",
    textPt: "Depois de um curto período de planeio, pressionar o botão de escudo ou o botão de ataque remove a Elytra, e Steve começa a cair. Enquanto cai, ele ainda pode se mover um pouco para frente e para trás.",
  },
  {
    titleEn: "[★☆☆] Elytra's Time Limit (Up Special)",
    titleJp: "エリトラの時間制限 【上必殺ワザ】",
    textJp: "ワザを出してからしばらくすると、エリトラが自然に外れ、落下してしまう。大きなスキが生じるため、要注意。",
    titleJpEn: "Elytra's Time Limit (Up Special)",
    textJpEn: "After a while of using this move, the Elytra will naturally come off and Steve will fall. Be careful, since this leaves a large opening.",
    titlePt: "Limite de Tempo da Elytra (Especial Superior)",
    textPt: "Depois de um tempo usando esse golpe, a Elytra naturalmente se solta e Steve cai. Cuidado, pois isso deixa uma grande brecha.",
  },
  {
    titleEn: "[★☆☆] Crashing with Elytra (Up Special)",
    titleJp: "エリトラと衝突 【上必殺ワザ】",
    textJp: "速度が上がっている時にカベや天井にぶつかると、無防備な状態で落下してしまう。しかし、ロケット花火で加速している間は、カベや天井にはぶつからない。",
    titleJpEn: "Crashing with Elytra (Up Special)",
    textJpEn: "If Steve hits a wall or ceiling while at high speed, he'll fall in a defenseless state. However, while accelerating from the Firework Rocket, he won't collide with walls or ceilings.",
    titlePt: "Colidindo com a Elytra (Especial Superior)",
    textPt: "Se Steve atingir uma parede ou teto em alta velocidade, ele cai num estado indefeso. Porém, enquanto acelera com o Firework Rocket, ele não colide com paredes ou tetos.",
  },
  {
    titleEn: "[★☆☆] TNT (Down Special)",
    titleJp: "TNT火薬 【下必殺ワザ】",
    textJp: "多くの素材を使い、高威力の爆弾であるTNT火薬と重量感知板を作り出して置く。しばらく経つか、一定以上のダメージを与えるか、重量感知板を踏むと爆発する。",
    titleJpEn: "TNT (Down Special)",
    textJpEn: "Uses a large amount of materials to create and place TNT, a high-power bomb, along with a pressure plate. It explodes after a while, after taking a certain amount of damage, or when the pressure plate is stepped on.",
    titlePt: "TNT (Especial Inferior)",
    textPt: "Usa uma grande quantidade de materiais para criar e colocar TNT, uma bomba de alto poder, junto com uma placa de pressão. Ela explode depois de um tempo, depois de sofrer uma certa quantidade de dano, ou quando a placa de pressão é pisada.",
  },
  {
    titleEn: "[★☆☆] TNT Materials (Down Special)",
    titleJp: "TNT火薬の素材 【下必殺ワザ】",
    textJp: "TNT火薬を作るための素材は、入手しやすいものから使われる。威力はどんな素材から作っても変わらないが、珍しい素材ほど必要数が少ない。",
    titleJpEn: "TNT Materials (Down Special)",
    textJpEn: "Materials to make TNT are used starting with the easiest to obtain. Its power stays the same no matter what material it's made from, but the rarer the material, the fewer are needed.",
    titlePt: "Materiais do TNT (Especial Inferior)",
    textPt: "Os materiais para fazer TNT são usados começando pelos mais fáceis de obter. O poder permanece o mesmo independentemente do material usado, mas quanto mais raro o material, menos são necessários.",
  },
  {
    titleEn: "[★☆☆] Remote TNT Detonation (Down Special)",
    titleJp: "TNT火薬の遠隔起動 【下必殺ワザ】",
    textJp: "地上でワザを出し、ボタンを押したまま左右に移動すると、レッドストーンを使って引火の導線を引く。ボタンを離すと重量感知板を置き、踏むか攻撃するとTNT火薬を起爆する。",
    titleJpEn: "Remote TNT Detonation (Down Special)",
    textJpEn: "Using this move on the ground and moving left or right while holding the button lays a redstone fuse wire. Releasing the button places a pressure plate, and stepping on or attacking it detonates the TNT.",
    titlePt: "Detonação Remota de TNT (Especial Inferior)",
    textPt: "Usar esse golpe no chão e se mover para a esquerda ou direita enquanto segura o botão coloca um fio de redstone. Soltar o botão coloca uma placa de pressão, e pisar ou atacar nela detona o TNT.",
  },
  {
    titleEn: "[★★☆] Several TNT Blocks (Down Special)",
    titleJp: "複数のTNT火薬 【下必殺ワザ】",
    textJp: "他のプレイヤーが置いたTNT火薬でも、自分が置いたTNTがすぐ隣にあるか、引いた導線が繋がっていれば、重量感知板で一緒に起爆できる。",
    titleJpEn: "Several TNT Blocks (Down Special)",
    textJpEn: "Even TNT placed by another player can be detonated together with the pressure plate, as long as Steve's own TNT is right next to it or connected by a laid fuse wire.",
    titlePt: "Vários Blocos de TNT (Especial Inferior)",
    textPt: "Até TNT colocado por outro jogador pode ser detonado junto com a placa de pressão, desde que o próprio TNT de Steve esteja bem ao lado ou conectado por um fio colocado.",
  },
  {
    titleEn: "[★☆☆] TNT Explosion (Down Special)",
    titleJp: "TNT火薬の爆発 【下必殺ワザ】",
    textJp: "近くでTNT火薬が爆発すると、置いたファイターも巻き込まれる。巻き込まれたくない時は、少し離れたところまで導線を引こう。",
    titleJpEn: "TNT Explosion (Down Special)",
    textJpEn: "If TNT explodes nearby, the fighter who placed it can also get caught in the blast. To avoid getting caught, lay the fuse wire out to a spot a bit farther away.",
    titlePt: "Explosão do TNT (Especial Inferior)",
    textPt: "Se o TNT explodir por perto, o lutador que o colocou também pode ser pego pela explosão. Para evitar isso, estenda o fio até um ponto um pouco mais distante.",
  },
  {
    titleEn: "[★☆☆] TNT's Power (Down Special)",
    titleJp: "TNT火薬の威力 【下必殺ワザ】",
    textJp: "爆発の威力は、時間切れや攻撃で爆発した時よりも、重量感知板で起爆した時のほうが少しだけ高い。",
    titleJpEn: "TNT's Power (Down Special)",
    textJpEn: "The explosion's power is slightly higher when detonated via the pressure plate than when it explodes from running out of time or from an attack.",
    titlePt: "Poder do TNT (Especial Inferior)",
    textPt: "O poder da explosão é um pouco maior quando detonado pela placa de pressão do que quando explode por esgotar o tempo ou por um ataque.",
  },
  {
    titleEn: "[★☆☆] House of Boom (Final Smash)",
    titleJp: "トラップルーム 【最後の切りふだ】",
    textJp: "巨大なピストンを作り出して、当たった相手をふっとばし、トラップルームに閉じ込めて部屋ごと爆破する。複数の相手をふっとばせるが、閉じ込める相手は１人だけ。",
    titleJpEn: "Trap Room (Final Smash)",
    textJpEn: "Creates a giant piston that launches any opponent it hits, trapping one of them inside a room and blowing up the whole room. It can launch multiple opponents, but only one can be trapped inside.",
    titlePt: "House of Boom (Ataque Final)",
    textPt: "Cria um pistão gigante que lança qualquer oponente atingido, prendendo um deles dentro de uma sala e explodindo a sala inteira. Pode lançar múltiplos oponentes, mas apenas um pode ficar preso dentro.",
  },
  {
    titleEn: "[★☆☆] Neutral Attack / Side Tilt Attack",
    titleJp: "弱攻撃・横強攻撃",
    textJp: "ボタンを押し続けると、連続で剣を振る。攻撃を続けながら移動することも可能。",
    titleJpEn: "Neutral Attack / Side Tilt Attack",
    textJpEn: "Holding down the button swings the sword repeatedly. Steve can also move while continuing the attack.",
    titlePt: "Ataque Fraco / Ataque Forte Lateral",
    textPt: "Segurar o botão golpeia com a espada repetidamente. Steve também pode se mover enquanto continua o ataque.",
  },
  {
    titleEn: "[★☆☆] Flint and Steel (Down Tilt Attack)",
    titleJp: "ガケ際で火打ち石 【下強攻撃】",
    textJp: "ガケ際でワザを出すと、火打ち石と打ち金で起こした炎を落下させて、ガケ外にいる相手を攻撃できる。",
    titleJpEn: "Flint and Steel at the Ledge (Down Tilt Attack)",
    textJpEn: "Using this move at the edge of a ledge drops flame created with flint and steel, letting Steve attack opponents off the ledge.",
    titlePt: "Flint and Steel na Borda (Ataque Forte para Baixo)",
    textPt: "Usar esse golpe na borda deixa cair uma chama criada com pederneira e aço, permitindo que Steve ataque oponentes fora da borda.",
  },
  {
    titleEn: "[★☆☆] Air Attacks with a Sword",
    titleJp: "剣での空中攻撃",
    textJp: "攻撃ボタンを押しながらジャンプすると、空中で剣を振る。弱攻撃を続けながらジャンプできるため、スキが少ない。",
    titleJpEn: "Air Attacks with a Sword",
    textJpEn: "Jumping while holding down the attack button swings the sword in midair. Since Steve can jump while continuing the neutral attack, it leaves little opening.",
    titlePt: "Ataques Aéreos com Espada",
    textPt: "Pular enquanto segura o botão de ataque golpeia com a espada no ar. Como Steve pode pular enquanto continua o ataque fraco, isso deixa pouca brecha.",
  },
  {
    titleEn: "[★☆☆] Pickaxe Attacks (Forward Air Attack / Back Air Attack)",
    titleJp: "ツルハシでの攻撃 【前・後空中攻撃】",
    textJp: "前空中攻撃と後空中攻撃は、ツルハシを振り下ろして攻撃する。前空中攻撃は、振り下ろした時にわずかな間、メテオ効果がある。",
    titleJpEn: "Pickaxe Attacks (Forward Air Attack / Back Air Attack)",
    textJpEn: "The forward air attack and back air attack swing the pickaxe down to attack. The forward air attack has a meteor effect for a brief moment when it swings down.",
    titlePt: "Ataques com a Picareta (Ataque Aéreo para Frente / Ataque Aéreo para Trás)",
    textPt: "O ataque aéreo para frente e o ataque aéreo para trás golpeiam com a picareta para baixo. O ataque aéreo para frente tem efeito meteoro por um breve instante quando desce.",
  },
  {
    titleEn: "[★☆☆] Anvil (Down Air Attack)",
    titleJp: "金床 【下空中攻撃】",
    textJp: "鉄を使って金床を作り出し、落として攻撃する。金床は短時間で消えるが、それまでは上に乗り続けることができる。",
    titleJpEn: "Anvil (Down Air Attack)",
    textJpEn: "Uses iron to create an anvil, dropping it to attack. The anvil disappears after a short time, but until then, opponents can keep standing on top of it.",
    titlePt: "Anvil (Ataque Aéreo Inferior)",
    textPt: "Usa ferro para criar uma bigorna, derrubando-a para atacar. A bigorna desaparece depois de um curto tempo, mas até lá, é possível continuar em cima dela.",
  },
  {
    titleEn: "[★☆☆] Fishing Rod (Grab Attack)",
    titleJp: "釣り竿 【つかみ】",
    textJp: "地上で出すと釣り竿を振り、捕らえた相手を柵の中に閉じ込める。空中では使えないため注意。",
    titleJpEn: "Fishing Rod (Grab Attack)",
    textJpEn: "Using this on the ground swings the fishing rod, trapping the caught opponent inside a fence. Be careful — it can't be used in midair.",
    titlePt: "Fishing Rod (Golpe de Agarrão)",
    textPt: "Usar esse golpe no chão balança a vara de pescar, prendendo o oponente capturado dentro de uma cerca. Cuidado — não pode ser usado no ar.",
  },
  {
    titleEn: "[★☆☆] Downward Throw",
    titleJp: "下投げ",
    textJp: "下投げは、相手を地面に叩きつける。鉄を持っていれば、さらに金床を作り出して、相手の上に落下させる。",
    titleJpEn: "Downward Throw",
    textJpEn: "The down throw slams the opponent into the ground. If Steve has iron, he can further create an anvil and drop it on the opponent.",
    titlePt: "Arremesso para Baixo",
    textPt: "O arremesso para baixo joga o oponente contra o chão. Se Steve tiver ferro, ele pode ainda criar uma bigorna e derrubá-la sobre o oponente.",
  },
];

async function main() {
  const steve = await db.fighter.findFirst({
    where: { name: { contains: "Steve", mode: "insensitive" } },
    select: { id: true, tips: { select: { id: true, titleEn: true } } },
  });
  if (!steve) { console.log("Steve not found"); return; }

  await db.fighter.update({
    where: { id: steve.id },
    data: {
      curatorOverviewEn: "Steve turns Smash into a resource-management minigame layered on top of a fighter: mining with the neutral special pulls materials in a fixed rarity order (dirt through diamond), the tool used automatically matches the terrain, and every tool degrades with use, dragging down the power of whatever move relies on it until it's repaired or replaced at the crafting table. Crafting itself branches three ways — making a fresh tool when one breaks, upgrading the whole set at once if better materials are on hand, or a faster repair using matching material — and gold tools trade durability for speed while diamond trades crafting time for raw power. Materials also fuel his other specials: the minecart consumes iron to build a cart that can be reboarded twice, decelerates on uphill slopes and needs redstone-and-gold powered rails to climb them, and drags along any opponent it plows into for longer the more damage they're carrying. Elytra turns the up special into a genuine glide with steerable pitch, kicked off by a Firework Rocket that both accelerates him and chip-damages anyone he collides with — though it eventually runs out on a timer and leaves him helpless if he crashes into a wall outside of that boost window. TNT is the most deliberate tool in the kit: a redstone wire can be run out to a remote pressure plate so Steve isn't caught in his own blast, multiple TNT blocks chain together if they're linked or adjacent, and detonating via the pressure plate deals slightly more damage than letting it time out. Even his attacks lean on the crafting theme — the down tilt drops flint-and-steel flame off a ledge, the forward air's pickaxe has a brief meteor window, the down air conjures a temporary anvil to stand on, and the grab is a fishing rod that can't be thrown in midair. None of Steve's tools work in isolation — his entire kit is a loop of gathering, spending, and rebuilding materials, and running dry at the wrong moment is often more dangerous than any single attack.",
      curatorOverviewPt: "Steve transforma o Smash num minigame de gerenciamento de recursos sobreposto a um lutador: minerar com o especial neutro extrai materiais numa ordem fixa de raridade (de terra a diamante), a ferramenta usada corresponde automaticamente ao terreno, e toda ferramenta se degrada com o uso, reduzindo o poder de qualquer golpe que dependa dela até que seja consertada ou substituída na mesa de trabalho. O próprio craft se ramifica de três formas — fazer uma ferramenta nova quando uma quebra, melhorar o conjunto inteiro de uma vez se houver materiais melhores disponíveis, ou um conserto mais rápido usando material correspondente — e as ferramentas de ouro trocam durabilidade por velocidade, enquanto o diamante troca tempo de craft por poder bruto. Os materiais também alimentam seus outros especiais: o minecart consome ferro para construir um carrinho que pode ser reembarcado duas vezes, desacelera em subidas íngremes e precisa de trilhos energizados de redstone e ouro para subi-las, e arrasta qualquer oponente com quem colide por mais tempo quanto maior o dano acumulado dele. A Elytra transforma o especial superior num planeio de verdade com inclinação ajustável, impulsionado por um Firework Rocket que ao mesmo tempo o acelera e causa dano de contato em quem ele colide — embora eventualmente se esgote num tempo limite e o deixe indefeso se colidir com uma parede fora dessa janela de impulso. O TNT é a ferramenta mais deliberada do kit: um fio de redstone pode ser estendido até uma placa de pressão remota para que Steve não seja pego pela própria explosão, múltiplos blocos de TNT se conectam entre si se estiverem ligados ou adjacentes, e detoná-los pela placa de pressão causa um pouco mais de dano do que deixá-los esgotar o tempo. Até os ataques dele se apoiam no tema de craft — o ataque forte para baixo derruba uma chama de pederneira e aço na borda, a picareta do ataque aéreo para frente tem uma breve janela de meteoro, o ataque aéreo inferior conjura uma bigorna temporária para ficar em cima, e o agarrão é uma vara de pescar que não pode ser usada no ar. Nenhuma das ferramentas de Steve funciona isoladamente — o kit inteiro dele é um ciclo de coletar, gastar e reconstruir materiais, e ficar sem eles no momento errado costuma ser mais perigoso do que qualquer ataque isolado.",
      curatorOverviewJp: "スティーブは、ファイターの上に資源管理のミニゲームを重ねたような存在だ——通常必殺ワザでの採掘は決まったレア度順（土からダイヤモンドまで）で素材を引き当て、使う道具は地形に応じて自動的に切り替わり、あらゆる道具は使うほど劣化し、修理か作業台での作り直しをするまで、その道具を使うワザの威力を下げ続ける。クラフトそのものも３つに枝分かれする——道具が壊れた時に新しく作る、より良い素材があれば道具一式を一度に強化する、あるいは同じ材質の素材があればより早く修理する、というように。金の道具は耐久性と引き換えに速さを得て、ダイヤモンドはクラフトの時間と引き換えに生の威力を得る。素材は他の必殺ワザの燃料にもなる——「トロッコ」は鉄を消費して２回まで乗り直せるトロッコを作り、上り坂では減速し、坂を登るにはレッドストーンと金による加速レールが必要で、突っ込んだ相手を、蓄積ダメージが大きいほど長く引きずり回す。「エリトラ」は上必殺ワザを、角度を調整できる本格的な滑空技に変える。出だしのロケット花火が加速をつけると同時に、ぶつかった相手に接触ダメージを与えるが、やがて時間切れになり、その加速の窓の外でカベにぶつかると無防備になってしまう。「TNT火薬」はこのキットの中でも最も計画的な道具だ——レッドストーンの導線を離れた重量感知板まで引けば自分の爆発に巻き込まれずに済み、複数のTNT火薬は隣接しているか導線で繋がっていれば連鎖し、重量感知板で起爆したほうが時間切れや攻撃で爆発させるよりわずかに威力が高い。攻撃技もクラフトのテーマに沿っている——下強攻撃はガケ際で火打ち石の炎を落とし、前空中攻撃のツルハシには一瞬のメテオ判定があり、下空中攻撃は一時的な金床を呼び出して上に乗ることができ、つかみは釣り竿で空中では使えない。スティーブの道具はどれも単独では機能しない——キット全体が素材を集め、使い、作り直す循環であり、間違ったタイミングで素材が尽きることは、単発の攻撃よりも危険なことが多い。",
      curatorOverviewJpEn: "Steve is like a resource-management minigame layered on top of a fighter — mining with the neutral special draws materials in a fixed order of rarity (from dirt to diamond), the tool used automatically switches according to the terrain, and every tool degrades the more it's used, continuing to lower the power of any move that relies on it until it's repaired or remade at a crafting table. Crafting itself branches into three paths — making a new tool when one breaks, upgrading the entire toolset at once if better materials are available, or repairing faster if a matching material is on hand. Gold tools trade durability for speed, while diamond trades crafting time for raw power. Materials also fuel his other special moves — \"Minecart\" consumes iron to build a cart that can be reboarded up to twice, slows down on uphill slopes, and needs a powered rail made from redstone and gold to climb them, dragging along any opponent it rams into for longer the higher their accumulated damage. \"Elytra\" turns the up special into a genuine glide with an adjustable angle. The Firework Rocket at the start both boosts his speed and deals contact damage to anyone he collides with, but it eventually runs out on a timer, and crashing into a wall outside that boost window leaves him defenseless. \"TNT\" is the most deliberate tool in the kit — running a redstone fuse wire out to a distant pressure plate keeps Steve from getting caught in his own blast, multiple TNT blocks chain together if they're adjacent or connected by wire, and detonating via the pressure plate deals slightly more damage than letting it explode from time or an attack. Even his attacks lean into the crafting theme — the down tilt drops flint-and-steel flame at a ledge, the forward air's pickaxe has a brief meteor window, the down air summons a temporary anvil to stand on, and the grab is a fishing rod that can't be used in midair. None of Steve's tools function in isolation — his whole kit is a cycle of gathering, spending, and rebuilding materials, and running out at the wrong moment is often more dangerous than any single attack.",
    },
  });
  console.log("✅ Curator Overview (4 langs)");

  let updated = 0;
  for (const data of TIPS) {
    const tip = steve.tips.find(t => t.titleEn === data.titleEn);
    if (!tip) { console.log(`  ⚠️  Tip não encontrada: "${data.titleEn}"`); continue; }
    await db.fighterTip.update({
      where: { id: tip.id },
      data: {
        titleJp: data.titleJp, textJp: data.textJp,
        titleJpEn: data.titleJpEn, textJpEn: data.textJpEn,
        titlePt: data.titlePt, textPt: data.textPt,
      },
    });
    updated++;
  }
  console.log(`✅ ${updated}/${TIPS.length} tips atualizadas`);

  await db.fighter.update({ where: { id: steve.id }, data: { curationStatus: "approved" } });
  console.log("✅ Steve/Alex aprovados");

  // Sem FighterMove (0 registros) — newcomer DLC exclusivo do Ultimate, não é lacuna.
  // Nenhum troféu existe (newcomer DLC) — fallback via FighterChronicleLink já lista Minecraft corretamente.
  // Sem timing de vídeo novo fornecido. SSBU bio JP ausente — aprovado direto, padrão já estabelecido.
  // Achado curioso preservado, não é erro: o Final Smash localizado como "House of Boom" (EN) se chama
  // "トラップルーム" ("Trap Room", tradução literal) no texto JP original — mantido fiel em cada idioma.

  await db.$disconnect();
}
main().catch(console.error);
