import { db } from "../../lib/db";

const TIPS = [
  { titleEn: "[★☆☆] Gale Strike (Neutral Special)", titleJp: "トルネードショット 【通常必殺ワザ】", textJp: "剣を大きく振って、前方に移動する竜巻を発生させる。竜巻に触れた相手は、真上にキリモミ状にふっとぶ。", titleJpEn: "Tornado Shot (Neutral Special)", textJpEn: "Swings the sword in a wide arc to create a tornado that moves forward. An opponent who touches the tornado is launched straight up in a corkscrew spin.", titlePt: "Gale Strike (Especial Neutro)", textPt: "Balança a espada em um grande arco para criar um tornado que se move para frente. Um adversário que tocar o tornado é lançado diretamente para cima em um giro de saca-rolhas." },
  { titleEn: "[★★☆] Gale Strike's Traits (Neutral Special)", titleJp: "トルネードショットの特徴 【通常必殺ワザ】", textJp: "竜巻は発射後から少しずつ威力が下がっていく。速度が遅い飛び道具なので、追いかけて共に攻めることが可能。", titleJpEn: "Tornado Shot's Traits (Neutral Special)", textJpEn: "The tornado gradually loses power after being launched. Since it's a slow-moving projectile, it can be chased and used to attack alongside it.", titlePt: "As Características do Gale Strike (Especial Neutro)", textPt: "O tornado perde poder gradualmente depois de lançado. Como é um projétil de movimento lento, é possível persegui-lo e atacar junto com ele." },
  { titleEn: "[★☆☆] Gale Strike's Path (Neutral Special)", titleJp: "トルネードショットの弾道 【通常必殺ワザ】", textJp: "剣を大きく振って、縦に長い竜巻を起こす。発射直後に少し沈んで、その後ホップする弾道が特徴。", titleJpEn: "Tornado Shot's Trajectory (Neutral Special)", textJpEn: "Swings the sword in a wide arc to create a vertically long tornado. It's characterized by a trajectory that dips slightly right after launch, then hops upward.", titlePt: "A Trajetória do Gale Strike (Especial Neutro)", textPt: "Balança a espada em um grande arco para criar um tornado verticalmente longo. É caracterizado por uma trajetória que desce levemente logo após o lançamento e depois salta para cima." },
  { titleEn: "[★★☆] Shuriken of Light (Neutral Special)", titleJp: "光手裏剣 【通常必殺ワザ】", textJp: "投げつける手裏剣は、遠くから当てるほどダメージが高い。至近距離で当てても、相手はひるまない。", titleJpEn: "Shuriken of Light (Neutral Special)", textJpEn: "The thrown shuriken deals more damage the farther away it hits. If it connects at point-blank range, the opponent won't flinch.", titlePt: "Shuriken of Light (Especial Neutro)", textPt: "O shuriken arremessado causa mais dano quanto mais longe acertar. Se acertar à queima-roupa, o adversário não sofre atordoamento." },
  { titleEn: "[★☆☆] Blurring Blade (Neutral Special)", titleJp: "ラピッドスラッシュ 【通常必殺ワザ】", textJp: "目の前を連続突きし、最後に剣を斬り上げる。相手との距離を置くように使うなど、身を守るのに適した剣術。", titleJpEn: "Rapid Slash (Neutral Special)", textJpEn: "Delivers a series of thrusts in front, finishing with an upward slash. A swordsmanship technique well-suited for defense, such as using it to keep distance from an opponent.", titlePt: "Blurring Blade (Especial Neutro)", textPt: "Desfere uma série de estocadas à frente, terminando com um corte ascendente. Uma técnica de espada adequada para defesa, como usá-la para manter distância de um adversário." },
  { titleEn: "[★☆☆] Charging Blurring Blade (Neutral Special)", titleJp: "ラピッドスラッシュのため 【通常必殺ワザ】", textJp: "目の前を炎属性で連続突きし、最後は斜め上にふっとばす。ボタン長押しでためることができ、ためるほど攻撃力がアップする。", titleJpEn: "Charging Rapid Slash (Neutral Special)", textJpEn: "Delivers a series of fire-element thrusts in front, finishing by launching the opponent diagonally upward. Holding the button charges the move, and the longer it's charged, the higher its power.", titlePt: "Carregando o Blurring Blade (Especial Neutro)", textPt: "Desfere uma série de estocadas com elemento fogo à frente, terminando ao lançar o adversário na diagonal para cima. Segurar o botão carrega o golpe, e quanto mais tempo carregado, maior seu poder." },
  { titleEn: "[★☆☆] Airborne Assault (Side Special)", titleJp: "変則急襲斬り 【横必殺ワザ】", textJp: "剣を構え、回転しながら地形に沿って突撃する。当たると相手をふっとばし、自分は反動で上に飛び上がる。", titleJpEn: "Irregular Assault Slash (Side Special)", textJpEn: "Readies the sword and charges forward along the terrain while spinning. On hit, it launches the opponent and, from the recoil, leaps upward itself.", titlePt: "Airborne Assault (Especial Lateral)", textPt: "Prepara a espada e avança girando ao longo do terreno. Ao acertar, lança o adversário e, pelo recuo, salta para cima." },
  { titleEn: "[★☆☆] Gale Stab (Side Special)", titleJp: "疾風突き 【横必殺ワザ】", textJp: "ためればためるほど、突進する速度と攻撃力が上がる。空中で出した時は、突進後に無防備になって落下してしまう。", titleJpEn: "Gale Stab (Side Special)", textJpEn: "The longer it's charged, the higher its dashing speed and power become. When used in the air, it leaves the user defenseless and falling after the dash.", titlePt: "Gale Stab (Especial Lateral)", textPt: "Quanto mais carregado, maior a velocidade de avanço e o poder. Quando usado no ar, deixa o usuário indefeso e caindo depois do avanço." },
  { titleEn: "[★☆☆] Chakram (Side Special)", titleJp: "チャクラム 【横必殺ワザ】", textJp: "リング状の飛び道具を投げつける。地形に当たるとささる。投げる直前に上下の方向入力で、投げる角度を調整できる。", titleJpEn: "Chakram (Side Special)", textJpEn: "Throws a ring-shaped projectile that sticks into the terrain on contact. Inputting up or down right before throwing adjusts the throwing angle.", titlePt: "Chakram (Especial Lateral)", textPt: "Arremessa um projétil em formato de anel que se crava no terreno ao entrar em contato. Inputar cima ou baixo logo antes de arremessar ajusta o ângulo do arremesso." },
  { titleEn: "[★★☆] Chakram's Traits (Side Special)", titleJp: "チャクラムの特性 【横必殺ワザ】", textJp: "はじき入力で、チャクラムの攻撃力や速度が上がる。投げる直前に上下入力すると、角度を調整できる。", titleJpEn: "Chakram's Traits (Side Special)", textJpEn: "A flick input increases the Chakram's power and speed. Inputting up or down right before throwing allows the angle to be adjusted.", titlePt: "As Características do Chakram (Especial Lateral)", textPt: "Um input rápido de flick aumenta o poder e a velocidade do Chakram. Inputar cima ou baixo logo antes de arremessar permite ajustar o ângulo." },
  { titleEn: "[★★★] Stone Scabbard (Up Special)", titleJp: "ロケット下突き 【上必殺ワザ】", textJp: "斬り上げながら上昇した後、剣を下に突き出して急降下。落ちていく間は、剣にメテオ効果がある。", titleJpEn: "Rocket Downward Thrust (Up Special)", textJpEn: "Rises with an upward slash, then thrusts the sword downward and descends rapidly. The sword has a meteor effect while falling.", titlePt: "Stone Scabbard (Especial Cima)", textPt: "Sobe com um corte ascendente e então crava a espada para baixo e desce rapidamente. A espada tem efeito meteoro durante a queda." },
  { titleEn: "[★★☆] Piercing Stone Scabbard (Up Special)", titleJp: "ロケット下突きの貫通 【上必殺ワザ】", textJp: "着地した時、足場を突き抜けた剣にも攻撃力がある。足場の下にいる相手に攻撃することも可能。", titleJpEn: "Rocket Downward Thrust's Piercing (Up Special)", textJpEn: "When it lands, the sword that pierces through the platform still has attack power, making it possible to hit opponents below the platform.", titlePt: "A Perfuração do Stone Scabbard (Especial Cima)", textPt: "Ao pousar, a espada que perfura a plataforma ainda tem poder de ataque, tornando possível acertar adversários abaixo da plataforma." },
  { titleEn: "[★☆☆] Skyward Slash Dash (Up Special)", titleJp: "ソードダッシュ 【上必殺ワザ】", textJp: "連続斬りをしながら突進。方向入力で好きな向きに突進できる。空中なら、眼下の相手への奇襲としても使える。", titleJpEn: "Sword Dash (Up Special)", textJpEn: "Dashes forward while delivering a series of slashes. A direction can be input to dash in any preferred direction. In the air, it can also be used as a surprise attack on opponents below.", titlePt: "Skyward Slash Dash (Especial Cima)", textPt: "Avança enquanto desfere uma série de cortes. Uma direção pode ser inputada para avançar na direção preferida. No ar, também pode ser usado como um ataque surpresa contra adversários abaixo." },
  { titleEn: "[★☆☆] Hero's Spin (Up Special)", titleJp: "回転斬り 【上必殺ワザ】", textJp: "その場で回転しながら、周囲を斬りつける。空中で出すと上昇するので、復帰にも使える。", titleJpEn: "Spin Slash (Up Special)", textJpEn: "Spins in place, slashing everything nearby. Using it in the air causes it to rise, so it can also be used for recovery.", titlePt: "Hero's Spin (Especial Cima)", textPt: "Gira no lugar, cortando tudo ao redor. Usá-lo no ar faz o personagem subir, então também pode ser usado para recuperação." },
  { titleEn: "[★☆☆] Blade Counter (Down Special)", titleJp: "カウンター 【下必殺ワザ】", textJp: "相手の攻撃を受け流して反撃する。成功した後は素早く動けるので、追撃を狙うことも可能。", titleJpEn: "Counter (Down Special)", textJpEn: "Parries an opponent's attack and counterattacks. After a successful counter, it can move quickly, making a follow-up attack possible.", titlePt: "Blade Counter (Especial Baixo)", textPt: "Para o ataque de um adversário e contra-ataca. Depois de um contra-ataque bem-sucedido, é possível se mover rapidamente, tornando possível um ataque de acompanhamento." },
  { titleEn: "[★★★] Blade Counter Technique (Down Special)", titleJp: "カウンターのテクニック 【下必殺ワザ】", textJp: "空中で使うことで、落下する速度を遅くすることができる。着地際の攻撃を狙う相手のタイミングをずらすなど、かけひきに使える。", titleJpEn: "Counter Technique (Down Special)", textJpEn: "Using it in the air can slow down the falling speed. It can be used tactically, such as to throw off the timing of an opponent aiming for an attack upon landing.", titlePt: "A Técnica do Blade Counter (Especial Baixo)", textPt: "Usá-lo no ar pode reduzir a velocidade de queda. Pode ser usado taticamente, como para atrapalhar o tempo de um adversário que mira um ataque no momento do pouso." },
  { titleEn: "[★☆☆] Reversal Slash (Down Special)", titleJp: "リバーススラッシュ 【下必殺ワザ】", textJp: "剣を振って風を起こし、飛び道具を跳ね返す。風を相手に当てれば、体の向きを反転させる効果がある。", titleJpEn: "Reversal Slash (Down Special)", textJpEn: "Swings the sword to create wind that deflects projectiles. If the wind hits an opponent, it has the effect of turning their body around.", titlePt: "Reversal Slash (Especial Baixo)", textPt: "Balança a espada para criar vento que rebate projéteis. Se o vento atingir um adversário, tem o efeito de virar o corpo dele." },
  { titleEn: "[★★☆] Power Thrust (Down Special)", titleJp: "ジェットスタッブ 【下必殺ワザ】", textJp: "地上で出すと、剣を突き出して横に突進する。空中で使うと斜め下に急降下。剣の先端は威力が高い。", titleJpEn: "Jet Stab (Down Special)", textJpEn: "On the ground, it thrusts the sword forward and dashes sideways. In the air, it descends rapidly at a diagonal downward angle. The tip of the sword deals higher damage.", titlePt: "Power Thrust (Especial Baixo)", textPt: "No chão, crava a espada para frente e avança lateralmente. No ar, desce rapidamente em um ângulo diagonal para baixo. A ponta da espada causa mais dano." },
  { titleEn: "[★☆☆] Final Edge (Final Smash)", titleJp: "ファイナルエッジ 【最後の切りふだ】", textJp: "素早く剣を振り、衝撃波を扇状に打ち出していく。地形を抜けるうえに長射程なので、ガケを覆うように出せば、相手を撃墜しやすい。", titleJpEn: "Final Edge (Final Smash)", textJpEn: "Swings the sword rapidly, sending out shockwaves in a fan shape. Since it passes through terrain and has long range, using it to cover the ledge makes it easy to KO opponents.", titlePt: "Final Edge (Final Smash)", textPt: "Balança a espada rapidamente, lançando ondas de choque em formato de leque. Como atravessa o terreno e tem longo alcance, usá-lo para cobrir a borda facilita nocautear adversários." },
  { titleEn: "[★☆☆] Mii Fighters' Origins", titleJp: "Miiの初登場作品", textJp: "Miiの初登場は２００６年。Wiiの内蔵ソフト『似顔絵チャンネル』で作成が可能。さまざまなゲームで活躍させることができる。", titleJpEn: "Mii Fighters' Debut Work", textJpEn: "Mii's debut was in 2006. They can be created using the Wii's built-in software \"Mii Channel,\" and can be featured active in a wide variety of games.", titlePt: "As Origens dos Mii Fighters", textPt: "A estreia do Mii foi em 2006. Eles podem ser criados usando o software integrado do Wii \"Canal Mii\", e podem atuar em uma grande variedade de jogos." },
];

async function main() {
  const swordfighter = await db.fighter.findFirst({
    where: { name: "Mii Swordfighter" },
    select: {
      id: true,
      tips: { select: { id: true, titleEn: true } },
    },
  });
  if (!swordfighter) { console.log("Mii Swordfighter not found"); return; }

  await db.fighter.update({
    where: { id: swordfighter.id },
    data: {
      curatorOverviewEn: "Mii Swordfighter is the mid-range technician of the Mii Fighter trio, wielding a blade with reach and versatility that reward precise spacing. Its neutral special options include the slow-moving, area-controlling Gale Strike and the punishing, chargeable Blurring Blade, while Chakram and Gale Stab extend its threat range further out. Its up specials double as recovery and offense — Stone Scabbard threatens a meteor smash on the way down, and Hero's Spin doubles as a solid vertical recovery. Blade Counter punishes overaggressive opponents, and Final Edge's long, terrain-piercing shockwave makes for a devastating edgeguard finisher. Like all Mii Fighters, its identity shifts entirely based on which special moves are equipped.",
      curatorOverviewPt: "Mii Swordfighter é o técnico de médio alcance do trio Mii Fighter, empunhando uma lâmina com alcance e versatilidade que recompensam o posicionamento preciso. Suas opções de especial neutro incluem o Gale Strike, de movimento lento e controle de área, e o punitivo e carregável Blurring Blade, enquanto Chakram e Gale Stab estendem ainda mais seu alcance de ameaça. Seus especiais de cima funcionam tanto como recuperação quanto como ofensiva — Stone Scabbard ameaça um meteoro na descida, e Hero's Spin funciona como uma boa recuperação vertical. Blade Counter pune adversários excessivamente agressivos, e a onda de choque longa e que atravessa terreno do Final Edge é um finalizador devastador para edge guard. Como todos os Mii Fighters, sua identidade muda completamente dependendo de quais golpes especiais estão equipados.",
      curatorOverviewJp: "Mii 剣術タイプは、Miiファイター３タイプの中で中距離技術に長けた存在で、間合いと汎用性を兼ね備えた剣を操り、正確な間合い管理に応える。通常必殺ワザには、低速でエリアを制圧する「トルネードショット」や、ためが可能で厳しい「ラピッドスラッシュ」があり、「チャクラム」や「疾風突き」はさらに間合いを広げる。上必殺ワザは復帰と攻撃を兼ねる――「ロケット下突き」は落下中にメテオの脅威を与え、「回転斬り」は確実な縦復帰としても機能する。「カウンター」は過剰に攻めてくる相手を罰し、「ファイナルエッジ」の長射程で地形を貫通する衝撃波は、ガケ狩りの決定打となる。すべてのMiiファイターと同様、その個性は装備する必殺ワザによって完全に変化する。",
      curatorOverviewJpEn: "Mii Swordfighter is the mid-range technician among the Mii Fighter trio, wielding a blade with reach and versatility that rewards precise spacing. Its Neutral Special options include the slow, area-controlling Gale Strike and the punishing, chargeable Blurring Blade, while Chakram and Gale Stab extend its threat range even further. Its Up Specials serve double duty as recovery and offense — Stone Scabbard threatens a meteor effect on the way down, while Hero's Spin also functions as a reliable vertical recovery. Blade Counter punishes overly aggressive opponents, and Final Edge's long-range, terrain-piercing shockwave makes for a decisive edge-guard finisher. Like all Mii Fighters, its identity changes completely depending on which special moves are equipped.",
    },
  });
  console.log("✅ Curator Overview (4 langs)");

  let updated = 0;
  for (const data of TIPS) {
    const tip = swordfighter.tips.find(t => t.titleEn === data.titleEn);
    if (!tip) { console.log(`  ⚠️  Tip não encontrada: "${data.titleEn}"`); continue; }
    await db.fighterTip.update({
      where: { id: tip.id },
      data: {
        titleJp: data.titleJp, textJp: data.textJp,
        titleJpEn: data.titleJpEn, textJpEn: data.textJpEn,
        titlePt: data.titlePt, textPt: data.textPt,
      },
    });
    updated++;
  }
  console.log(`✅ ${updated}/${TIPS.length} tips atualizadas`);

  // Orphaned trophies: "Mii Swordfighter" e "Mii Swordfighter (Alt.)" nunca foram linkados desde o scraping.
  // Nomes originais no banco vieram duplicados do scraping ("Mii Swordfighter Mii Sword Fighter" /
  // "... (Alt.) Mii Sword Fighter (Alt.)") — já normalizados via scratch_swordfighter_rename.ts antes deste script rodar.
  const main = await db.collectible.findFirst({ where: { name: "Mii Swordfighter", type: "TROPHY", smashGameVersion: "SSB4" }, select: { id: true, videoStartSec: true, videoEndSec: true, videoStartSec2: true, videoEndSec2: true } });
  if (main) {
    await db.collectible.update({ where: { id: main.id }, data: { fighterId: swordfighter.id, videoStartSec: 40, videoEndSec: 50, videoStartSec2: 27, videoEndSec2: 37 } });
    console.log(`✅ Trophy "Mii Swordfighter" [SSB4]: linkado, vídeo WiiU 40-50 | 3DS 27-37 (era ${main.videoStartSec}-${main.videoEndSec} | ${main.videoStartSec2}-${main.videoEndSec2})`);
  }
  const alt = await db.collectible.findFirst({ where: { name: "Mii Swordfighter (Alt.)", type: "TROPHY", smashGameVersion: "SSB4" }, select: { id: true } });
  if (alt) {
    await db.collectible.update({ where: { id: alt.id }, data: { fighterId: swordfighter.id } });
    console.log(`✅ Trophy "Mii Swordfighter (Alt.)" [SSB4]: linkado (vídeo mantido, já plausível)`);
  }

  await db.$disconnect();
}
main().catch(console.error);
