import { db } from "../../lib/db";

const BIO_PT_JPEN: Record<string, { pt: string; jpEn: string }> = {
  SSB4: {
    jpEn: "The protagonist of \"Mega Man,\" an action game released by Capcom in 1987. He clears each stage by making full use of weapons obtained from defeated bosses. In Smash Bros., he also carries an extensive arsenal. \"Metal Blade\" is a projectile that can be thrown in eight directions and has a piercing effect. When thrown on the ground, it can be picked up and used as an item.",
    pt: "O protagonista de \"Mega Man,\" um jogo de ação lançado pela Capcom em 1987. Ele completa cada fase usando ao máximo as armas obtidas de chefes derrotados. Em Smash Bros., ele também carrega um vasto arsenal. \"Metal Blade\" é um projétil que pode ser arremessado em oito direções e tem um efeito perfurante. Quando arremessado no chão, pode ser pego e usado como um item.",
  },
  SSBU: {
    jpEn: "The protagonist of the \"Mega Man\" series. His original form was \"DRN.001 Rock,\" a boy-shaped domestic helper robot created by Dr. Light, an authority in robotics. When the evil genius scientist Dr. Wily declared his intent to conquer the world, Rock volunteered to be modified for combat in order to protect peace, and was reborn as Mega Man.",
    pt: "O protagonista da série \"Mega Man.\" Sua forma original era \"DRN.001 Rock,\" um robô doméstico ajudante em forma de garoto criado pelo Dr. Light, uma autoridade em robótica. Quando o gênio maligno Dr. Wily declarou sua intenção de conquistar o mundo, o Rock se voluntariou para ser modificado para combate a fim de proteger a paz, e renasceu como Mega Man.",
  },
};

const TIPS = [
  { titleEn: "[★☆☆] Mega Man's Origins", titleJp: "ロックマンの初登場作品", textJp: "ロックマンの初登場作品は、１９８７年に発売された『ロックマン』。ボスから入手した武器を使ってクリアを目指す、戦略性の高い作品。", titleJpEn: "Mega Man's Origins", textJpEn: "Mega Man's debut was in \"Mega Man,\" released in 1987. A highly strategic game where you aim to clear stages using weapons obtained from bosses.", titlePt: "As Origens do Mega Man", textPt: "O debut do Mega Man foi em \"Mega Man,\" lançado em 1987. Um jogo altamente estratégico onde você busca completar as fases usando armas obtidas de chefes." },
  { titleEn: "[★☆☆] In His Series", titleJp: "原作では", textJp: "ライト博士に作られた、家庭用お手伝いロボットの「ロック」。平和を守るために自ら志願して、戦闘用に改造された。太陽エネルギーが動力源。", titleJpEn: "In His Series", textJpEn: "\"Rock,\" a domestic helper robot created by Dr. Light. He volunteered to be modified for combat in order to protect peace. Solar energy is his power source.", titlePt: "Na Série Original", textPt: "\"Rock,\" um robô doméstico ajudante criado pelo Dr. Light. Ele se voluntariou para ser modificado para combate a fim de proteger a paz. Energia solar é sua fonte de energia." },
  { titleEn: "[★☆☆] Mega Man Series", titleJp: "『ロックマン』シリーズ", textJp: "１９８７年発売の『ロックマン』をはじめとして、全世界でのシリーズ累計は３,２００万本以上のセールスを記録した。", titleJpEn: "Mega Man Series", textJpEn: "Starting with \"Mega Man,\" released in 1987, the series has recorded over 32 million units sold worldwide.", titlePt: "A Série Mega Man", textPt: "Começando com \"Mega Man,\" lançado em 1987, a série já registrou mais de 32 milhões de unidades vendidas em todo o mundo." },
  { titleEn: "[★☆☆] Metal Blade (Neutral Special)", titleJp: "メタルブレード 【通常必殺ワザ】", textJp: "「メタルブレード」は、８方向に貫通する刃を投げる通常必殺ワザ。『ロックマン2 Dr.ワイリーの謎』のボス、メタルマンの特殊武器。", titleJpEn: "Metal Blade (Neutral Special)", textJpEn: "\"Metal Blade\" is a neutral special that throws piercing blades in 8 directions. It's the special weapon of Metal Man, a boss from \"Mega Man 2.\"", titlePt: "Metal Blade (Especial Neutro)", textPt: "\"Metal Blade\" é um especial neutro que arremessa lâminas perfurantes em 8 direções. É a arma especial do Metal Man, um chefe de \"Mega Man 2.\"" },
  { titleEn: "[★★☆] Metal Blade as an Item (Neutral Special)", titleJp: "メタルブレードがアイテムに 【通常必殺ワザ】", textJp: "地面に刺さるとアイテムとして拾えるが、威力は下がる。刺さっているメタルブレードは相手も拾えるので、先に拾われないように。", titleJpEn: "Metal Blade as an Item (Neutral Special)", textJpEn: "When it sticks into the ground, it can be picked up as an item, but its power decreases. Since a stuck Metal Blade can also be picked up by the opponent, don't let them get to it first.", titlePt: "Metal Blade como Item (Especial Neutro)", textPt: "Quando se crava no chão, pode ser pego como item, mas seu poder diminui. Como um Metal Blade cravado também pode ser pego pelo adversário, não deixe que ele chegue primeiro." },
  { titleEn: "[★☆☆] Crash Bomber (Side Special)", titleJp: "クラッシュボム 【横必殺ワザ】", textJp: "横必殺ワザは、相手や地形にくっついて爆発する「クラッシュボム」。『ロックマン2 Dr.ワイリーの謎』のボス、クラッシュマンの特殊武器。", titleJpEn: "Crash Bomber (Side Special)", textJpEn: "The side special is \"Crash Bomb,\" which sticks to an opponent or terrain and explodes. It's the special weapon of Crash Man, a boss from \"Mega Man 2.\"", titlePt: "Crash Bomber (Especial Lateral)", textPt: "O especial lateral é \"Crash Bomb,\" que gruda em um adversário ou no cenário e explode. É a arma especial do Crash Man, um chefe de \"Mega Man 2.\"" },
  { titleEn: "[★☆☆] Crash Bomber Connection (Side Special)", titleJp: "クラッシュボムなすりつけ 【横必殺ワザ】", textJp: "クラッシュボムはカベや地面にも貼りつく。ファイターについたボムは、相手になすりつけることも可能。", titleJpEn: "Crash Bomber Connection (Side Special)", textJpEn: "Crash Bomb also sticks to walls and the ground. A bomb stuck to a fighter can also be rubbed off onto an opponent.", titlePt: "A Conexão do Crash Bomber (Especial Lateral)", textPt: "Crash Bomb também gruda em paredes e no chão. Uma bomba grudada em um lutador também pode ser esfregada em um adversário." },
  { titleEn: "[★☆☆] Rush Coil (Up Special)", titleJp: "ラッシュコイル 【上必殺ワザ】", textJp: "「ラッシュコイル」は相棒のラッシュに乗って大ジャンプする上必殺ワザ。ラッシュは『ロックマン3 Dr.ワイリーの最期!?』で初めて登場した。", titleJpEn: "Rush Coil (Up Special)", textJpEn: "\"Rush Coil\" is an up special where he rides his partner Rush for a big jump. Rush first appeared in \"Mega Man 3.\"", titlePt: "Rush Coil (Especial Cima)", textPt: "\"Rush Coil\" é um especial cima em que ele monta em seu parceiro Rush para um grande pulo. O Rush apareceu pela primeira vez em \"Mega Man 3.\"" },
  { titleEn: "[★☆☆] Midair Jump after Rush Coil (Up Special)", titleJp: "ラッシュコイルからの空中ジャンプ 【上必殺ワザ】", textJp: "ラッシュコイル使用後は自由に動け、空中ジャンプもできる。復帰に使う時は、先にラッシュコイルを使って、空中ジャンプを温存することも可能。", titleJpEn: "Midair Jump after Rush Coil (Up Special)", textJpEn: "After using Rush Coil, he can move freely and even air jump. When using it for recovery, using Rush Coil first can also save the air jump for later.", titlePt: "Pulo Aéreo Depois do Rush Coil (Especial Cima)", textPt: "Depois de usar o Rush Coil, ele pode se mover livremente e até pular no ar. Ao usá-lo para recuperação, usar o Rush Coil primeiro também pode guardar o pulo aéreo para depois." },
  { titleEn: "[★★☆] Rush Coil's Downtime (Up Special)", titleJp: "出現済みのラッシュコイル 【上必殺ワザ】", textJp: "出現済みのラッシュコイルに乗った時の方が、最初にワザを使った時のジャンプより高く飛べる。また、呼び出したラッシュコイルには相手も乗れる。", titleJpEn: "Rush Coil's Downtime (Up Special)", textJpEn: "Riding an already-summoned Rush Coil launches him higher than the jump from first using the move. Also, an opponent can also ride a summoned Rush Coil.", titlePt: "O Tempo de Espera do Rush Coil (Especial Cima)", textPt: "Montar em um Rush Coil já invocado o lança mais alto do que o pulo ao usar o golpe pela primeira vez. Além disso, um adversário também pode montar em um Rush Coil invocado." },
  { titleEn: "[★☆☆] Leaf Shield (Down Special)", titleJp: "リーフシールド 【下必殺ワザ】", textJp: "ロックマンの下必殺ワザは、木の葉で身を守る「リーフシールド」。『ロックマン2 Dr.ワイリーの謎』のボス、ウッドマンの特殊武器。", titleJpEn: "Leaf Shield (Down Special)", textJpEn: "Mega Man's down special is \"Leaf Shield,\" which protects him with leaves. It's the special weapon of Wood Man, a boss from \"Mega Man 2.\"", titlePt: "Leaf Shield (Especial Baixo)", textPt: "O especial baixo do Mega Man é \"Leaf Shield,\" que o protege com folhas. É a arma especial do Wood Man, um chefe de \"Mega Man 2.\"" },
  { titleEn: "[★☆☆] Mega Legends (Final Smash)", titleJp: "ロックマンスペシャル【最後の切りふだ】", textJp: "最後の切りふだに登場するのは、ロックマン、エックス、ロック・ヴォルナット、ロックマン.EXE、シューティングスター・ロックマン、ブルース、フォルテの総勢７人。", titleJpEn: "Mega Legends (Final Smash)", textJpEn: "The Final Smash features a total of 7 characters: Mega Man, X, Volnutt, Mega Man.EXE, Shooting Star Rockman, Proto Man, and Bass.", titlePt: "Mega Legends (Final Smash)", textPt: "O Final Smash apresenta um total de 7 personagens: Mega Man, X, Volnutt, Mega Man.EXE, Shooting Star Rockman, Proto Man e Bass." },
  { titleEn: "[★★☆] Mega Legends Timing (Final Smash)", titleJp: "ロックマンスペシャルのタイミング【最後の切りふだ】", textJp: "ブラックホールボムは相手に命中する以外にも、必殺ワザボタンを押して好きなタイミングで爆発させ、近くの相手を巻き込むことができる。", titleJpEn: "Mega Legends Timing (Final Smash)", textJpEn: "Besides hitting an opponent directly, the Black Hole Bomb can also be detonated at a chosen moment by pressing the special move button, catching nearby opponents.", titlePt: "O Timing do Mega Legends (Final Smash)", textPt: "Além de acertar um adversário diretamente, a Black Hole Bomb também pode ser detonada em um momento escolhido apertando o botão de golpe especial, pegando adversários próximos." },
  { titleEn: "[★☆☆] The Mega Buster (Neutral Attack / Side Tilt Attack / Neutral Air Attack)", titleJp: "ロックバスターとは 【弱・横強・通常空中攻撃】", textJp: "ロックバスターは腕に装着された武器で、エネルギー弾を放つことができる。初代『ロックマン』の頃から、標準装備されている。", titleJpEn: "The Mega Buster (Neutral Attack / Side Tilt Attack / Neutral Air Attack)", textJpEn: "The Mega Buster is a weapon mounted on his arm that can fire energy shots. It has been his standard equipment since the original \"Mega Man.\"", titlePt: "O Mega Buster (Ataque Neutro / Inclinado Lateral / Aéreo Neutro)", textPt: "O Mega Buster é uma arma montada em seu braço que pode disparar tiros de energia. É seu equipamento padrão desde o \"Mega Man\" original." },
  { titleEn: "[★★☆] One Mega Buster at a Time", titleJp: "ロックバスターは片方ずつ 【弱・横強・通常空中攻撃】", textJp: "太陽エネルギーを圧縮した弾「ソーラーブリット」を放つ。両腕ともバスターに変形可能だが、エネルギーが強力なため、片方ずつしか撃てない。", titleJpEn: "One Mega Buster at a Time", textJpEn: "Fires a shot called \"Solar Blit,\" made of compressed solar energy. Both arms can transform into Busters, but because the energy is so powerful, only one can fire at a time.", titlePt: "Um Mega Buster de Cada Vez", textPt: "Dispara um tiro chamado \"Solar Blit,\" feito de energia solar comprimida. Ambos os braços podem se transformar em Busters, mas como a energia é muito poderosa, só um pode disparar por vez." },
  { titleEn: "[★☆☆] Mega Upper (Up Tilt Attack)", titleJp: "ロックアッパー 【上強攻撃】", textJp: "相手を上空にふっとばすロックマンの上強攻撃「ロックアッパー」。『ロックマン2・ザ・パワーファイターズ』などでロックマンが使える必殺技。", titleJpEn: "Mega Upper (Up Tilt Attack)", textJpEn: "Mega Man's up tilt attack, \"Mega Upper,\" launches opponents into the sky. It's a special technique Mega Man can use in \"Mega Man 2: The Power Fighters\" and other titles.", titlePt: "Mega Upper (Ataque Inclinado Cima)", textPt: "O ataque inclinado cima do Mega Man, \"Mega Upper,\" arremessa os adversários para o céu. É uma técnica especial que o Mega Man pode usar em \"Mega Man 2: The Power Fighters\" e outros títulos." },
  { titleEn: "[★★☆] A Clean Mega Upper (Up Tilt Attack)", titleJp: "ロックアッパーのクリーンヒット 【上強攻撃】", textJp: "ワザの開始直後に当てると、相手を真上に強くふっとばす。外した後のスキが大きいけれど、クリーンヒットで一発逆転も狙える。", titleJpEn: "A Clean Mega Upper (Up Tilt Attack)", textJpEn: "Landing it right at the start of the move launches the opponent hard straight upward. The opening after missing is large, but a clean hit can be a game-changer.", titlePt: "Um Mega Upper Limpo (Ataque Inclinado Cima)", textPt: "Acertá-lo bem no início do golpe arremessa o adversário fortemente para cima. A abertura depois de errar é grande, mas um golpe limpo pode virar o jogo." },
  { titleEn: "[★☆☆] Sliding (Down Tilt Attack)", titleJp: "スライディング 【下強攻撃】", textJp: "ロックマンが下強攻撃で放つ「スライディング」。もともとは、『ロックマン3 Dr.ワイリーの最期!?』以降で使える移動手段。", titleJpEn: "Sliding (Down Tilt Attack)", textJpEn: "\"Sliding,\" which Mega Man performs as his down tilt attack. It was originally a movement technique usable starting from \"Mega Man 3.\"", titlePt: "Sliding (Ataque Inclinado Baixo)", textPt: "\"Sliding,\" que o Mega Man realiza como seu ataque inclinado baixo. Originalmente, era uma técnica de movimento utilizável a partir de \"Mega Man 3.\"" },
  { titleEn: "[★☆☆] Charge Shot (Side Smash Attack)", titleJp: "チャージショット 【横スマッシュ攻撃】", textJp: "横スマッシュ攻撃は、エネルギーをためて撃つ「チャージショット」。『ロックマン4 新たなる野望!!』で初めて使えるようになった攻撃。", titleJpEn: "Charge Shot (Side Smash Attack)", textJpEn: "The side smash attack is \"Charge Shot,\" fired after charging up energy. It's an attack that first became usable in \"Mega Man 4.\"", titlePt: "Charge Shot (Ataque Smash Lateral)", textPt: "O ataque smash lateral é \"Charge Shot,\" disparado depois de carregar energia. É um ataque que se tornou utilizável pela primeira vez em \"Mega Man 4.\"" },
  { titleEn: "[★☆☆] Charging Charge Shot (Side Smash Attack)", titleJp: "チャージショットのため 【横スマッシュ攻撃】", textJp: "前方に強力なチャージショットを撃つ。ためた時間に応じて、攻撃力だけでなく飛距離もアップする。", titleJpEn: "Charging Charge Shot (Side Smash Attack)", textJpEn: "Fires a powerful Charge Shot forward. Depending on the charge time, both attack power and range increase.", titlePt: "Carregando o Charge Shot (Ataque Smash Lateral)", textPt: "Dispara um poderoso Charge Shot para frente. Dependendo do tempo de carga, tanto o poder de ataque quanto o alcance aumentam." },
  { titleEn: "[★☆☆] Spark Shock (Up Smash Attack)", titleJp: "スパークショック 【上スマッシュ攻撃】", textJp: "頭上で放電する「スパークショック」は、ロックマンの上スマッシュ攻撃。『ロックマン3 Dr.ワイリーの最期!?』のボス、スパークマンの特殊武器。", titleJpEn: "Spark Shock (Up Smash Attack)", textJpEn: "\"Spark Shock,\" which discharges electricity above his head, is Mega Man's up smash attack. It's the special weapon of Spark Man, a boss from \"Mega Man 3.\"", titlePt: "Spark Shock (Ataque Smash Cima)", textPt: "\"Spark Shock,\" que descarrega eletricidade acima de sua cabeça, é o ataque smash cima do Mega Man. É a arma especial do Spark Man, um chefe de \"Mega Man 3.\"" },
  { titleEn: "[★☆☆] Flame Blast (Down Smash Attack)", titleJp: "フレイムブラスト 【下スマッシュ攻撃】", textJp: "ロックマンの下スマッシュ攻撃は、両手で火柱を放つ「フレイムブラスト」。『ロックマン6 史上最大の戦い!!』のボス、フレイムマンの特殊武器。", titleJpEn: "Flame Blast (Down Smash Attack)", textJpEn: "Mega Man's down smash attack is \"Flame Blast,\" which releases pillars of fire from both hands. It's the special weapon of Flame Man, a boss from \"Mega Man 6.\"", titlePt: "Flame Blast (Ataque Smash Baixo)", textPt: "O ataque smash baixo do Mega Man é \"Flame Blast,\" que libera colunas de fogo de ambas as mãos. É a arma especial do Flame Man, um chefe de \"Mega Man 6.\"" },
  { titleEn: "[★☆☆] Flame Sword (Forward Air Attack)", titleJp: "フレイムソード 【前空中攻撃】", textJp: "「フレイムソード」は、炎の剣で斬りつけるロックマンの前空中攻撃。『ロックマン8 メタルヒーローズ』のボス、ソードマンの特殊武器。", titleJpEn: "Flame Sword (Forward Air Attack)", textJpEn: "\"Flame Sword\" is Mega Man's forward air attack where he slashes with a fiery sword. It's the special weapon of Sword Man, a boss from \"Mega Man 8.\"", titlePt: "Flame Sword (Ataque Aéreo Frente)", textPt: "\"Flame Sword\" é o ataque aéreo frontal do Mega Man, em que ele corta com uma espada flamejante. É a arma especial do Sword Man, um chefe de \"Mega Man 8.\"" },
  { titleEn: "[★☆☆] Slash Claw (Back Air Attack)", titleJp: "スラッシュクロー 【後空中攻撃】", textJp: "ロックマンの後空中攻撃は連続ヒットする「スラッシュクロー」。『ロックマン7 宿命の対決!』のボス、スラッシュマンの特殊武器。", titleJpEn: "Slash Claw (Back Air Attack)", textJpEn: "Mega Man's back air attack is \"Slash Claw,\" which hits multiple times. It's the special weapon of Slash Man, a boss from \"Mega Man 7.\"", titlePt: "Slash Claw (Ataque Aéreo Trás)", textPt: "O ataque aéreo traseiro do Mega Man é \"Slash Claw,\" que acerta múltiplas vezes. É a arma especial do Slash Man, um chefe de \"Mega Man 7.\"" },
  { titleEn: "[★☆☆] Air Shooter (Up Air Attack)", titleJp: "エアーシューター 【上空中攻撃】", textJp: "「エアーシューター」は、竜巻を上に飛ばすロックマンの上空中攻撃。『ロックマン2 Dr.ワイリーの謎』のボス、エアーマンの特殊武器。", titleJpEn: "Air Shooter (Up Air Attack)", textJpEn: "\"Air Shooter\" is Mega Man's up air attack that launches a tornado upward. It's the special weapon of Air Man, a boss from \"Mega Man 2.\"", titlePt: "Air Shooter (Ataque Aéreo Cima)", textPt: "\"Air Shooter\" é o ataque aéreo cima do Mega Man, que lança um tornado para cima. É a arma especial do Air Man, um chefe de \"Mega Man 2.\"" },
  { titleEn: "[★☆☆] Air Shooter's Tornado (Up Air Attack)", titleJp: "エアーシューターで竜巻発射 【上空中攻撃】", textJp: "小さい竜巻を真上に向かって発射する。竜巻は当たった相手を巻き込んで上昇する。", titleJpEn: "Air Shooter's Tornado (Up Air Attack)", textJpEn: "Fires a small tornado straight upward. The tornado catches any opponent it hits and carries them up.", titlePt: "O Tornado do Air Shooter (Ataque Aéreo Cima)", textPt: "Dispara um pequeno tornado diretamente para cima. O tornado pega qualquer adversário que atinge e o carrega para cima." },
  { titleEn: "[★☆☆] Hard Knuckle (Down Air Attack)", titleJp: "ハードナックル 【下空中攻撃】", textJp: "ロックマンの下空中攻撃はロケットパンチを下に撃つ「ハードナックル」。『ロックマン3 Dr.ワイリーの最期!?』のボス、ハードマンの特殊武器。", titleJpEn: "Hard Knuckle (Down Air Attack)", textJpEn: "Mega Man's down air attack is \"Hard Knuckle,\" which fires a rocket punch downward. It's the special weapon of Hard Man, a boss from \"Mega Man 3.\"", titlePt: "Hard Knuckle (Ataque Aéreo Baixo)", textPt: "O ataque aéreo baixo do Mega Man é \"Hard Knuckle,\" que dispara um soco-foguete para baixo. É a arma especial do Hard Man, um chefe de \"Mega Man 3.\"" },
  { titleEn: "[★★★] Hard Knuckle Meteor (Down Air Attack)", titleJp: "ハードナックルでメテオ 【下空中攻撃】", textJp: "真下に飛ぶ腕は、ロックマンから少し離れてからメテオ効果が発生する。相手を真下に落としたい時は、相手との距離を少し空けた方がうまくいく。", titleJpEn: "Hard Knuckle Meteor (Down Air Attack)", textJpEn: "The arm that flies straight down gains its meteor effect after traveling a short distance from Mega Man. To send an opponent straight down, it works better to keep a bit of distance from them.", titlePt: "Meteoro com o Hard Knuckle (Ataque Aéreo Baixo)", textPt: "O braço que voa diretamente para baixo ganha seu efeito de meteoro depois de percorrer uma curta distância do Mega Man. Para derrubar um adversário diretamente para baixo, funciona melhor manter um pouco de distância dele." },
  { titleEn: "[★☆☆] Top Spin (Dash Attack)", titleJp: "タップスピン 【ダッシュ攻撃】", textJp: "「タップスピン」は、回転してダメージを与えるロックマンのダッシュ攻撃。『ロックマン3 Dr.ワイリーの最期!?』のボス、タップマンの特殊武器。", titleJpEn: "Top Spin (Dash Attack)", textJpEn: "\"Top Spin\" is Mega Man's dash attack where he spins to deal damage. It's the special weapon of Top Man, a boss from \"Mega Man 3.\"", titlePt: "Top Spin (Ataque em Disparada)", textPt: "\"Top Spin\" é o ataque em disparada do Mega Man, em que ele gira para causar dano. É a arma especial do Top Man, um chefe de \"Mega Man 3.\"" },
  { titleEn: "[★☆☆] Super Arm (Grab Attack)", titleJp: "スーパーアーム 【つかみ】", textJp: "つかみアクションは、大きな相手も軽々と持ち上げる「スーパーアーム」。初代『ロックマン』のボス、ガッツマンの特殊武器。", titleJpEn: "Super Arm (Grab Attack)", textJpEn: "The grab action is \"Super Arm,\" which effortlessly lifts even large opponents. It's the special weapon of Guts Man, a boss from the original \"Mega Man.\"", titlePt: "Super Arm (Agarrão)", textPt: "A ação de agarrar é \"Super Arm,\" que levanta com facilidade até adversários grandes. É a arma especial do Guts Man, um chefe do \"Mega Man\" original." },
  { titleEn: "[★☆☆] Mega Man's Heat Release System", titleJp: "ロックマンの排熱処理", textJp: "両腕をバスターに変形させるワザを使うと、オーバーヒート。使用後は、腕から熱を放出する。", titleJpEn: "Mega Man's Heat Release System", textJpEn: "Using a move that transforms both arms into Busters causes overheating. After use, heat is released from his arms.", titlePt: "O Sistema de Liberação de Calor do Mega Man", textPt: "Usar um golpe que transforma ambos os braços em Busters causa superaquecimento. Depois do uso, calor é liberado de seus braços." },
];

async function main() {
  const megaman = await db.fighter.findFirst({
    where: { name: { contains: "Mega Man" } },
    select: {
      id: true,
      bios: { select: { id: true, smashGameVersion: true } },
      moves: { select: { id: true, smashGameVersion: true, order: true } },
      tips: { select: { id: true, titleEn: true } },
    },
  });
  if (!megaman) { console.log("Mega Man not found"); return; }

  await db.fighter.update({
    where: { id: megaman.id },
    data: {
      curatorOverviewEn: "Mega Man is a projectile specialist unlike anyone else in Smash, using almost no traditional attacks — nearly every move is one of his classic Robot Master weapons, from Metal Blade's eight-directional throw to Leaf Shield's rotating barrier to Crash Bomber's sticky detonation. Rush Coil offers a powerful recovery that can be pre-placed and reused, while his Charge Shot rewards patient spacing. A pure zoner with an answer for nearly every situation drawn straight from his 30-year arsenal, Mega Man rewards players who keep opponents at range and pepper them with a rotating toolkit rather than engaging directly.",
      curatorOverviewPt: "Mega Man é um especialista em projéteis como nenhum outro no Smash, usando quase nenhum ataque tradicional — quase todo golpe é uma de suas armas clássicas de Robot Master, do arremesso em oito direções do Metal Blade à barreira giratória do Leaf Shield à detonação grudenta do Crash Bomber. Rush Coil oferece uma recuperação poderosa que pode ser pré-posicionada e reutilizada, enquanto seu Charge Shot recompensa posicionamento paciente. Um controlador de espaço puro com uma resposta para quase toda situação extraída diretamente de seu arsenal de 30 anos, o Mega Man recompensa jogadores que mantêm os adversários à distância e os desgastam com um arsenal rotativo em vez de se engajar diretamente.",
      curatorOverviewJp: "ロックマンは、スマブラの中で他の誰とも違う飛び道具の専門家であり、従来の攻撃をほとんど使わない――ほぼすべての技が、メタルブレードの８方向投げからリーフシールドの回転バリア、クラッシュボムの貼り付き爆発まで、彼のクラシックなロボットマスターの武器のいずれかだ。ラッシュコイルは事前に設置して再利用できる強力な復帰を提供し、チャージショットは忍耐強い間合い管理に応える。30年分の武器庫からそのまま引き出されたほぼすべての状況への答えを持つ純粋な空間制圧型ファイターであるロックマンは、直接交戦するのではなく相手を遠ざけ、回転する武器庫で削っていくプレイヤーに応える。",
      curatorOverviewJpEn: "Mega Man is a projectile specialist unlike anyone else in Smash, using almost no traditional attacks — nearly every move is one of his classic Robot Master weapons, from Metal Blade's eight-directional throw to Leaf Shield's rotating barrier to Crash Bomber's sticky detonation. Rush Coil provides a powerful recovery that can be pre-placed and reused, while Charge Shot rewards patient spacing. A pure space-control fighter with an answer for nearly every situation drawn straight from his 30-year arsenal, Mega Man rewards players who keep opponents at a distance and wear them down with a rotating toolkit rather than engaging directly.",
    },
  });
  console.log("✅ Curator Overview (4 langs)");

  for (const [version, data] of Object.entries(BIO_PT_JPEN)) {
    const bio = megaman.bios.find(b => b.smashGameVersion === version);
    if (!bio) continue;
    await db.fighterBio.update({ where: { id: bio.id }, data: { contentPt: data.pt, contentJpEn: data.jpEn } });
    console.log(`✅ Bio [${version}]: PT+JpEn adicionados`);
  }

  const move = megaman.moves.find(m => m.smashGameVersion === "SSB4" && m.order === 0);
  if (move) {
    const en = "Mega Man uses over 10 different weapons. \"Flame Sword,\" his forward air attack, has a wide range and small opening, making it useful in many situations. \"Leaf Shield\" is a special move that deploys four rotating leaves around him. Besides acting as a barrier to protect against projectiles, it can also hit opponents directly or be launched forward as an attack. (FC) Mega Man (1987/12) (FC) Mega Man 2 (1988/12)";
    await db.fighterMove.update({
      where: { id: move.id },
      data: {
        descEn: en, descJpEn: en,
        descPt: "Mega Man usa mais de 10 armas diferentes. \"Flame Sword,\" seu ataque aéreo frontal, tem um amplo alcance e pequena abertura, tornando-o útil em muitas situações. \"Leaf Shield\" é um golpe especial que implanta quatro folhas giratórias ao seu redor. Além de atuar como uma barreira para proteger contra projéteis, também pode acertar adversários diretamente ou ser lançado para frente como um ataque. (FC) Mega Man (1987/12) (FC) Mega Man 2 (1988/12)",
      },
    });
    console.log("✅ Move [SSB4] EX: EN+PT+JpEn adicionados");
  }

  let updated = 0;
  for (const data of TIPS) {
    const tip = megaman.tips.find(t => t.titleEn === data.titleEn);
    if (!tip) { console.log(`  ⚠️  Tip não encontrada: "${data.titleEn}"`); continue; }
    await db.fighterTip.update({
      where: { id: tip.id },
      data: {
        titleJp: data.titleJp, textJp: data.textJp,
        titleJpEn: data.titleJpEn, textJpEn: data.textJpEn,
        titlePt: data.titlePt, textPt: data.textPt,
      },
    });
    updated++;
  }
  console.log(`✅ ${updated}/${TIPS.length} tips atualizadas`);

  // Link orphaned "Star Force Mega Man" [SSB4]
  const starForce = await db.collectible.findFirst({ where: { name: "Star Force Mega Man", smashGameVersion: "SSB4", type: "TROPHY" }, select: { id: true } });
  if (starForce) {
    await db.collectible.update({ where: { id: starForce.id }, data: { fighterId: megaman.id } });
    console.log("✅ \"Star Force Mega Man\": linkado");
  }

  await db.$disconnect();
}
main().catch(console.error);
