import { db } from "../../lib/db";

const BIO_PT_JPEN: Record<string, { pt: string; jpEn: string }> = {
  SSB4: {
    jpEn: "Joins the fight from \"Fire Emblem Fates.\" Born in the Kingdom of Hoshido, Corrin was kidnapped by the Kingdom of Nohr at a young age and raised as one of its own. Having inherited a strong bloodline from the First Dragons, Corrin can use the power of dragons. In \"Super Smash Bros.\" too, Corrin's defining trait is \"Dragon Fang,\" which turns part of the body draconic. The sharply extended limbs have reach, and since hitting with the tip deals high damage, managing spacing is important.",
    pt: "Entra na luta vindo de \"Fire Emblem Fates\". Nascido no Reino de Hoshido, Corrin foi sequestrado pelo Reino de Nohr ainda jovem e criado como um dos seus. Tendo herdado uma linhagem forte dos Primeiros Dragões, Corrin pode usar o poder dos dragões. Também em \"Super Smash Bros.\", a característica que define Corrin é o \"Dragon Fang\", que transforma parte do corpo em algo dracônico. Os membros afiados e estendidos têm alcance, e como acertar com a ponta causa alto dano, gerenciar a distância é importante.",
  },
};

const TIPS = [
  { titleEn: "[★☆☆] In Their Series", titleJp: "原作では", textJp: "『ファイアーエムブレムif』の主人公で、王族の血を引いている。神祖竜の血を受け継いでいるため、竜に変身することができる。", titleJpEn: "In the Original Game", textJpEn: "The protagonist of \"Fire Emblem Fates,\" of royal blood. Having inherited the blood of the First Dragons, Corrin can transform into a dragon.", titlePt: "Na Série Original", textPt: "O protagonista de \"Fire Emblem Fates\", de sangue real. Tendo herdado o sangue dos Primeiros Dragões, Corrin pode se transformar em um dragão." },
  { titleEn: "[★☆☆] Omega Yato", titleJp: "夜刀神・終夜", textJp: "カムイが使用している武器は、「夜刀神」が４つの神器と共鳴し、最後の進化を遂げた最強の形態である、「夜刀神・終夜」。", titleJpEn: "Yato: Owari", textJpEn: "The weapon Corrin wields is \"Yato: Owari,\" the strongest form the \"Yato\" reaches after resonating with the four other divine weapons and undergoing its final evolution.", titlePt: "Omega Yato", textPt: "A arma que o Corrin empunha é o \"Yato: Owari\", a forma mais forte que o \"Yato\" alcança após ressoar com as outras quatro armas divinas e passar por sua evolução final." },
  { titleEn: "[★☆☆] Charging Dragon Fang Shot (Neutral Special)", titleJp: "竜穿射のため 【通常必殺ワザ】", textJp: "水弾の発射前と後の２回、ボタン長押しでためが可能。発射前のためは水弾が、発射後のためは噛みつきが強化される。", titleJpEn: "Charging Dragon Fang Shot (Neutral Special)", textJpEn: "It can be charged twice by holding down the button — once before firing the water bullet, and again after. Charging before launch strengthens the water bullet, while charging afterward strengthens the bite.", titlePt: "Carregando o Dragon Fang Shot (Especial Neutro)", textPt: "Pode ser carregado duas vezes segurando o botão — uma antes de disparar a bala de água, e outra depois. Carregar antes do disparo fortalece a bala de água, enquanto carregar depois fortalece a mordida." },
  { titleEn: "[★☆☆] Dragon Fang Shot's Blast (Neutral Special)", titleJp: "竜穿射の弾 【通常必殺ワザ】", textJp: "放たれる水弾にはしびれ効果がついている。密着した相手に弾が当たった時はため続けた強力な噛みつきを当てるチャンス。", titleJpEn: "Dragon Fang Shot's Bullet (Neutral Special)", textJpEn: "The water bullet that's fired has a paralysis effect. When it hits an opponent up close, it's a chance to land the powerful, fully-charged bite.", titlePt: "A Bala do Dragon Fang Shot (Especial Neutro)", textPt: "A bala de água disparada tem um efeito de paralisia. Quando acerta um adversário de perto, é uma chance de acertar a mordida poderosa e totalmente carregada." },
  { titleEn: "[★★☆] Dragon Lunge and Terrain (Side Special)", titleJp: "跳槍突と地形 【横必殺ワザ】", textJp: "槍の先端を地形に当てると突き刺して追加行動を出せる。ステージによってはカベに突き刺すことで復帰にも使える。", titleJpEn: "Dragon Lunge and Terrain (Side Special)", textJpEn: "Hitting terrain with the tip of the lance skewers it, allowing a follow-up action. On some stages, skewering a wall can also be used for recovery.", titlePt: "Dragon Lunge e o Terreno (Especial Lateral)", textPt: "Atingir o terreno com a ponta da lança a crava nele, permitindo uma ação de acompanhamento. Em alguns palcos, cravar em uma parede também pode ser usado para recuperação." },
  { titleEn: "[★☆☆] Lockdown with Dragon Lunge (Side Special)", titleJp: "跳槍突で拘束 【横必殺ワザ】", textJp: "地形に槍が刺さると同時に命中した相手を一定時間拘束できる。拘束されている時間はレバガチャで短くすることができる。", titleJpEn: "Restraining with Dragon Lunge (Side Special)", textJpEn: "If the lance sticks into terrain at the same moment it hits an opponent, it can restrain them for a set amount of time. The restrained duration can be shortened by mashing the control stick.", titlePt: "Prendendo com o Dragon Lunge (Especial Lateral)", textPt: "Se a lança se cravar no terreno no mesmo momento em que acerta um adversário, pode prendê-lo por um período determinado. A duração da prisão pode ser reduzida sacudindo o analógico repetidamente." },
  { titleEn: "[★★☆] Dragon Lunge Tips (Side Special)", titleJp: "跳槍突のコツ 【横必殺ワザ】", textJp: "地上で出すとき、必殺ワザボタンから攻撃ボタンを滑るように スライド入力すると、素早く地形へ刺して留まることができる。", titleJpEn: "Dragon Lunge Tips (Side Special)", textJpEn: "When using it on the ground, sliding your input from the special move button to the attack button lets it quickly stick into the terrain and stay there.", titlePt: "Dicas do Dragon Lunge (Especial Lateral)", textPt: "Ao usá-lo no chão, deslizar o input do botão de golpe especial para o botão de ataque faz com que ele se crave rapidamente no terreno e permaneça lá." },
  { titleEn: "[★★☆] Actions after Dragon Lunge (Side Special)", titleJp: "跳槍突からの行動 【横必殺ワザ】", textJp: "空中で出すと、すぐ槍を突き刺し、地上では、ジャンプ後のボタン入力で突き刺す。槍が地面に刺さったら、スティック横でキック、上でジャンプ、下でキャンセルできる。", titleJpEn: "Actions after Dragon Lunge (Side Special)", textJpEn: "Using it in midair immediately thrusts the lance, while on the ground it thrusts on a button input after jumping. Once the lance is stuck in the ground, tilting the stick sideways kicks, up jumps, and down cancels.", titlePt: "Ações Após o Dragon Lunge (Especial Lateral)", textPt: "Usá-lo no ar crava a lança imediatamente, enquanto no chão ela crava com um input de botão após pular. Uma vez que a lança está cravada no chão, inclinar o analógico para o lado chuta, para cima pula, e para baixo cancela." },
  { titleEn: "[★☆☆] Dragon Ascent's Direction (Up Special)", titleJp: "翔竜翼の方向 【上必殺ワザ】", textJp: "飛び上がる時に左右へ入力をすることで角度を調整できる。向いている方向とは逆に入力しておくと真上に高く移動できる。", titleJpEn: "Dragon Ascent's Direction (Up Special)", textJpEn: "The angle of flight can be adjusted by inputting left or right when leaping up. Inputting the opposite direction from where he's facing lets him rise straight up to a greater height.", titlePt: "A Direção do Dragon Ascent (Especial Cima)", textPt: "O ângulo de voo pode ser ajustado inputando esquerda ou direita ao saltar. Inputar a direção oposta a que está virado permite subir reto até uma altura maior." },
  { titleEn: "[★★☆] Invincibility for Dragon Ascent (Up Special)", titleJp: "翔竜翼の無敵時間 【上必殺ワザ】", textJp: "出だしで力を溜めてしゃがんでいる時に全身無敵がある。タイミングを合わせ、相手の攻撃に割り込んで使うこともできる。", titleJpEn: "Invincibility for Dragon Ascent (Up Special)", textJpEn: "There's full-body invincibility during the crouch at the start of the move while gathering power. Timing it right can even interrupt an opponent's attack.", titlePt: "A Invencibilidade do Dragon Ascent (Especial Cima)", textPt: "Há invencibilidade de corpo inteiro durante o agachamento no início do golpe enquanto acumula poder. Cronometrar corretamente pode até interromper o ataque de um adversário." },
  { titleEn: "[★☆☆] Counter Surge (Down Special)", titleJp: "反竜穿 【下必殺ワザ】", textJp: "カウンターした相手を上方向に勢いよくふっとばす。ステージ上空でカウンターに成功すると撃墜を狙いやすい。", titleJpEn: "Counter Surge (Down Special)", textJpEn: "Launches a countered opponent forcefully upward. Successfully countering high above the stage makes it easy to aim for a KO.", titlePt: "Counter Surge (Especial Baixo)", textPt: "Lança um adversário contra-atacado com força para cima. Contra-atacar com sucesso bem acima do palco torna fácil mirar um nocaute." },
  { titleEn: "[★★☆] Area Attack with Counter Surge (Down Special)", titleJp: "反竜穿で範囲攻撃 【下必殺ワザ】", textJp: "他のカウンターと比べて反撃までの時間が少し遅めだが、自分の周囲全体を攻撃する。多人数の乱闘で特に有効。", titleJpEn: "Area Attack with Counter Surge (Down Special)", textJpEn: "Compared to other counters, the time until the counterattack is a bit slower, but it attacks the entire area around him. Especially effective in multi-fighter battles.", titlePt: "Ataque em Área com o Counter Surge (Especial Baixo)", textPt: "Comparado a outros contra-ataques, o tempo até o contra-golpe é um pouco mais lento, mas ataca toda a área ao redor dele. Especialmente eficaz em lutas com múltiplos lutadores." },
  { titleEn: "[★☆☆] Torrential Roar (Final Smash)", titleJp: "激流咆 【最後の切りふだ】", textJp: "光の柱を出現させ、当たった相手を激流でふっとばす。光の柱は、自分の上にいる相手にも当てられる。", titleJpEn: "Torrential Roar (Final Smash)", textJpEn: "Summons pillars of light and launches any opponent hit with a raging torrent. The pillars of light can also hit opponents directly above.", titlePt: "Torrential Roar (Final Smash)", textPt: "Convoca colunas de luz e lança qualquer adversário atingido com uma torrente furiosa. As colunas de luz também podem acertar adversários diretamente acima." },
  { titleEn: "[★★★] Options for Dragon Fang Thrust (Side Smash Attack)", titleJp: "竜穿突の出し分け 【横スマッシュ攻撃】", textJp: "スマッシュホールドで構えている間、夜刀神に攻撃判定がある。リーチがあり上下に出し分けることもできる重要なワザ。", titleJpEn: "Options for Dragon Fang Thrust (Side Smash Attack)", textJpEn: "While holding the smash charge, the Yato blade itself has a hitbox. An important move with reach that can also be angled up or down.", titlePt: "Opções do Dragon Fang Thrust (Ataque Smash Lateral)", textPt: "Enquanto segura a carga do smash, a própria lâmina Yato tem uma hitbox. Um golpe importante com alcance que também pode ser angulado para cima ou para baixo." },
  { titleEn: "[★☆☆] Tip on Dragon Fang Thrust (Side Smash Attack)", titleJp: "竜穿突の先端 【横スマッシュ攻撃】", textJp: "槍のように鋭く尖った腕の先端は、威力がとても高い。常に先端ヒットを狙えるような立ち回りを意識して戦うと良い。", titleJpEn: "Tip on Dragon Fang Thrust (Side Smash Attack)", textJpEn: "The sharply pointed tip of the lance-like arm deals very high damage. It's good to fight with positioning in mind that always allows aiming for a tip hit.", titlePt: "Dica do Dragon Fang Thrust (Ataque Smash Lateral)", textPt: "A ponta afiada e pontiaguda do braço em forma de lança causa dano muito alto. É bom lutar com o posicionamento em mente que sempre permite mirar um acerto de ponta." },
  { titleEn: "[★☆☆] Vertical Dragon Fang Thrust (Up Smash Attack)", titleJp: "直上竜穿突 【上スマッシュ攻撃】", textJp: "低い姿勢になり真上を攻撃する。槍のように鋭く伸びた両腕は、先端の威力が高い。意識して一番強い部分で狙おう。", titleJpEn: "Vertical Dragon Fang Thrust (Up Smash Attack)", textJpEn: "Gets into a low stance and attacks straight up. Both arms extend sharply like lances, and their tips deal high damage. Aim consciously for the strongest part.", titlePt: "Vertical Dragon Fang Thrust (Ataque Smash Cima)", textPt: "Assume uma postura baixa e ataca diretamente para cima. Ambos os braços se estendem afiados como lanças, e suas pontas causam alto dano. Mire conscientemente na parte mais forte." },
  { titleEn: "[★☆☆] Yato Dragon Fang (Down Smash Attack)", titleJp: "夜刀竜穿 【下スマッシュ攻撃】", textJp: "前後に対して同時に攻撃でき、背後は槍のように竜化した足で突き刺す。背後を意識して威力が高い先端ヒットを狙おう。", titleJpEn: "Yato Dragon Fang (Down Smash Attack)", textJpEn: "Attacks forward and backward simultaneously, thrusting behind with a leg transformed into a lance. Keep the rear in mind and aim for the high-damage tip hit.", titlePt: "Yato Dragon Fang (Ataque Smash Baixo)", textPt: "Ataca para frente e para trás simultaneamente, estocando atrás com uma perna transformada em lança. Tenha a retaguarda em mente e mire no acerto de ponta de alto dano." },
  { titleEn: "[★☆☆] Dragon Fang Wings (Back Air Attack)", titleJp: "竜穿翼 【後空中攻撃】", textJp: "竜穿によって背中に生やした竜の羽根で羽ばたいて攻撃する。攻撃の反動で自身が前方に押し出されるので復帰にも使える。", titleJpEn: "Dragon Fang Wings (Back Air Attack)", textJpEn: "Attacks by flapping dragon wings grown on his back through Dragon Fang. The recoil from the attack pushes him forward, so it can also be used for recovery.", titlePt: "Dragon Fang Wings (Ataque Aéreo de Trás)", textPt: "Ataca batendo asas de dragão que crescem em suas costas através do Dragon Fang. O recuo do ataque o empurra para frente, então também pode ser usado para recuperação." },
  { titleEn: "[★☆☆] Dragon's Piercing Drop (Down Air Attack)", titleJp: "竜穿落 【下空中攻撃】", textJp: "両足を鋭い槍のように変化させて勢いよく真下に急降下する。着地にも判定があるが、シールドされるとスキが大きいので注意。", titleJpEn: "Dragon's Piercing Drop (Down Air Attack)", textJpEn: "Transforms both legs into sharp lances and dives straight down forcefully. There's a hitbox on landing too, but be careful, as it leaves a big opening if shielded.", titlePt: "Dragon's Piercing Drop (Ataque Aéreo Baixo)", textPt: "Transforma ambas as pernas em lanças afiadas e mergulha reto para baixo com força. Também há uma hitbox no pouso, mas cuidado, pois deixa uma grande abertura se bloqueado." },
  { titleEn: "[★☆☆] Dragon-Form Kick (Downward Throw)", titleJp: "竜化蹴 【下投げ】", textJp: "勢いよく叩きつけた前足で、足元を広く攻撃する。近くの相手を巻き込んでふっとばすことが可能。うまく追撃しよう。", titleJpEn: "Dragon-Form Kick (Downward Throw)", textJpEn: "Attacks a wide area at his feet with a forceful stomp of the front leg. It can catch and launch nearby opponents as well. Follow up well.", titlePt: "Dragon-Form Kick (Arremesso Baixo)", textPt: "Ataca uma ampla área aos seus pés com um pisão forte da perna dianteira. Pode pegar e lançar adversários próximos também. Emende bem em seguida." },
  { titleEn: "[★☆☆] Get Multiple Opponents with a Throw", titleJp: "投げでの巻き込み攻撃", textJp: "前投げ・後ろ投げは腕を槍のように鋭く伸ばし、他のファイターを巻き込み攻撃できる。先端に当てれば、強くふっとばすことができる。", titleJpEn: "Catching Multiple Opponents with a Throw", textJpEn: "The forward throw and backward throw extend the arm sharply like a lance, allowing it to catch and attack other fighters as well. Hitting with the tip launches them powerfully.", titlePt: "Pegando Múltiplos Adversários com um Arremesso", textPt: "O arremesso para frente e o arremesso para trás estendem o braço de forma afiada como uma lança, permitindo pegar e atacar outros lutadores também. Acertar com a ponta os lança com força." },
];

async function main() {
  const corrin = await db.fighter.findFirst({
    where: { name: "Corrin" },
    select: {
      id: true,
      bios: { select: { id: true, smashGameVersion: true } },
      moves: { select: { id: true, smashGameVersion: true, order: true } },
      tips: { select: { id: true, titleEn: true } },
    },
  });
  if (!corrin) { console.log("Corrin not found"); return; }

  await db.fighter.update({
    where: { id: corrin.id },
    data: {
      curatorOverviewEn: "Corrin's kit is built around Dragon Fang, the ability to transform limbs into lance-like extensions with a sharp, high-damage tip and mediocre power everywhere else, rewarding precise spacing over raw button presses. Dragon Lunge can skewer terrain to hold position, trap grounded opponents, or serve as a wall-cling recovery, while Dragon Ascent grants brief full-body invincibility during its windup, useful for interrupting attacks mid-recovery. Counter Surge doubles as a single-target vertical launcher or, with the delayed variant, a full 360-degree counter for crowded fights. Charging Dragon Fang Shot in either its projectile or bite phase adds another layer of options for zoning versus punishing. Overall, Corrin plays like a spacing-focused swordfighter whose real reward comes from consistently landing that lance tip rather than brute-forcing exchanges.",
      curatorOverviewPt: "O kit do Corrin é construído em torno do Dragon Fang, a habilidade de transformar os membros em extensões parecidas com lanças, com uma ponta afiada de alto dano e poder mediano no resto, recompensando um posicionamento preciso em vez de apertar botões aleatoriamente. Dragon Lunge pode cravar o terreno para manter posição, prender adversários no chão, ou servir como uma recuperação agarrando-se à parede, enquanto o Dragon Ascent concede uma breve invencibilidade de corpo inteiro durante sua preparação, útil para interromper ataques no meio da recuperação. Counter Surge funciona tanto como um lançador vertical de alvo único quanto, com a variante retardada, como um contra-ataque de 360 graus completo para lutas lotadas. Carregar o Dragon Fang Shot em sua fase de projétil ou de mordida adiciona mais uma camada de opções para controle de área versus punição. No geral, o Corrin joga como um espadachim focado em posicionamento cuja verdadeira recompensa vem de acertar consistentemente a ponta da lança em vez de forçar trocas.",
      curatorOverviewJp: "カムイのキットは「竜穿」を軸に組み立てられている――手足を槍のような延長部分に変化させる能力で、鋭く高威力な先端と、それ以外の部分の平凡な威力を併せ持ち、無闇なボタン連打よりも正確な間合い管理に応える。「跳槍突」は地形に突き刺して位置を保持したり、地上の相手を拘束したり、壁にしがみつく復帰技として使ったりでき、「翔竜翼」は出だしの溜め中に短い全身無敵を得られ、復帰の途中で相手の攻撃に割り込むのに便利だ。「反竜穿」は単体を垂直に打ち上げるカウンターとしても、遅延版なら乱戦向けの全方位カウンターとしても機能する。「竜穿射」を発射前・発射後どちらの段階でためるかで、けん制か反撃かの選択肢がさらに広がる。全体として、カムイは槍の先端を安定して当てることこそが真の報酬となる、間合い管理重視の剣士のようにプレイするファイターだ。",
      curatorOverviewJpEn: "Corrin's kit is built around \"Dragon Fang,\" the ability to turn limbs into lance-like extensions with a sharp, high-power tip and mediocre power everywhere else, rewarding precise spacing over reckless button-mashing. \"Dragon Lunge\" can skewer terrain to hold position, restrain grounded opponents, or serve as a wall-cling recovery, while \"Dragon Ascent\" grants brief full-body invincibility during its startup charge, useful for interrupting an opponent's attack mid-recovery. \"Counter Surge\" functions both as a single-target vertical launcher and, in its delayed version, as an all-around counter suited for chaotic multi-fighter brawls. Choosing whether to charge \"Dragon Fang Shot\" before or after firing further widens the choice between zoning and punishing. Overall, Corrin plays like a spacing-focused swordfighter whose true reward comes from consistently landing the tip of the lance rather than forcing exchanges.",
    },
  });
  console.log("✅ Curator Overview (4 langs)");

  for (const [version, data] of Object.entries(BIO_PT_JPEN)) {
    const bio = corrin.bios.find(b => b.smashGameVersion === version);
    if (!bio) continue;
    await db.fighterBio.update({ where: { id: bio.id }, data: { contentPt: data.pt, contentJpEn: data.jpEn } });
    console.log(`✅ Bio [${version}]: PT+JpEn adicionados`);
  }

  const move = corrin.moves.find(m => m.smashGameVersion === "SSB4" && m.order === 0);
  if (move) {
    const en = "The Side Special \"Dragon Lunge\" is not just a direct attack — thrusting the spear-like extended arm into terrain lets Corrin stay in place. Piercing an opponent while skewering terrain works as a special move that traps them in place, impaled. Additional inputs allow follow-ups into a forward kick, backward kick, or jump. Note that it can't be used again until landing once used. (3DS) Fire Emblem Fates (2015/06)";
    await db.fighterMove.update({
      where: { id: move.id },
      data: {
        descEn: en, descJpEn: en,
        descPt: "O especial lateral \"Dragon Lunge\" não é só um ataque direto — cravar o braço estendido em formato de lança no terreno permite que o Corrin fique parado no lugar. Perfurar um adversário enquanto o braço está cravado no terreno funciona como um golpe especial que o prende no lugar, empalado. Inputs adicionais permitem emendar em um chute para frente, chute para trás, ou pulo. Note que não pode ser usado novamente até pousar depois de usado. (3DS) Fire Emblem Fates (2015/06)",
      },
    });
    console.log("✅ Move [SSB4] EX: EN+PT+JpEn adicionados");
  }

  let updated = 0;
  for (const data of TIPS) {
    const tip = corrin.tips.find(t => t.titleEn === data.titleEn);
    if (!tip) { console.log(`  ⚠️  Tip não encontrada: "${data.titleEn}"`); continue; }
    await db.fighterTip.update({
      where: { id: tip.id },
      data: {
        titleJp: data.titleJp, textJp: data.textJp,
        titleJpEn: data.titleJpEn, textJpEn: data.textJpEn,
        titlePt: data.titlePt, textPt: data.textPt,
      },
    });
    updated++;
  }
  console.log(`✅ ${updated}/${TIPS.length} tips atualizadas`);

  // Video fix (usuário via VLC): WiiU 1:28:01-1:28:25 = 5281-5305 no troféu principal
  const main = await db.collectible.findFirst({ where: { name: "Corrin", type: "TROPHY", smashGameVersion: "SSB4" }, select: { id: true, videoStartSec: true, videoEndSec: true } });
  if (main) {
    await db.collectible.update({ where: { id: main.id }, data: { videoStartSec: 5281, videoEndSec: 5305 } });
    console.log(`✅ Trophy "Corrin" [SSB4]: vídeo WiiU corrigido 5281-5305 (era ${main.videoStartSec}-${main.videoEndSec})`);
  }

  await db.$disconnect();
}
main().catch(console.error);
