/**
 * Índice imutável: EN name → JP name canônico (smashwiki.info).
 * Importado por collectibles.ts para o Title Matching.
 */
export const SSBU_ROSTER_JP: Array<{ name: string; jpName: string }> = [
  { name: "Mario",              jpName: "マリオ" },
  { name: "Donkey Kong",        jpName: "ドンキーコング" },
  { name: "Link",               jpName: "リンク" },
  { name: "Samus",              jpName: "サムス" },
  { name: "Dark Samus",         jpName: "ダークサムス" },
  { name: "Yoshi",              jpName: "ヨッシー" },
  { name: "Kirby",              jpName: "カービィ" },
  { name: "Fox",                jpName: "フォックス" },
  { name: "Pikachu",            jpName: "ピカチュウ" },
  { name: "Luigi",              jpName: "ルイージ" },
  { name: "Ness",               jpName: "ネス" },
  { name: "Captain Falcon",     jpName: "キャプテン・ファルコン" },
  { name: "Jigglypuff",         jpName: "プリン" },
  { name: "Peach",              jpName: "ピーチ" },
  { name: "Daisy",              jpName: "デイジー" },
  { name: "Bowser",             jpName: "クッパ" },
  { name: "Ice Climbers",       jpName: "アイスクライマー" },
  { name: "Sheik",              jpName: "シーク" },
  { name: "Zelda",              jpName: "ゼルダ" },
  { name: "Dr. Mario",          jpName: "ドクターマリオ" },
  { name: "Pichu",              jpName: "ピチュー" },
  { name: "Falco",              jpName: "ファルコ" },
  { name: "Marth",              jpName: "マルス" },
  { name: "Lucina",             jpName: "ルキナ" },
  { name: "Young Link",         jpName: "こどもリンク" },
  { name: "Ganondorf",          jpName: "ガノンドロフ" },
  { name: "Mewtwo",             jpName: "ミュウツー" },
  { name: "Roy",                jpName: "ロイ" },
  { name: "Chrom",              jpName: "クロム" },
  { name: "Mr. Game & Watch",   jpName: "Mr.ゲーム＆ウォッチ" },
  { name: "Meta Knight",        jpName: "メタナイト" },
  { name: "Pit",                jpName: "ピット" },
  { name: "Dark Pit",           jpName: "ブラックピット" },
  { name: "Zero Suit Samus",    jpName: "ゼロスーツサムス" },
  { name: "Wario",              jpName: "ワリオ" },
  { name: "Snake",              jpName: "スネーク" },
  { name: "Ike",                jpName: "アイク" },
  { name: "Pokémon Trainer",    jpName: "ポケモントレーナー" },
  { name: "Diddy Kong",         jpName: "ディディーコング" },
  { name: "Lucas",              jpName: "リュカ" },
  { name: "Sonic",              jpName: "ソニック" },
  { name: "King Dedede",        jpName: "デデデ" },
  { name: "Olimar",             jpName: "ピクミン＆オリマー" },
  { name: "Lucario",            jpName: "ルカリオ" },
  { name: "R.O.B.",             jpName: "ロボット" },
  { name: "Toon Link",          jpName: "トゥーンリンク" },
  { name: "Wolf",               jpName: "ウルフ" },
  { name: "Villager",           jpName: "むらびと" },
  { name: "Mega Man",           jpName: "ロックマン" },
  { name: "Wii Fit Trainer",    jpName: "Wii Fitトレーナー" },
  { name: "Rosalina & Luma",    jpName: "ロゼッタ＆チコ" },
  { name: "Little Mac",         jpName: "リトル・マック" },
  { name: "Greninja",           jpName: "ゲッコウガ" },
  { name: "Mii Brawler",        jpName: "Mii格闘タイプ" },
  { name: "Mii Swordfighter",   jpName: "Mii剣術タイプ" },
  { name: "Mii Gunner",         jpName: "Mii射撃タイプ" },
  { name: "Palutena",           jpName: "パルテナ" },
  { name: "Pac-Man",            jpName: "パックマン" },
  { name: "Robin",              jpName: "ルフレ" },
  { name: "Shulk",              jpName: "シュルク" },
  { name: "Bowser Jr.",         jpName: "クッパJr." },
  { name: "Duck Hunt",          jpName: "ダックハント" },
  { name: "Ryu",                jpName: "リュウ" },
  { name: "Ken",                jpName: "ケン" },
  { name: "Cloud",              jpName: "クラウド" },
  { name: "Corrin",             jpName: "カムイ" },
  { name: "Bayonetta",          jpName: "ベヨネッタ" },
  { name: "Inkling",            jpName: "インクリング" },
  { name: "Ridley",             jpName: "リドリー" },
  { name: "Simon",              jpName: "シモン" },
  { name: "Richter",            jpName: "リヒター" },
  { name: "King K. Rool",       jpName: "キングクルール" },
  { name: "Isabelle",           jpName: "しずえ" },
  { name: "Incineroar",         jpName: "ガオガエン" },
  { name: "Piranha Plant",      jpName: "パックンフラワー" },
  { name: "Joker",              jpName: "ジョーカー" },
  { name: "Hero",               jpName: "勇者" },
  { name: "Banjo & Kazooie",    jpName: "バンジョー＆カズーイ" },
  { name: "Terry",              jpName: "テリー" },
  { name: "Byleth",             jpName: "ベレト" },
  { name: "Min Min",            jpName: "ミェンミェン" },
  { name: "Steve",              jpName: "スティーブ" },
  { name: "Sephiroth",          jpName: "セフィロス" },
  { name: "Pyra",               jpName: "ホムラ" },
  { name: "Mythra",             jpName: "ヒカリ" },
  { name: "Kazuya",             jpName: "カズヤ" },
  { name: "Sora",               jpName: "ソラ" },
];
